[phases.install]
cmds = ["cd click-cond-web && npm install"]

[phases.build]
cmds = [
  "cd click-cond-web && npx prisma generate",
  "cd click-cond-web && npx nx build api"
]

[start]
cmd = "cd click-cond-web && node apps/api/dist/main.js"
