name: click
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+11

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:  
  cupertino_icons: ^1.0.8

  easy_mask: ^2.0.1
  rflutter_alert: any
  dotted_border: ^2.1.0
  auto_size_text: any
  mask_text_input_formatter: any
  roundcheckbox: any
  multiselect_formfield: any
  intl: any
  badges: any
  syncfusion_flutter_charts: any
  currency_text_input_formatter: any
  in_app_purchase: any

  flutter:
    sdk: flutter
  contained_tab_bar_view: any
  image_picker: any
  url_launcher: any
  material_design_icons_flutter: any
  localstorage: ^4.0.0
  file_picker: ^8.1.4
  open_filex: any
  flutter_speed_dial: any
  table_calendar: any
  permission_handler: any
  package_info_plus: any
  easy_localization: any
  google_fonts: any
  phosphor_flutter: ^1.4.0

  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: any

  flutter_test:
    sdk: flutter 

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icon/