import 'package:click/utils/localizable/localizable.dart';

class Localizable_PtBr {

  final List<LocalizableModel> strings = [
    // Idioma
    LocalizableModel(key: 'language_idioma', text: 'Idioma'),
    LocalizableModel(key: 'language_pt_br', text: 'Português Brasil'),
    LocalizableModel(key: 'language_pt_pt', text: 'Português Portugal'),
    LocalizableModel(key: 'language_en', text: 'Inglês'),
    LocalizableModel(key: 'language_es', text: 'Espanhol'),
    LocalizableModel(key: 'language_al', text: 'Alemão'),

    // Data
    LocalizableModel(key: 'data_informar', text: 'Informe a data desejada.'),
    LocalizableModel(key: 'data_selecionar_horario', text: 'Selecione o horário desejado.'),
    LocalizableModel(key: 'data_das', text: 'Dàs'),    
    LocalizableModel(key: 'data_as', text: 'Às'),    
    LocalizableModel(key: 'data_e_hora', text: 'Data e Hora'),
    LocalizableModel(key: 'dia_e_hora', text: 'Dia e Hora'),
    LocalizableModel(key: 'dia', text: 'Dia'),
    LocalizableModel(key: 'dias', text: 'dias'),
    LocalizableModel(key: 'data', text: 'Data'),
    LocalizableModel(key: 'datas', text: 'Datas'),
    LocalizableModel(key: 'hora', text: 'Hora'),
    LocalizableModel(key: 'data_inicio', text: 'Data de Início'),
    LocalizableModel(key: 'hora_inicio', text: 'Hora de Início'),
    LocalizableModel(key: 'data_termino', text: 'Data de Término'),
    LocalizableModel(key: 'hora_termino', text: 'Hora de Término'),
    LocalizableModel(key: 'data_hora_criacao', text: 'DATA E HORA DE CRIAÇÃO'),
    LocalizableModel(key: 'data_hora_inicio', text: 'Data e hora de início'),
    LocalizableModel(key: 'segunda', text: 'Segunda'),
    LocalizableModel(key: 'terca', text: 'Terça'),
    LocalizableModel(key: 'quarta', text: 'Quarta'),
    LocalizableModel(key: 'quinta', text: 'Quinta'),
    LocalizableModel(key: 'sexta', text: 'Sexta'),
    LocalizableModel(key: 'sabado', text: 'Sábado'),
    LocalizableModel(key: 'domingo', text: 'Domingo'),

    // Modal Select Month
    LocalizableModel(key: 'modal_select_month_btn_ok', text: 'OK'),
    LocalizableModel(key: 'modal_select_month_btn_cancel', text: 'cancelar'),

    //TextField
    LocalizableModel(key: 'textfield_long_placeholder', text: 'Escreva aqui...'),
    LocalizableModel(key: 'textfield_short_placeholder', text: 'Escreva a sua mensagem...'),

    //Label
    LocalizableModel(key: 'label_to', text: 'Para:'),
    LocalizableModel(key: 'label_of', text: 'de'),
    LocalizableModel(key: 'label_until', text: 'até'),
    LocalizableModel(key: 'ola', text: 'Olá'),
    LocalizableModel(key: 'sindico', text: 'Síndico'),
    LocalizableModel(key: 'morador', text: 'Morador'),
    LocalizableModel(key: 'funcionario', text: 'Funcionário'),
    LocalizableModel(key: 'email', text: 'E-mail'),
    LocalizableModel(key: 'senha', text: 'Senha'),
    LocalizableModel(key: 'vesaoApp', text: 'Versão:'),
    LocalizableModel(key: 'nome', text: 'Nome'),
    LocalizableModel(key: 'user_nome_completo', text: 'Nome Completo'),
    LocalizableModel(key: 'user_documento', text: 'Documento de Identificação'),
    LocalizableModel(key: 'data_nascimento', text: 'Data de Nascimento'),
    LocalizableModel(key: 'email', text: 'E-mail'),
    LocalizableModel(key: 'telefone', text: 'Telefone'),
    LocalizableModel(key: 'senha', text: 'Senha'),
    LocalizableModel(key: 'editar_infos', text: 'Editar Informações'),
    LocalizableModel(key: 'label_exclusao', text: 'Exclusão!'),

    LocalizableModel(key: 'lb_areas_sociais', text: 'Áreas Sociais'),
    LocalizableModel(key: 'lb_area_social', text: 'Área Social'),
    LocalizableModel(key: 'lb_financeiro', text: 'Financeiro'),
    LocalizableModel(key: 'lb_assembleia_votacoes', text: 'Assembléias e Votações'),
    LocalizableModel(key: 'lb_assembleias', text: 'Assembléias'),
    LocalizableModel(key: 'lb_assembleia', text: 'Assembléia'),
    LocalizableModel(key: 'lb_votacoes', text: 'Votações'),
    LocalizableModel(key: 'lb_enquetes', text: 'Enquetes'),
    LocalizableModel(key: 'lb_comunicados', text: 'Comunicados'),
    LocalizableModel(key: 'lb_comunicado', text: 'Comunicado'),
    LocalizableModel(key: 'lb_ocorrencias', text: 'Ocorrências'),
    LocalizableModel(key: 'lb_ocorrencia', text: 'Ocorrência'),
    LocalizableModel(key: 'lb_funcionarios', text: 'Funcionários'),
    LocalizableModel(key: 'lb_funcionarios_condominio', text: 'Funcionários do Condomínio'),
    LocalizableModel(key: 'lb_manut_programadas', text: 'Manutenções Programadas'),
    LocalizableModel(key: 'lb_manut_programada', text: 'Manutenção Programada'),
    LocalizableModel(key: 'lb_prestadores_servico', text: 'Prestadores de Serviço'),
    LocalizableModel(key: 'lb_agendar_mudanca', text: 'Agendar Mudança'),
    LocalizableModel(key: 'lb_cadastrar_visitante', text: 'Cadastrar Visitante'),
    LocalizableModel(key: 'lb_apartamentos', text: 'Apartamentos'),
    LocalizableModel(key: 'lb_apartamento', text: 'Apartamento'),
    LocalizableModel(key: 'lb_docs', text: 'Docs'),
    LocalizableModel(key: 'lb_apto', text: 'Apto'),
    LocalizableModel(key: 'lb_ref', text: 'Ref.'),
    LocalizableModel(key: 'lb_saldo', text: 'Saldo'),
    LocalizableModel(key: 'lb_status', text: 'Status'),
    LocalizableModel(key: 'lb_categorias', text: 'Categorias'),
    LocalizableModel(key: 'lb_categoria', text: 'Categoria'),
    LocalizableModel(key: 'lb_anexos', text: 'Anexos'),
    LocalizableModel(key: 'lb_insira_fotos', text: 'Insira suas fotos aqui'),
    LocalizableModel(key: 'lb_tipo', text: 'Tipo'),
    LocalizableModel(key: 'lb_resposta', text: 'Resposta'),
    LocalizableModel(key: 'lb_todos', text: 'Todos'),
    LocalizableModel(key: 'lb_pendentes', text: 'Pendentes'),
    LocalizableModel(key: 'lb_buscar', text: 'Buscar'),
    LocalizableModel(key: 'lb_aviso', text: 'Aviso'),
    LocalizableModel(key: 'lb_ultima_atualizacao', text: 'Última atualização'),
    LocalizableModel(key: 'lb_ciente', text: 'Ciente'),
    LocalizableModel(key: 'lb_pendente', text: 'Pendente'),
    LocalizableModel(key: 'lb_aprovado', text: 'Aprovado'),
    LocalizableModel(key: 'lb_recusado', text: 'Recusado'),
    LocalizableModel(key: 'lb_solucionado', text: 'Solucionado'),
    LocalizableModel(key: 'lb_nao_informado', text: 'Não Informado'),
    LocalizableModel(key: 'lb_aceitar', text: 'Aceitar'),
    LocalizableModel(key: 'lb_recusar', text: 'Recusar'),
    LocalizableModel(key: 'lb_finalizar', text: 'Finalizar'),

    LocalizableModel(key: 'lb_titulo', text: 'Título'),
    LocalizableModel(key: 'lb_descricao', text: 'Descrição'),
    LocalizableModel(key: 'lb_descricao_opcional', text: 'DESCRIÇÃO (OPCIONAL)'),
    LocalizableModel(key: 'lb_observacoes_opcional', text: 'OBSERVAÇÕES (OPCIONAL)'),
    LocalizableModel(key: 'lb_observacoes', text: 'Observações'),    
    LocalizableModel(key: 'lb_inicio', text: 'Início'),
    LocalizableModel(key: 'lb_termino', text: 'Término'),
    LocalizableModel(key: 'lb_autorizado_por', text: 'Autorizado por'),

    LocalizableModel(key: 'lb_infos_apto', text: 'INFORMAÇÕES DO APARTAMENTO'),
    LocalizableModel(key: 'lb_bloco', text: 'Bloco'),

    LocalizableModel(key: 'lb_li_concordo', text: 'Li e concordo com as normas'),
    LocalizableModel(key: 'lb_complementos', text: 'Complementos'),

    LocalizableModel(key: 'lb_logout', text: 'Sair'),

    //Button
    LocalizableModel(key: 'btn_save', text: 'SALVAR'),
    LocalizableModel(key: 'btn_delete', text: 'Excluir'),
    LocalizableModel(key: 'btn_enviar', text: 'ENVIAR'),
    LocalizableModel(key: 'btn_proximo', text: 'PRÓXIMO'),
    LocalizableModel(key: 'btn_anterior', text: 'ANTERIOR'),

    //UPLOAD
    LocalizableModel(key: 'upload_max_number', text: 'Número máximo de documentos atingidos'),

    // ALERT
    LocalizableModel(key: 'alert', text: 'Alerta!'),
    LocalizableModel(key: 'alert_alert', text: 'Aviso'),
    LocalizableModel(key: 'alert_success', text: 'Sucesso!'),
    LocalizableModel(key: 'alert_error', text: 'Erro!'),
    LocalizableModel(key: 'alert_ops', text: 'Ops!'),
    LocalizableModel(key: 'alert_invalid_value', text: 'Valor informado inválido!'),
    LocalizableModel(key: 'alert_sim', text: 'Sim'),
    LocalizableModel(key: 'alert_nao', text: 'Não'),
    LocalizableModel(key: 'alert_em_breve', text: 'Em Breve!'),
    LocalizableModel(key: 'alert_em_breve_description', text: 'Estamos trabalhando para disponibilizar este serviço o quanto antes.'),    
    LocalizableModel(key: 'alert_delete_description', text: 'Você tem certeza de que deseja excluir este item permanentemente?'),
    LocalizableModel(key: 'alert_cancel_description', text: 'Você tem certeza de que deseja efetuar o cancelamento deste item?'),
    LocalizableModel(key: 'alert_photo_choice', text: 'Você deseja tirar uma foto agora ou selecionar uma foto da galeria?'),
    LocalizableModel(key: 'alert_doc_choice', text: 'Você deseja anexar um documento ou uma imagem?'),
    LocalizableModel(key: 'alert_photo_camera', text: 'Câmera'),
    LocalizableModel(key: 'alert_photo_galeria', text: 'Galeria'),
    LocalizableModel(key: 'alert_photo_image', text: 'Imagem'),
    LocalizableModel(key: 'alert_document', text: 'Documento'),
    LocalizableModel(key: 'alert_generic_error', text: 'Houve um erro, tente novamente!'),
    LocalizableModel(key: 'alert_list_empty_generic', text: 'Nenhum registro encontrado!'),
    LocalizableModel(key: 'alert_upload_image', text: 'Insira a imagem.'),
    LocalizableModel(key: 'alert_dados_alterados', text: 'Dados alterados com sucesso!'),
    LocalizableModel(key: 'alert_nenhum_bloco', text: 'Nenhum bloco localizado!\nPrimeiro cadastre as unidades no menu "Apartamentos".'),
    LocalizableModel(key: 'alert_nenhum_apto', text: 'Nenhum apartamento localizado!\n\nPrimeiro cadastre as unidades no menu "Apartamentos" na tela inicial.'),

    // ACESSO
    LocalizableModel(key: 'sou_sindico', text: 'SOU SÍNDICO'),
    LocalizableModel(key: 'sou_morador', text: 'SOU MORADOR'),
    LocalizableModel(key: 'sou_funcionario', text: 'SOU FUNCIONÁRIO'),
    LocalizableModel(key: 'view_hello_text', text: 'vamos cadastrar o seu primeiro condomínio?'),
    LocalizableModel(key: 'vamos_cadastrar', text: 'vamos cadastrar'),
    LocalizableModel(key: 'possuo_cadastro', text: 'já possuo cadastro'),
    
    // LOGIN
    LocalizableModel(key: 'login_btn_entrar', text: 'ENTRAR'),
    LocalizableModel(key: 'login_btn_esqueci_senha', text: 'Esqueceu a senha?'),
    LocalizableModel(key: 'login_error', text: 'Login ou Senha incorretos. Tente Novamente'),

    // ESQUECI A SENHA
    LocalizableModel(key: 'esqueci_senha_nav', text: 'Esqueci a senha'),
    LocalizableModel(key: 'esqueci_senha_title', text: 'Esqueceu a senha?'),
    LocalizableModel(key: 'esqueci_senha_description', text: 'Não se preocupe, preencha o seu e-mail abaixo que enviaremos um link de recuperação.'),
    LocalizableModel(key: 'esqueci_senha_send_description', text: 'O link de recuperação foi encaminhado para o seu e-mail.'),    

    // CADASTRO SÍNDICO
    LocalizableModel(key: 'signup_nav_sindico', text: 'Cadastro Síndico'),
    LocalizableModel(key: 'sindico_nav_edit', text: 'Editar Dados'),
    LocalizableModel(key: 'signup_success', text: 'Cadastro efetuado com sucesso!'),
    LocalizableModel(key: 'signup_erro_dt_nascimento', text: 'Data de Nascimento inválida!'),
    LocalizableModel(key: 'signup_infos_contato', text: 'INFORMAÇÕES DE CONTATO'),

    // CADASTRO CONDOMINIO
    LocalizableModel(key: 'signup_cond_nav', text: 'Cadastro Condomínio'),
    LocalizableModel(key: 'condominio_nav_edit', text: 'Editar Condomínio'),
    LocalizableModel(key: 'condominio_nav_edit_address', text: 'Editar Condomínio'),
    LocalizableModel(key: 'signup_cond_error_nome', text: 'Informe o nome do condomínio.'),
    LocalizableModel(key: 'signup_cond_error_doc', text: 'Informe o documento de identificação do condomínio.'),
    LocalizableModel(key: 'signup_cond_error_subsindico', text: 'Informe o nome do subsíndico.'),
    LocalizableModel(key: 'signup_cond_error_dt_inicio_mandato', text: 'Informe a data de inicio do mandato'),
    LocalizableModel(key: 'signup_cond_error_dt_fim_mandato', text: 'Informe a data de término do mandato.'),
    LocalizableModel(key: 'signup_cond_error_dt_anterior', text: 'Data de término anterior a data de início.'), 
    LocalizableModel(key: 'signup_cond_error_cep', text: 'Informe o CEP.'),  
    LocalizableModel(key: 'signup_cond_error_pais', text: 'Informe o País.'),  
    LocalizableModel(key: 'signup_cond_error_estado', text: 'Informe o Estado.'),  
    LocalizableModel(key: 'signup_cond_error_cidade', text: 'Informe a Cidade.'),  
    LocalizableModel(key: 'signup_cond_error_bairro', text: 'Informe o Bairro.'),  
    LocalizableModel(key: 'signup_cond_error_rua', text: 'Informe o Rua.'),  
    LocalizableModel(key: 'signup_cond_error_numero', text: 'Informe o Número.'),  

    LocalizableModel(key: 'signup_cond_nome', text: 'Nome do condomínio'),
    LocalizableModel(key: 'signup_cond_subsindico_nome', text: 'Nome do subsíndico'),
    LocalizableModel(key: 'signup_cond_ini_mandato', text: 'Data de início do mandato'),
    LocalizableModel(key: 'signup_cond_fim_mandato', text: 'Data de término do mandato'),
    LocalizableModel(key: 'signup_cond_cep', text: 'Código Postal'),
    LocalizableModel(key: 'signup_cond_pais', text: 'País'),  
    LocalizableModel(key: 'signup_cond_uf', text: 'UF'),  
    LocalizableModel(key: 'signup_cond_cidade', text: 'Cidade'),  
    LocalizableModel(key: 'signup_cond_bairro', text: 'Bairro'),  
    LocalizableModel(key: 'signup_cond_rua', text: 'Rua'),  
    LocalizableModel(key: 'signup_cond_numero', text: 'Número'),  
    LocalizableModel(key: 'signup_cond_complemento', text: 'Complemento'),  

    LocalizableModel(key: 'signup_cond_valor_total', text: 'Valor Total:'),  
    LocalizableModel(key: 'signup_cond_valor_mensal', text: 'R\$ 35,99 / mês'), 
    LocalizableModel(key: 'signup_cond_dias_gratuitos', text: 'Aproveite os seus 45 dias Gratuitos!'), 
    LocalizableModel(key: 'signup_cond_cancele_label', text: 'Cancele a hora que quiser!'), 

    LocalizableModel(key: 'signup_cond_sucesso', text: 'Condomínio Cadastrado com SUCESSO'), 

    LocalizableModel(key: 'cond_confirm_delete', text: 'Você tem certeza de que deseja excluir esse condomínio permanentemente?'), 
    LocalizableModel(key: 'signup_confirm_delete', text: 'Você tem certeza de que deseja excluir a sua conta permanentemente?'), 

    LocalizableModel(key: 'condominio_edit_dados', text: 'Editar dados do condomínio'),
    LocalizableModel(key: 'condominio_edit_endereco', text: 'Atualizar endereço'),
    
  
    //MANUTENCAO PROGRAMADA
    LocalizableModel(key: 'manut_edit_nav', text: 'Editar Compromisso da Agenda'), 
    LocalizableModel(key: 'manut_signup_nav', text: 'Novo Compromisso na Agenda'), 
    LocalizableModel(key: 'manut_about', text: 'SOBRE A MANUTENÇÃO'), 
    LocalizableModel(key: 'manut_nav', text: 'Solicitações de Manutenção'), 
    LocalizableModel(key: 'manut_edit', text: 'Editar Solicitação'), 
    LocalizableModel(key: 'manut_new', text: 'Nova Solicitação'), 
    


    //AREA SOCIAL
    LocalizableModel(key: 'area_social_precisa_agendamento', text: 'Necessita de Agendamento'), 
    LocalizableModel(key: 'area_social_precisa_autorizacao', text: 'Necessita de Autorização'), 
    LocalizableModel(key: 'area_social_precisa_pagamento', text: 'Necessita de Pagamento'), 
    LocalizableModel(key: 'area_social_agendamentos', text: 'Agendamentos'), 
    LocalizableModel(key: 'area_social_meus_agendamentos', text: 'Meus Agendamentos'), 
    LocalizableModel(key: 'area_social_nenhum_agendamento', text: 'Você não possui agendamentos'), 
    LocalizableModel(key: 'area_social_nav_new', text: 'Nova Área Social'), 
    LocalizableModel(key: 'area_social_dados_iniciais', text: 'DADOS INICIAIS'), 
    LocalizableModel(key: 'area_social_capacidade_maxima', text: 'Capacidade máxima'), 
    LocalizableModel(key: 'area_social_capacidade_vazio', text: 'Deixe vazio caso não tenha capacidade máxima'), 
    LocalizableModel(key: 'area_social_obrigatoriedades', text: 'OBRIGATORIEDADES'), 
    LocalizableModel(key: 'area_social_novo_horario', text: 'Novo Horário'), 
    LocalizableModel(key: 'area_social_erro_normas', text: 'Aceite as normas antes de continuar.'), 
    LocalizableModel(key: 'area_social_nav_edit_reserva', text: 'Editar Reserva'), 
    LocalizableModel(key: 'area_social_nav_reservar', text: 'Reservar'), 
    LocalizableModel(key: 'area_social_data_reserva', text: 'Data da reserva:'), 
    LocalizableModel(key: 'area_social_hora_reserva', text: 'Hora da reserva:'), 
    LocalizableModel(key: 'area_social_reservado', text: 'Reservado:'), 

    //ASSEMBLEIA
    LocalizableModel(key: 'assembleia_infos', text: 'INFORMAÇÕES DA ASSEMBLÉIA'), 
    LocalizableModel(key: 'assembleia_local', text: 'Local'), 
    LocalizableModel(key: 'assembleia_nav_edit', text: 'Editar Assembléia'), 
    LocalizableModel(key: 'assembleia_nav_new', text: 'Nova Assembléia'), 
    LocalizableModel(key: 'assembleia_data_local', text: 'SOBRE A DATA E O LOCAL'), 
    LocalizableModel(key: 'assembleia_link_online', text: 'Link (caso a assembléia seja online)'), 
    LocalizableModel(key: 'assembleia_arquivos', text: 'Insira os arquivos aqui\n(Apenas formato .PDF)'), 

    LocalizableModel(key: 'assembleia_alert_ata', text: 'Insira a ATA para finalizar essa Assembléia'), 
    LocalizableModel(key: 'assembleia_encerrada', text: 'A assembléia foi encerrada!\nA ATA se encontra disponível para consulta no menu "Docs" do seu condomínio.'), 
    LocalizableModel(key: 'assembleia_finalize_upload', text: 'Finalize a assembéia.\nFaça o upload da Ata'), 
    LocalizableModel(key: 'assembleia_upload_ata', text: 'Insira aqui a Ata da Assembléia'), 
    

    //VOTACAO
    LocalizableModel(key: 'votacao_signup_informe_opcoes', text: 'Informe as opções de votos.'), 
    LocalizableModel(key: 'votacao_signup_nav', text: 'Criar Votação'), 
    LocalizableModel(key: 'votacao_signup_infos', text: 'INFORMAÇÕES DA VOTAÇÃO'), 
    LocalizableModel(key: 'votacao_signup_dt_encerramento', text: 'Data de encerramento'), 
    LocalizableModel(key: 'votacao_opcoes', text: 'OPÇÕES'), 
    LocalizableModel(key: 'votacao_opcao', text: 'Opção'), 
    LocalizableModel(key: 'votacao_confirm_delete', text: 'Tem certeza de que deseja finalizar a votação antes da data de término planejada?'), 
    LocalizableModel(key: 'votacao_enquete', text: 'Enquete'), 
    LocalizableModel(key: 'votacao_infos', text: 'INFORMAÇÕES DA ENQUETE'), 
    LocalizableModel(key: 'votacao_agendado', text: 'Agendado'), 
    LocalizableModel(key: 'votacao_andamento', text: 'Em andamento'), 
    LocalizableModel(key: 'votacao_finalizado', text: 'Finalizado'), 
    LocalizableModel(key: 'votacao_finalizar', text: 'Finalizar votação?'), 
    LocalizableModel(key: 'votacao_fora_periodo', text: 'Votação fora do período permitido.'), 

    //COMUNICADO
    LocalizableModel(key: 'comunicado_nav_edit', text: 'Editar Comunicado'), 
    LocalizableModel(key: 'comunicado_nav_new', text: 'Novo Comunicado'), 
    LocalizableModel(key: 'comunicados_infos', text: 'INFORMAÇÕES DO COMUNICADO'), 

    //CONFIGURACAO
    LocalizableModel(key: 'config_delete_account_sucesso', text: 'A exclusão da sua conta foi solicitada!\nA equipe responsável lhe comunicará do andamento!'), 
    LocalizableModel(key: 'config_nav', text: 'Configurações'), 
    LocalizableModel(key: 'config_termos_uso', text: 'Termos de Uso'), 
    LocalizableModel(key: 'config_politica_privacidade', text: 'Política de Privacidade'), 
    LocalizableModel(key: 'config_fale_conosco', text: 'Fale conosco'), 
    LocalizableModel(key: 'config_fale_conosco_descricao', text: 'Entre em contacto através do nosso e-mail apontando as suas dúvidas e/ou requerimentos. \n\nE não se esqueça de se identificar. \n\ncontacto@click-app.co\n'), 
    LocalizableModel(key: 'config_alt_senha', text: 'Alterar senha'), 
    LocalizableModel(key: 'config_delete_cond', text: 'Excluir condomínio'), 
    LocalizableModel(key: 'config_delete_account', text: 'Excluir minha conta'), 
    LocalizableModel(key: 'config_nova_senha', text: 'Nova senha'), 
    LocalizableModel(key: 'config_confirm_nova_senha', text: 'Confirme a nova senha'), 
    LocalizableModel(key: 'config_alt_senha_sucesso', text: 'Senha alterada com sucesso!'), 

    //ASSINATURA
    LocalizableModel(key: 'assinatura', text: 'Assinatura'), 
    LocalizableModel(key: 'assinatura_morador', text: 'Assinatura Morador'), 
    LocalizableModel(key: 'assinatura_condominio', text: 'Assinatura Condomínio'), 
    LocalizableModel(key: 'assinatura_erro', text: 'Houve um erro na sua compra, tente novamente.'), 
    LocalizableModel(key: 'assinatura_renovada', text: 'Assinatura renovada com sucesso!'), 
    LocalizableModel(key: 'assinatura_produto_nao_localizado', text: 'Produto não localizado!'), 
    LocalizableModel(key: 'assinatura_erro_loja', text: 'O app não conseguiu se comunicar com a loja, tente novamente mais tarde!'), 
    LocalizableModel(key: 'assinatura_tipo_renovacao', text: 'Tipo de renovação: '),
    LocalizableModel(key: 'assinatura_mensal', text: 'Mensal'),
    LocalizableModel(key: 'assinatura_validade', text: 'Validade: '),
    LocalizableModel(key: 'assinatura_dias_restantes', text: 'Dias restantes: '),
    LocalizableModel(key: 'assinatura_venceu', text: 'Sua assinatura venceu!'),
    LocalizableModel(key: 'assinatura_renove_agora', text: 'Renove agora por mais 30 dias e continue por dentro de tudo o que acontece no seu condomínio!'),    
    LocalizableModel(key: 'assinatura_cond_renove_agora', text: 'Renove agora por mais 30 dias e garanta mais tranquilidade na gestão de seu condomínio!'),    
    LocalizableModel(key: 'assinatura_cond_contato_sindico', text: 'Entre em contato com o síndico e informe sobre a renovação do plano do App Click.'), 
    LocalizableModel(key: 'assinatura_renove_agora_obs', text: 'No caso de ainda ter dias restantes, a renovação começará a contar a partir da data de expiração do plano atual.'),    
    LocalizableModel(key: 'assinatura_btn_mensal_morador', text: 'Renovar agora'),    
    LocalizableModel(key: 'assinatura_btn_mensal_cond', text: 'Renovar agora'),    
    LocalizableModel(key: 'assinatura_renovar_depois', text: 'Renovar depois'),  
    LocalizableModel(key: 'assinatura_renovar_7_dias', text: 'Você poderá renovar seu plano faltando 7 dias para a data de expiração!' ),  
     
    

    //DOCS
    LocalizableModel(key: 'docs_nav_atas', text: 'Atas'), 
    LocalizableModel(key: 'docs_nav', text: 'Documentos'), 
    LocalizableModel(key: 'docs_nav_new', text: 'Novo Documento'), 
    LocalizableModel(key: 'docs_title', text: 'Título do documento'), 
    LocalizableModel(key: 'docs_upload', text: 'Insira seu documento aqui'), 

    //FINANCEIRO
    LocalizableModel(key: 'financeiro_inadimplente', text: 'Inadimplente'), 
    LocalizableModel(key: 'financeiro_inadimplentes', text: 'Inadimplentes'), 
    LocalizableModel(key: 'financeiro_meses_aberto', text: 'MESES EM ABERTO'), 
    LocalizableModel(key: 'financeiro_nav_relatorio', text: 'Resumo'), 
    LocalizableModel(key: 'financeiro_nav_resultado', text: 'RESULTADO'),
    LocalizableModel(key: 'financeiro_total_receitas', text: 'Total das Receitas:'), 
    LocalizableModel(key: 'financeiro_total_despesas', text: 'Total das Despesas:'), 
    LocalizableModel(key: 'financeiro_resultado_periodo', text: 'Resultado do período:'), 
    LocalizableModel(key: 'financeiro_nav_arrecadacoes', text: 'Arrecadações'),
    LocalizableModel(key: 'financeiro_sem_lancamentos', text: 'Não há lançamentos no período'),
    LocalizableModel(key: 'financeiro_nenhum_inadimplente', text: 'Nenhum inadimplente encontrado'),
    LocalizableModel(key: 'financeiro_despesa', text: 'Despesa'), 
    LocalizableModel(key: 'financeiro_despesas', text: 'Despesas'), 
    LocalizableModel(key: 'financeiro_arrecadacoes', text: 'Arrecadações'),  
    LocalizableModel(key: 'financeiro_receita_outras', text: 'Receita - Outras'),  
    LocalizableModel(key: 'financeiro_receita', text: 'Receita'), 
    LocalizableModel(key: 'financeiro_recebedor', text: 'RECEBEDOR'), 
    LocalizableModel(key: 'financeiro_fornecedor', text: 'Fornecedor'), 
    LocalizableModel(key: 'financeiro_categoria', text: 'Categoria'), 
    LocalizableModel(key: 'financeiro_dt_pag', text: 'Data do Pagamento'), 
    LocalizableModel(key: 'financeiro_valores', text: 'VALORES'), 
    LocalizableModel(key: 'financeiro_valor', text: 'Valor'), 
    LocalizableModel(key: 'financeiro_forma_pagamento', text: 'Forma do pagamento'), 
    LocalizableModel(key: 'financeiro_parcelas', text: 'Nº de parcelas'), 
    LocalizableModel(key: 'financeiro_conta_debito', text: 'Conta de débito'),
    LocalizableModel(key: 'financeiro_desc_comprovante', text: 'DESCRIÇÃO E COMPROVANTE (OPCIONAIS)'), 
    LocalizableModel(key: 'financeiro_anexo_comprovante', text: 'Clique aqui e anexe uma foto do comprovante ou da NF'), 
    LocalizableModel(key: 'financeiro_arrecadacao', text: 'Arrecadação'), 
    LocalizableModel(key: 'financeiro_lancamento', text: 'Lançamento'), 
    LocalizableModel(key: 'financeiro_mes_referencia', text: 'Mês de referência'), 
    LocalizableModel(key: 'financeiro_data_vencimento', text: 'Data de vencimento'), 
    LocalizableModel(key: 'financeiro_pagador', text: 'Pagador'), 
    LocalizableModel(key: 'financeiro_tipo', text: 'Tipo'), 
    LocalizableModel(key: 'financeiro_forn_cliente', text: 'Fornecedor / Cliente'), 
    LocalizableModel(key: 'financeiro_data_recebimento', text: 'Data de recebimento'),
    LocalizableModel(key: 'financeiro_conta_bancaria', text: 'Conta Bancária'),
    LocalizableModel(key: 'financeiro_nav_edit', text: 'Editar Lançamento'),
    LocalizableModel(key: 'financeiro_nav_new', text: 'Novo Lançamento'),
    LocalizableModel(key: 'financeiro_saldo_dia', text: 'Saldo no dia'),

    LocalizableModel(key: 'financeiro_categ_consumo', text: 'Consumo'),
    LocalizableModel(key: 'financeiro_categ_manutencao', text: 'Manutenção'),
    LocalizableModel(key: 'financeiro_categ_pessoal', text: 'Pessoal'),
    LocalizableModel(key: 'financeiro_categ_impostos', text: 'Impostos'),
    LocalizableModel(key: 'financeiro_categ_adms', text: 'Administrativas'),
    LocalizableModel(key: 'financeiro_categ_outras', text: 'Outras'),

    LocalizableModel(key: 'financeiro_conta_corrente', text: 'Conta Corrente'),
    LocalizableModel(key: 'financeiro_conta_poupanca', text: 'Poupança'),
    LocalizableModel(key: 'financeiro_conta_outra', text: 'Outra'),

    LocalizableModel(key: 'financeiro_dinheiro', text: 'Dinheiro'),
    LocalizableModel(key: 'financeiro_pix', text: 'Pix'),
    LocalizableModel(key: 'financeiro_boleto', text: 'Boleto'),
    LocalizableModel(key: 'financeiro_cartao_credito', text: 'Cartão de Crédito'),
    LocalizableModel(key: 'financeiro_cartao_debito', text: 'Cartão de Débito'),
    LocalizableModel(key: 'financeiro_outra', text: 'Outra'),


    //FUNCIONÁRIO
    LocalizableModel(key: 'funcionario_nav_edit', text: 'Editar Funcionário'), 
    LocalizableModel(key: 'funcionario_nav_new', text: 'Cadastrar Funcionário'), 
    LocalizableModel(key: 'funcionario_infos_pessoais', text: 'INFORMAÇÕES PESSOAIS'), 
    LocalizableModel(key: 'funcionario_infos_funcao', text: 'INFORMAÇÕES RELATIVAS A FUNÇÃO'), 
    LocalizableModel(key: 'funcionario_funcao', text: 'Função'), 
    LocalizableModel(key: 'funcionario_horario_trabalho', text: 'Horário de trabalho'), 
    LocalizableModel(key: 'funcionario_permissoes', text: 'PERMISSÕES DENTRO DO APLICATIVO'),     
    LocalizableModel(key: 'funcionario_permissoes_sobre', text: 'Ao habilitar uma permissão, você estará dando a autonomia de síndico para este funcionário ao menu escolhido!'),
    LocalizableModel(key: 'funcionario_infos_extra', text: 'INFORMAÇÕES EXTRAS (OPCIONAL)'),
    LocalizableModel(key: 'funcionario_infos_extra_1', text: 'Informações Extras 1'),
    LocalizableModel(key: 'funcionario_infos_extra_2', text: 'Informações Extras 2'),
    LocalizableModel(key: 'funcionario_infos_extra_3', text: 'Informações Extras 3'),
    LocalizableModel(key: 'funcionario_infos_extra_4', text: 'Informações Extras 4'),
    LocalizableModel(key: 'funcionario_infos_acesso', text: 'INFORMAÇÕES DE ACESSO'),
    LocalizableModel(key: 'funcionario_senha', text: 'Senha de Acesso ao Click'),

    //MORADORES
    LocalizableModel(key: 'moradores_empty', text: 'Não há moradores cadastrados até o momento'), 

    //APARTAMENTO
    LocalizableModel(key: 'apto_desc', text: 'Para realizar o cadastro de um novo apartamento, insira os dados abaixo:'), 
    LocalizableModel(key: 'apto_fracao', text: 'Fração ideal'), 
    LocalizableModel(key: 'apto_proprietarios', text: 'Proprietários: '), 
    LocalizableModel(key: 'apto_inquilinos', text: 'Inquilinos: '), 
    LocalizableModel(key: 'apto_usuario_criado_msg', text: 'Usuário criado!\nInforme que a senha padrão será o número do documento e que ao entrar na conta a senha poderá ser alterada.'), 
    
    //MUDANCA
    LocalizableModel(key: 'mudanca_nav', text: 'Agendamentos Mudança'),  
    LocalizableModel(key: 'mudanca_nav_edit', text: 'Editar Mudança'),
    LocalizableModel(key: 'mudanca_nav_new', text: 'Solicitar Mudança'),
    LocalizableModel(key: 'mudanca_pendente_aprovacao', text: 'Este item não está mais pendente aprovação.\nVocê não pode mais editá-lo.'), 
    LocalizableModel(key: 'mudanca_selecione_apto', text: 'ASelecione o apartamento desejado'),   
    LocalizableModel(key: 'mudanca_infos_mudanca', text: 'INFORMAÇÕES SOBRE A MUDANÇA'),   
    LocalizableModel(key: 'mudanca_motivo_recusa', text: 'Motivo da Recusa'),   

    //OCORRÊNCIA
    LocalizableModel(key: 'ocorrencia_sobre', text: 'SOBRE A OCORRÊNCIA'),  
    LocalizableModel(key: 'ocorrencia_respondido', text: 'Respondido em'),  
    LocalizableModel(key: 'ocorrencia_resposta', text: 'Escreva aqui a resposta para o morador'),  
    LocalizableModel(key: 'ocorrencia_status', text: 'Selecione o status:'), 
    LocalizableModel(key: 'ocorrencia_abertura_nav', text: 'Abertura de Ocorrências'), 
    LocalizableModel(key: 'ocorrencia_erro_tipo', text: 'Selecione o tipo da ocorrência!'),     
    LocalizableModel(key: 'ocorrencia_nav_edit', text: 'Selecione o tipo da ocorrência!'),   
    LocalizableModel(key: 'ocorrencia_tipo', text: 'Tipo da ocorrência'),   

    //PRESTADORES
    LocalizableModel(key: 'prestador_eletricista', text: '⚡ Eletricista'),  
    LocalizableModel(key: 'prestador_hidraulica', text: '🚰 Hidráulica / Encanador'),  
    LocalizableModel(key: 'prestador_pintor', text: '🎨 Pintor'),  
    LocalizableModel(key: 'prestador_pedreiro', text: '🏚 Pedreiro'),  
    LocalizableModel(key: 'prestador_limpeza', text: '🧹 Limpeza'),  
    LocalizableModel(key: 'prestador_dedetizacao', text: '🐜 Dedetização'),  
    LocalizableModel(key: 'prestador_nav_edit', text: 'Editar Prestador de Serviços'),
    LocalizableModel(key: 'prestador_nav_new', text: 'Cadastrar Prestador de Serviços'),
    LocalizableModel(key: 'prestador_infos', text: 'INFORMAÇÕES DO PRESTADOR'),
    LocalizableModel(key: 'prestador_funcoes', text: 'FUNÇÕES'),
    LocalizableModel(key: 'prestador_selecione_categoria', text:  'Selecione a(s) categoria(s):'),
    LocalizableModel(key: 'prestador_categoria_desc', text: 'Ou informe outra(s) categoria(s): (separadas por vírgula)'),

    //VISITANTES
    LocalizableModel(key: 'visitantes_list', text: 'Lista de Visitantes'),  
    LocalizableModel(key: 'visitantes_nav_new', text: 'Cadastrar novo visitante'),
    LocalizableModel(key: 'visitantes_nav_edit', text: 'Editar Visitante'),
    LocalizableModel(key: 'visitantes_infos', text: 'INFORMAÇÕES REFERENTE A VISITA'),
    LocalizableModel(key: 'visitantes_data_hora_inicio', text: 'Data e hora de início da liberação'),
    LocalizableModel(key: 'visitantes_data_hora_termino', text: 'Data e hora de término da liberação'),
    LocalizableModel(key: 'visitante', text: 'Visitante'),
    LocalizableModel(key: 'prestador', text: 'Prestador'),
    LocalizableModel(key: 'visitante_prestador_servico', text: 'Prestador de Serviços'),
    LocalizableModel(key: 'visitante_erro_bloco', text: 'Primeiro selecione o bloco!'),

    //OUTROS
    LocalizableModel(key: 'pessoas', text: 'Pessoas'),
    LocalizableModel(key: 'capacidade_indeterminada', text: 'Capacidade indeterminada'),
    LocalizableModel(key: 'pagos', text: 'Pagos'),
    LocalizableModel(key: 'escolha_opcao_desejada', text: 'Escolha a opção desejada'),
    LocalizableModel(key: 'ciente', text: 'Ciente'),
    LocalizableModel(key: 'solucionado', text: 'Solucionado'),
    LocalizableModel(key: 'urgente', text: 'Urgente'),
    LocalizableModel(key: 'manutencao', text: 'Manutenção'),
    LocalizableModel(key: 'outros', text: 'Outros'),
    LocalizableModel(key: 'primeiro_documento', text: 'Primeiro Documento'),
    LocalizableModel(key: 'link_erro', text: 'Não foi possível abrir o link'),
    LocalizableModel(key: 'invalid_data', text: 'Data informada inválida!'),
    LocalizableModel(key: 'invalid_hora', text: 'Hora informada inválida!'),
    LocalizableModel(key: 'senhas_nao_conferem', text: 'As senhas informadas não conferem.'),
    LocalizableModel(key: 'senha_minimo_caracteres', text: 'A senha deve conter no mínimo 6 caracteres.'),
    LocalizableModel(key: 'libere_funcoes', text: 'Libere as Funções Desejadas'),
    LocalizableModel(key: 'editar_manutencao', text: 'Editar Manutenção'),
    LocalizableModel(key: 'nova_manutencao', text: 'Nova Manutenção'),
    LocalizableModel(key: 'gerar_alerta', text: 'Gerar alerta para os moradores'),

    LocalizableModel(key: 'moeda', text: 'Moeda'),
    LocalizableModel(key: 'moeda_real', text: 'R\$ (Real Brasileiro)'),
    LocalizableModel(key: 'moeda_dolar_americano', text: 'US\$ (Dolár Americano)'),
    LocalizableModel(key: 'moeda_euro', text: '€ (Euro)'),
    LocalizableModel(key: 'moeda_libra', text: '£ (Libra)'),
    LocalizableModel(key: 'moeda_peso_mexicano', text: 'Mex\$ (Peso Mexicano)'),
    LocalizableModel(key: 'moeda_generico', text: '\$'),

    LocalizableModel(key: 'assinatura_semestral', text: 'Semestral'),
    LocalizableModel(key: 'assinatura_anual', text: 'Anual'),

    LocalizableModel(key: 'meus_condominios', text: 'Meus Condomínios'),

  ];

}

