import 'package:click/utils/localizable/localizable.dart';

class Localizable_EnUs {

  final List<LocalizableModel> strings = [
    // Idioma
          LocalizableModel(key: 'language_idioma', text: 'Language'),
          LocalizableModel(key: 'language_pt_br', text: 'Brazilian Portuguese'),
          LocalizableModel(key: 'language_pt_pt', text: 'Portuguese Portugal'),
          LocalizableModel(key: 'language_en', text: 'English'),
          LocalizableModel(key: 'language_es', text: 'Spanish'),
          LocalizableModel(key: 'language_al', text: 'German'),
      
          // Data
          LocalizableModel(key: 'data_informar', text: 'Enter the desired date.'),
          LocalizableModel(key: 'data_selecionar_horario', text: 'Select the desired time.'),
          LocalizableModel(key: 'data_das', text: 'Dàs'),    
          LocalizableModel(key: 'data_as', text: 'Às'),    
          LocalizableModel(key: 'data_e_hora', text: 'Date and Time'),
          LocalizableModel(key: 'dia_e_hora', text: 'Day and Time'),
          LocalizableModel(key: 'dia', text: 'Day'),
          LocalizableModel(key: 'days', text: 'days'),
          LocalizableModel(key: 'data', text: 'Date'),
          LocalizableModel(key: 'datas', text: 'Dates'),
          LocalizableModel(key: 'hora', text: 'Time'),
          LocalizableModel(key: 'data_inicio', text: 'Start Date'),
          LocalizableModel(key: 'hora_inicio', text: 'Start Time'),
          LocalizableModel(key: 'data_termino', text: 'End Date'),
          LocalizableModel(key: 'hora_termino', text: 'End Time'),
          LocalizableModel(key: 'data_hora_criacao', text: 'CREATION DATE AND TIME'),
          LocalizableModel(key: 'data_hora_inicio', text: 'Start Date and Time'),
          LocalizableModel(key: 'segunda', text: 'Monday'),
          LocalizableModel(key: 'terca', text: 'Tuesday'),
          LocalizableModel(key: 'quarta', text: 'Wednesday'),
          LocalizableModel(key: 'quinta', text: 'Thursday'),
          LocalizableModel(key: 'sexta', text: 'Friday'),
          LocalizableModel(key: 'sabado', text: 'Saturday'),
          LocalizableModel(key: 'domingo', text: 'Sunday'),
      
          // Modal Select Month
          LocalizableModel(key: 'modal_select_month_btn_ok', text: 'OK'),
          LocalizableModel(key: 'modal_select_month_btn_cancel', text: 'cancel'),
      
          //TextField
          LocalizableModel(key: 'textfield_long_placeholder', text: 'Write here...'),
          LocalizableModel(key: 'textfield_short_placeholder', text: 'Write your message...'),
      
          //Label
          LocalizableModel(key: 'label_to', text: 'To:'),
          LocalizableModel(key: 'label_of', text: 'from'),
          LocalizableModel(key: 'label_until', text: 'to'),
          LocalizableModel(key: 'ola', text: 'Hello'),
          LocalizableModel(key: 'sindico', text: 'Construction Manager'),
          LocalizableModel(key: 'morador', text: 'Resident'),
          LocalizableModel(key: 'funcionario', text: 'Employee'),
          LocalizableModel(key: 'email', text: 'Email'),
          LocalizableModel(key: 'senha', text: 'Password'),
          LocalizableModel(key: 'vesaoApp', text: 'Version:'),
          LocalizableModel(key: 'nome', text: 'Name'),
          LocalizableModel(key: 'user_nome_completo', text: 'Full Name'),
          LocalizableModel(key: 'user_documento', text: 'Identification Document'),
          LocalizableModel(key: 'data_nascimento', text: 'Date of Birth'),
          LocalizableModel(key: 'email', text: 'Email'),
          LocalizableModel(key: 'telefone', text: 'Phone'),
          LocalizableModel(key: 'senha', text: 'Password'),
          LocalizableModel(key: 'editar_infos', text: 'Edit Information'),
          LocalizableModel(key: 'label_exclusao', text: 'Delete!'),
      
          LocalizableModel(key: 'lb_areas_sociais', text: 'Social Areas'),
          LocalizableModel(key: 'lb_area_social', text: 'Social Area'),
          LocalizableModel(key: 'lb_financeiro', text: 'Financial'),
          LocalizableModel(key: 'lb_assembleia_votacoes', text: 'Meetings and Voting'),
          LocalizableModel(key: 'lb_assembleias', text: 'Meetings'),
          LocalizableModel(key: 'lb_assembleia', text: 'Meeting'),
          LocalizableModel(key: 'lb_votacoes', text: 'Voting'),
          LocalizableModel(key: 'lb_enquetes', text: 'Polls'),
          LocalizableModel(key: 'lb_comunicados', text: 'Announcements'),
          LocalizableModel(key: 'lb_comunicado', text: 'Announcement'),
          LocalizableModel(key: 'lb_ocorrencias', text: 'Occurrences'),
          LocalizableModel(key: 'lb_ocorrencia', text: 'Occurrence'),
          LocalizableModel(key: 'lb_funcionarios', text: 'Employees'),
          LocalizableModel(key: 'lb_funcionarios_condominio', text: 'Condominium Employees'),
          LocalizableModel(key: 'lb_manut_programadas', text: 'Scheduled Maintenance'),
          LocalizableModel(key: 'lb_manut_programada', text: 'Scheduled Maintenance'),
          LocalizableModel(key: 'lb_prestadores_servico', text: 'Service Providers'),
          LocalizableModel(key: 'lb_agendar_mudanca', text: 'Schedule a Move'),
          LocalizableModel(key: 'lb_cadastrar_visitante', text: 'Register a Visitor'),
          LocalizableModel(key: 'lb_apartamentos', text: 'Apartments'),
          LocalizableModel(key: 'lb_apartamento', text: 'Apartment'),
          LocalizableModel(key: 'lb_docs', text: 'Docs'),
          LocalizableModel(key: 'lb_apto', text: 'Apartment'),
          LocalizableModel(key: 'lb_ref', text: 'Ref.'),
          LocalizableModel(key: 'lb_saldo', text: 'Balance'),
          LocalizableModel(key: 'lb_status', text: 'Status'),
          LocalizableModel(key: 'lb_categorias', text: 'Categories'),
          LocalizableModel(key: 'lb_categoria', text: 'Category'),
          LocalizableModel(key: 'lb_anexos', text: 'Attachments'),
          LocalizableModel(key: 'lb_insira_fotos', text: 'Insert your photos here'),
          LocalizableModel(key: 'lb_tipo', text: 'Type'),
          LocalizableModel(key: 'lb_resposta', text: 'Response'),
          LocalizableModel(key: 'lb_todos', text: 'All'),
          LocalizableModel(key: 'lb_pendentes', text: 'Pending'),
          LocalizableModel(key: 'lb_buscar', text: 'Search'),
          LocalizableModel(key: 'lb_aviso', text: 'Notice'),
          LocalizableModel(key: 'lb_ultima_atualizacao', text: 'Last update'),
          LocalizableModel(key: 'lb_ciente', text: 'Aware'),
          LocalizableModel(key: 'lb_pendente', text: 'Pending'),
          LocalizableModel(key: 'lb_aprovado', text: 'Approved'),
          LocalizableModel(key: 'lb_recusado', text: 'Rejected'),
          LocalizableModel(key: 'lb_solucionado', text: 'Resolved'),
          LocalizableModel(key: 'lb_nao_informado', text: 'Not provided'),
          LocalizableModel(key: 'lb_aceitar', text: 'Accept'),
          LocalizableModel(key: 'lb_recusar', text: 'Reject'),
          LocalizableModel(key: 'lb_finalizar', text: 'Finalize'),
      
          LocalizableModel(key: 'lb_titulo', text: 'Title'),
          LocalizableModel(key: 'lb_descricao', text: 'Description'),
          LocalizableModel(key: 'lb_descricao_opcional', text: 'DESCRIPTION (OPTIONAL)'),
          LocalizableModel(key: 'lb_observacoes_opcional', text: 'OBSERVATIONS (OPTIONAL)'),
          LocalizableModel(key: 'lb_observacoes', text: 'Observations'),    
          LocalizableModel(key: 'lb_inicio', text: 'Start'),
          LocalizableModel(key: 'lb_termino', text: 'End'),
          LocalizableModel(key: 'lb_autorizado_por', text: 'Authorized by'),
      
          LocalizableModel(key: 'lb_infos_apto', text: 'APARTMENT INFORMATION'),
          LocalizableModel(key: 'lb_bloco', text: 'Block'),
      
          LocalizableModel(key: 'lb_li_concordo', text: 'I have read and agree with the rules'),
          LocalizableModel(key: 'lb_complementos', text: 'Additions'),
      
          LocalizableModel(key: 'lb_logout', text: 'Exit'),
      
          //Button
          LocalizableModel(key: 'btn_save', text: 'SAVE'),
          LocalizableModel(key: 'btn_delete', text: 'Delete'),
          LocalizableModel(key: 'btn_enviar', text: 'SEND'),
          LocalizableModel(key: 'btn_proximo', text: 'NEXT'),
          LocalizableModel(key: 'btn_anterior', text: 'PREVIOUS'),
      
          //UPLOAD
          LocalizableModel(key: 'upload_max_number', text: 'Maximum number of documents reached'),
      
          // ALERT
          LocalizableModel(key: 'alert', text: 'Alert!'),
          LocalizableModel(key: 'alert_alert', text: 'Notice'),
          LocalizableModel(key: 'alert_success', text: 'Success!'),
          LocalizableModel(key: 'alert_error', text: 'Error!'),
          LocalizableModel(key: 'alert_ops', text: 'Oops!'),
          LocalizableModel(key: 'alert_invalid_value', text: 'Value entered is invalid!'),
          LocalizableModel(key: 'alert_sim', text: 'Yes'),
          LocalizableModel(key: 'alert_nao', text: 'No'),
          LocalizableModel(key: 'alert_em_breve', text: 'Coming soon!'),
          LocalizableModel(key: 'alert_em_breve_description', text: 'We are working to make this service available as soon as possible.'),    
          LocalizableModel(key: 'alert_delete_description', text: 'Are you sure you want to permanently delete this item?'),
          LocalizableModel(key: 'alert_cancel_description', text: 'Are you sure you want to cancel this item?'),
          LocalizableModel(key: 'alert_photo_choice', text: 'Do you want to take a photo now or select a photo from the gallery?'),
          LocalizableModel(key: 'alert_doc_choice', text: 'Do you want to attach a document or an image?'),
          LocalizableModel(key: 'alert_photo_camera', text: 'Camera'),
          LocalizableModel(key: 'alert_photo_galeria', text: 'Gallery'),
          LocalizableModel(key: 'alert_photo_image', text: 'Image'),
          LocalizableModel(key: 'alert_document', text: 'Document'),
          LocalizableModel(key: 'alert_generic_error', text: 'An error occurred, please try again!'),
          LocalizableModel(key: 'alert_list_empty_generic', text: 'No records found!'),
          LocalizableModel(key: 'alert_upload_image', text: 'Insert the image.'),
          LocalizableModel(key: 'alert_dados_alterados', text: 'Data changed successfully!'),
          LocalizableModel(key: 'alert_nenhum_bloco', text: 'No blocks found!\nFirst register the units in the "Apartments" menu.'),
          LocalizableModel(key: 'alert_nenhum_apto', text: 'No apartments found!\no First register the units in the “Apartments” menu on the home screen.'),
      
          // ACESSO
          LocalizableModel(key: 'sou_sindico', text: 'I AM A CONDOMINIUM MANAGER'),
          LocalizableModel(key: 'sou_morador', text: 'I AM A RESIDENT'),
          LocalizableModel(key: 'sou_funcionario', text: 'I AM AN EMPLOYEE'),
          LocalizableModel(key: 'view_hello_text', text: "let's register your first condominium?"),
          LocalizableModel(key: 'vamos_cadastrar', text: "let's register"),
          LocalizableModel(key: 'possuo_cadastro', text: 'I already have a registration'),
          
          // LOGIN
          LocalizableModel(key: 'login_btn_entrar', text: 'LOG IN'),
          LocalizableModel(key: 'login_btn_esqueci_senha', text: 'Forgot your password?'),
          LocalizableModel(key: 'login_error', text: 'Incorrect login or password. Try again'),
      
          // ESQUECI A SENHA
          LocalizableModel(key: 'esqueci_senha_nav', text: 'Forgot your password'),
          LocalizableModel(key: 'esqueci_senha_title', text: 'Forgot your password?'),
          LocalizableModel(key: 'esqueci_senha_description', text: "Don't worry, fill in your email below and we will send you a recovery link."),
          LocalizableModel(key: 'esqueci_senha_send_description', text: 'The recovery link was sent to your email.'),    
      
          // CADASTRO SÍNDICO
          LocalizableModel(key: 'signup_nav_sindico', text: 'Condominium Registration'),
          LocalizableModel(key: 'sindico_nav_edit', text: 'Edit Data'),
          LocalizableModel(key: 'signup_success', text: 'Registration completed successfully!'),
          LocalizableModel(key: 'signup_erro_dt_nascimento', text: 'Invalid Date of Birth!'),
          LocalizableModel(key: 'signup_infos_contato', text: 'CONTACT INFORMATION'),
      
          // CADASTRO CONDOMINIO
          LocalizableModel(key: 'signup_cond_nav', text: 'Condominium Registration'),
          LocalizableModel(key: 'condominio_nav_edit', text: 'Edit Condominium'),
          LocalizableModel(key: 'condominio_nav_edit_address', text: 'Edit Condominium'),
          LocalizableModel(key: 'signup_cond_error_nome', text: 'Enter the name of the condominium.'),
          LocalizableModel(key: 'signup_cond_error_doc', text: 'Enter the condominium identification document.'),
          LocalizableModel(key: 'signup_cond_error_subsindico', text: 'Enter the name of the assistant manager.'),
          LocalizableModel(key: 'signup_cond_error_dt_inicio_mandato', text: 'Enter the start date of the term'),
          LocalizableModel(key: 'signup_cond_error_dt_fim_mandato', text: 'Enter the end date of the term.'),
          LocalizableModel(key: 'signup_cond_error_dt_anterior', text: 'End date before the start date.'), 
          LocalizableModel(key: 'signup_cond_error_cep', text: 'Enter the zip code.'),  
          LocalizableModel(key: 'signup_cond_error_pais', text: 'Enter the country.'),  
          LocalizableModel(key: 'signup_cond_error_estado', text: 'Enter the state.'),  
          LocalizableModel(key: 'signup_cond_error_cidade', text: 'Enter the city.'),  
          LocalizableModel(key: 'signup_cond_error_bairro', text: 'Enter the neighborhood.'),  
          LocalizableModel(key: 'signup_cond_error_rua', text: 'Enter the street.'),  
          LocalizableModel(key: 'signup_cond_error_numero', text: 'Enter the number.'),  
      
          LocalizableModel(key: 'signup_cond_nome', text: 'Name of the condominium'),
          LocalizableModel(key: 'signup_cond_subsindico_nome', text: 'Name of the assistant manager'),
          LocalizableModel(key: 'signup_cond_ini_mandato', text: 'Start date of the term'),
          LocalizableModel(key: 'signup_cond_fim_mandato', text: 'End date of the term'),
          LocalizableModel(key: 'signup_cond_cep', text: 'Postal code'),
          LocalizableModel(key: 'signup_cond_pais', text: 'Country'),  
          LocalizableModel(key: 'signup_cond_uf', text: 'State'),  
          LocalizableModel(key: 'signup_cond_cidade', text: 'City'),  
          LocalizableModel(key: 'signup_cond_bairro', text: 'Neighborhood'),  
          LocalizableModel(key: 'signup_cond_rua', text: 'Street'),  
          LocalizableModel(key: 'signup_cond_numero', text: 'Number'),  
          LocalizableModel(key: 'signup_cond_complemento', text: 'Complement'),  
      
          LocalizableModel(key: 'signup_cond_valor_total', text: 'Total amount:'),  
          LocalizableModel(key: 'signup_cond_valor_mensal', text: 'R\$ 35,99 / mês'), 
          LocalizableModel(key: 'signup_cond_dias_gratuitos', text: 'Enjoy your 45 free days!'), 
          LocalizableModel(key: 'signup_cond_cancele_label', text: 'Cancel whenever you want!'), 
      
          LocalizableModel(key: 'signup_cond_sucesso', text: 'Condominium registered SUCCESSFULLY'), 
      
          LocalizableModel(key: 'cond_confirm_delete', text: 'Are you sure you want to delete this condominium permanently?'), 
          LocalizableModel(key: 'signup_confirm_delete', text: 'Are you sure you want to delete your account permanently?'), 
      
          LocalizableModel(key: 'condominio_edit_dados', text: 'Edit condominium data'),
          LocalizableModel(key: 'condominio_edit_endereco', text: 'Update address'),
          
        
          //MANUTENCAO PROGRAMADA
          LocalizableModel(key: 'manut_edit_nav', text: 'Edit Calendar Appointment'), 
          LocalizableModel(key: 'manut_signup_nav', text: 'New Calendar Appointment'), 
          LocalizableModel(key: 'manut_about', text: 'ABOUT THE APPOINTMENT'), 
          LocalizableModel(key: 'manut_nav', text: 'Maintenance Requests'), 
          LocalizableModel(key: 'manut_edit', text: 'Edit Request'), 
          LocalizableModel(key: 'manut_new', text: 'New Request'), 
          
      
      
          //AREA SOCIAL
          LocalizableModel(key: 'area_social_precisa_agendamento', text: 'Requires Scheduling'), 
          LocalizableModel(key: 'area_social_precisa_autorizacao', text: 'Requires Authorization'), 
          LocalizableModel(key: 'area_social_precisa_pagamento', text: 'Requires Payment'), 
          LocalizableModel(key: 'area_social_agendamentos', text: 'Scheduling'), 
          LocalizableModel(key: 'area_social_meus_agendamentos', text: 'My Scheduling'), 
          LocalizableModel(key: 'area_social_nenhum_agendamento', text: 'You have no scheduling'), 
          LocalizableModel(key: 'area_social_nav_new', text: 'New Social Area'), 
          LocalizableModel(key: 'area_social_dados_iniciais', text: 'INITIAL DATA'), 
          LocalizableModel(key: 'area_social_capacidade_maxima', text: 'Maximum capacity'), 
          LocalizableModel(key: 'area_social_capacidade_vazio', text: 'Leave blank if there is no maximum capacity'), 
          LocalizableModel(key: 'area_social_obrigatoriedades', text: 'MANDATORIE'), 
          LocalizableModel(key: 'area_social_novo_horario', text: 'New Schedule'), 
          LocalizableModel(key: 'area_social_erro_normas', text: 'Accept the rules before continuing.'), 
          LocalizableModel(key: 'area_social_nav_edit_reserva', text: 'Edit Reservation'), 
          LocalizableModel(key: 'area_social_nav_reservar', text: 'Reserve'), 
          LocalizableModel(key: 'area_social_data_reserva', text: 'Reservation date:'), 
          LocalizableModel(key: 'area_social_hora_reserva', text: 'Reservation time:'), 
          LocalizableModel(key: 'area_social_reservado', text: 'Reserved:'), 
      
          //ASSEMBLEIA
          LocalizableModel(key: 'assembleia_infos', text: 'ASSEMBLY INFORMATION'), 
          LocalizableModel(key: 'assembleia_local', text: 'Location'), 
          LocalizableModel(key: 'assembleia_nav_edit', text: 'Edit Meeting'), 
          LocalizableModel(key: 'assembleia_nav_new', text: 'New Meeting'), 
          LocalizableModel(key: 'assembleia_data_local', text: 'ABOUT THE DATE AND LOCATION'), 
          LocalizableModel(key: 'assembleia_link_online', text: 'Link (if the meeting is online)'), 
          LocalizableModel(key: 'assembleia_arquivos', text: 'Insira os arquivos aqui\n(Apenas formato .PDF)'), 
      
          LocalizableModel(key: 'assembleia_alert_ata', text: 'Insert the MINUTES to end this Meeting'), 
          LocalizableModel(key: 'assembleia_encerrada', text: 'A assembléia foi encerrada!\nA ATA se encontra disponível para consulta no menu "Docs" do seu condomínio.'), 
          LocalizableModel(key: 'assembleia_finalize_upload', text: 'End the meeting.\nUpload the Minutes'), 
          LocalizableModel(key: 'assembleia_upload_ata', text: 'Insert the Meeting Minutes here'), 
          
      
          //VOTACAO
          LocalizableModel(key: 'votacao_signup_informe_opcoes', text: 'Inform the voting options.'), 
          LocalizableModel(key: 'votacao_signup_nav', text: 'Create Poll'), 
          LocalizableModel(key: 'votacao_signup_infos', text: 'VOTING INFORMATION'), 
          LocalizableModel(key: 'votacao_signup_dt_encerramento', text: 'Closing date'), 
          LocalizableModel(key: 'votacao_opcoes', text: 'OPTIONS'), 
          LocalizableModel(key: 'votacao_opcao', text: 'Option'), 
          LocalizableModel(key: 'votacao_confirm_delete', text: 'Are you sure you want to end the vote before the planned end date?'), 
          LocalizableModel(key: 'votacao_enquete', text: 'Poll'), 
          LocalizableModel(key: 'votacao_infos', text: 'POLL INFORMATION'), 
          LocalizableModel(key: 'votacao_agendado', text: 'Scheduled'), 
          LocalizableModel(key: 'votacao_andamento', text: 'In progress'), 
          LocalizableModel(key: 'votacao_finalizado', text: 'Finalized'), 
          LocalizableModel(key: 'votacao_finalizar', text: 'End voting?'), 
          LocalizableModel(key: 'votacao_fora_periodo', text: 'Voting outside the permitted period.'), 
      
          //COMUNICADO
          LocalizableModel(key: 'comunicado_nav_edit', text: 'Edit Announcement'), 
          LocalizableModel(key: 'comunicado_nav_new', text: 'New Announcement'), 
          LocalizableModel(key: 'comunicados_infos', text: 'ANNOUNCEMENT INFORMATION'), 
      
          //CONFIGURACAO
          LocalizableModel(key: 'config_delete_account_sucesso', text: 'A exclusão da sua conta foi solicitada!\nA equipe responsável lhe comunicará do andamento!'), 
          LocalizableModel(key: 'config_nav', text: 'Settings'), 
          LocalizableModel(key: 'config_termos_uso', text: 'Terms of Use'), 
          LocalizableModel(key: 'config_politica_privacidade', text: 'Privacy Policy'), 
          LocalizableModel(key: 'config_fale_conosco', text: 'Contact Us'), 
          LocalizableModel(key: 'config_fale_conosco_descricao', text: "Contact us via email with your questions and/or requests.\n\nAnd don't forget to identify yourself.\n\ncontato@click-app.co\n"), 
          LocalizableModel(key: 'config_alt_senha', text: 'Change password'), 
          LocalizableModel(key: 'config_delete_cond', text: 'Delete condominium'), 
          LocalizableModel(key: 'config_delete_account', text: 'Delete my account'), 
          LocalizableModel(key: 'config_nova_senha', text: 'New password'), 
          LocalizableModel(key: 'config_confirm_nova_senha', text: 'Confirm new password'), 
          LocalizableModel(key: 'config_alt_senha_sucesso', text: 'Password changed successfully!'), 
      
          //ASSINATURA
          LocalizableModel(key: 'assinatura', text: 'Subscription'), 
          LocalizableModel(key: 'assinatura_morador', text: 'Resident Subscription'), 
          LocalizableModel(key: 'assinatura_condominio', text: 'Condominium Subscription'), 
          LocalizableModel(key: 'assinatura_erro', text: 'There was an error with your purchase, please try again.'), 
          LocalizableModel(key: 'assinatura_renovada', text: 'Subscription renewed successfully!'), 
          LocalizableModel(key: 'assinatura_produto_nao_localizado', text: 'Product not found!'), 
          LocalizableModel(key: 'assinatura_erro_loja', text: 'The app was unable to communicate with the store, please try again later!'), 
          LocalizableModel(key: 'assinatura_tipo_renovacao', text: 'Renewal type:'),
          LocalizableModel(key: 'assinatura_mensal', text: 'Monthly'),
          LocalizableModel(key: 'assinatura_validade', text: 'Validity:'),
          LocalizableModel(key: 'assinatura_dias_restantes', text: 'Days remaining:'),
          LocalizableModel(key: 'assinatura_venceu', text: 'Your subscription has expired!'),
          LocalizableModel(key: 'assinatura_renove_agora', text: 'Renew now for another 30 days and stay up to date with everything that happens in your condominium!'),    
          LocalizableModel(key: 'assinatura_cond_renove_agora', text: 'Renew now for another 30 days and ensure greater peace of mind in managing your condominium!'),    
          LocalizableModel(key: 'assinatura_cond_contato_sindico', text: 'Contact the building manager and inform them about the renewal of the App Click plan.'), 
          LocalizableModel(key: 'assinatura_renove_agora_obs', text: 'If you still have days left, the renewal will start counting from the expiration date of the current plan.'),    
          LocalizableModel(key: 'assinatura_btn_mensal_morador', text: 'Renew now'),    
          LocalizableModel(key: 'assinatura_btn_mensal_cond', text: 'Renew now'),    
          LocalizableModel(key: 'assinatura_renovar_depois', text: 'Renew later'),  
          LocalizableModel(key: 'assinatura_renovar_7_dias', text: 'You can renew your plan with 7 days left until the expiration date!' ),  
           
          
      
          //DOCS
          LocalizableModel(key: 'docs_nav_atas', text: 'Minutes'), 
          LocalizableModel(key: 'docs_nav', text: 'Documents'), 
          LocalizableModel(key: 'docs_nav_new', text: 'New Document'), 
          LocalizableModel(key: 'docs_title', text: 'Document title'), 
          LocalizableModel(key: 'docs_upload', text: 'Insert your document here'), 
      
          //FINANCEIRO
          LocalizableModel(key: 'financeiro_inadimplente', text: 'Defaulter'), 
          LocalizableModel(key: 'financeiro_inadimplentes', text: 'Defaulters'), 
          LocalizableModel(key: 'financeiro_meses_aberto', text: 'OPEN MONTHS'), 
          LocalizableModel(key: 'financeiro_nav_relatorio', text: 'Summary'), 
          LocalizableModel(key: 'financeiro_nav_resultado', text: 'RESULT'),
          LocalizableModel(key: 'financeiro_total_receitas', text: 'Total Revenue:'), 
          LocalizableModel(key: 'financeiro_total_despesas', text: 'Total Expenses:'), 
          LocalizableModel(key: 'financeiro_resultado_periodo', text: 'Result for the period:'), 
          LocalizableModel(key: 'financeiro_nav_arrecadacoes', text: 'Collections'),
          LocalizableModel(key: 'financeiro_sem_lancamentos', text: 'There are no entries in the period'),
          LocalizableModel(key: 'financeiro_nenhum_inadimplente', text: 'No defaulters found'),
          LocalizableModel(key: 'financeiro_despesa', text: 'Expenses'), 
          LocalizableModel(key: 'financeiro_despesas', text: 'Expenses'), 
          LocalizableModel(key: 'financeiro_arrecadacoes', text: 'Collections'),  
          LocalizableModel(key: 'financeiro_receita_outras', text: 'Revenue - Other'),  
          LocalizableModel(key: 'financeiro_receita', text: 'Revenue'), 
          LocalizableModel(key: 'financeiro_recebedor', text: 'RECEIVER'), 
          LocalizableModel(key: 'financeiro_fornecedor', text: 'Supplier'), 
          LocalizableModel(key: 'financeiro_categoria', text: 'Category'), 
          LocalizableModel(key: 'financeiro_dt_pag', text: 'Payment Date'), 
          LocalizableModel(key: 'financeiro_valores', text: 'VALUES'), 
          LocalizableModel(key: 'financeiro_valor', text: 'Value'), 
          LocalizableModel(key: 'financeiro_forma_pagamento', text: 'Payment method'), 
          LocalizableModel(key: 'financeiro_parcelas', text: 'Number of installments'), 
          LocalizableModel(key: 'financeiro_conta_debito', text: 'Debit account'),
          LocalizableModel(key: 'financeiro_desc_comprovante', text: 'DESCRIPTION AND PROOF (OPTIONAL)'), 
          LocalizableModel(key: 'financeiro_anexo_comprovante', text: 'Click here and attach a photo of the receipt or invoice'), 
          LocalizableModel(key: 'financeiro_arrecadacao', text: 'Collection'), 
          LocalizableModel(key: 'financeiro_lancamento', text: 'Entry'), 
          LocalizableModel(key: 'financeiro_mes_referencia', text: 'Reference month'), 
          LocalizableModel(key: 'financeiro_data_vencimento', text: 'Due date'), 
          LocalizableModel(key: 'financeiro_pagador', text: 'Payer'), 
          LocalizableModel(key: 'financeiro_tipo', text: 'Type'), 
          LocalizableModel(key: 'financeiro_forn_cliente', text: 'Supplier / Customer'), 
          LocalizableModel(key: 'financeiro_data_recebimento', text: 'Receipt date'),
          LocalizableModel(key: 'financeiro_conta_bancaria', text: 'Bank account'),
          LocalizableModel(key: 'financeiro_nav_edit', text: 'Edit Entry'),
          LocalizableModel(key: 'financeiro_nav_new', text: 'New Entry'),
          LocalizableModel(key: 'financeiro_saldo_dia', text: 'Balance on the day'),
      
          LocalizableModel(key: 'financeiro_categ_consumo', text: 'Consumption'),
          LocalizableModel(key: 'financeiro_categ_manutencao', text: 'Maintenance'),
          LocalizableModel(key: 'financeiro_categ_pessoal', text: 'Personal'),
          LocalizableModel(key: 'financeiro_categ_impostos', text: 'Taxes'),
          LocalizableModel(key: 'financeiro_categ_adms', text: 'Administrative'),
          LocalizableModel(key: 'financeiro_categ_outras', text: 'Others'),
      
          LocalizableModel(key: 'financeiro_conta_corrente', text: 'Current account'),
          LocalizableModel(key: 'financeiro_conta_poupanca', text: 'Savings'),
          LocalizableModel(key: 'financeiro_conta_outra', text: 'Other'),
      
          LocalizableModel(key: 'financeiro_dinheiro', text: 'Cash'),
          LocalizableModel(key: 'financeiro_pix', text: 'Pix'),
          LocalizableModel(key: 'financeiro_boleto', text: 'Boleto'),
          LocalizableModel(key: 'financeiro_cartao_credito', text: 'Credit card'),
          LocalizableModel(key: 'financeiro_cartao_debito', text: 'Debit card'),
          LocalizableModel(key: 'financeiro_outra', text: 'Other'),
      
      
          //FUNCIONÁRIO
          LocalizableModel(key: 'funcionario_nav_edit', text: 'Edit Employee'), 
          LocalizableModel(key: 'funcionario_nav_new', text: 'Register Employee'), 
          LocalizableModel(key: 'funcionario_infos_pessoais', text: 'PERSONAL INFORMATION'), 
          LocalizableModel(key: 'funcionario_infos_funcao', text: 'INFORMATION RELATED TO THE FUNCTION'), 
          LocalizableModel(key: 'funcionario_funcao', text: 'Function'), 
          LocalizableModel(key: 'funcionario_horario_trabalho', text: 'Working hours work'), 
          LocalizableModel(key: 'funcionario_permissoes', text: 'PERMISSIONS WITHIN THE APPLICATION'),     
          LocalizableModel(key: 'funcionario_permissoes_sobre', text: 'By enabling a permission, you will be granting this employee the autonomy of the condominium manager to the chosen menu!'),
          LocalizableModel(key: 'funcionario_infos_extra', text: 'EXTRA INFORMATION (OPTIONAL)'),
          LocalizableModel(key: 'funcionario_infos_extra_1', text: 'Extra Information 1'),
          LocalizableModel(key: 'funcionario_infos_extra_2', text: 'Extra Information 2'),
          LocalizableModel(key: 'funcionario_infos_extra_3', text: 'Extra Information 3'),
          LocalizableModel(key: 'funcionario_infos_extra_4', text: 'Extra Information 4'),
          LocalizableModel(key: 'funcionario_infos_acesso', text: 'ACCESS INFORMATION'),
          LocalizableModel(key: 'funcionario_senha', text: 'Click Access Password'),
      
          //MORADORES
          LocalizableModel(key: 'moradores_empty', text: 'There are no residents registered yet'), 
      
          //APARTAMENTO
          LocalizableModel(key: 'apto_desc', text: 'To register a new apartment, enter the data below:'), 
          LocalizableModel(key: 'apto_fracao', text: 'Ideal fraction'), 
          LocalizableModel(key: 'apto_proprietarios', text: 'Owners:'), 
          LocalizableModel(key: 'apto_inquilinos', text: 'Tenants:'), 
          LocalizableModel(key: 'apto_usuario_criado_msg', text: 'Usuário criado!\nInforme que a senha padrão será o número do documento e que ao entrar na conta a senha poderá ser alterada.'), 
          
          //MUDANCA
          LocalizableModel(key: 'mudanca_nav', text: 'Schedules Change'),  
          LocalizableModel(key: 'mudanca_nav_edit', text: 'Edit Change'),
          LocalizableModel(key: 'mudanca_nav_new', text: 'Request Change'),
          LocalizableModel(key: 'mudanca_pendente_aprovacao', text: 'Este item não está mais pendente aprovação.\nVocê não pode mais editá-lo.'), 
          LocalizableModel(key: 'mudanca_selecione_apto', text: 'Select the desired apartment'),   
          LocalizableModel(key: 'mudanca_infos_mudanca', text: 'INFORMATION ABOUT THE MOVE'),   
          LocalizableModel(key: 'mudanca_motivo_recusa', text: 'Reason for Refusal'),   
      
          //OCORRÊNCIA
          LocalizableModel(key: 'ocorrencia_sobre', text: 'ABOUT THE INCIDENT'),  
          LocalizableModel(key: 'ocorrencia_respondido', text: 'Answered on'),  
          LocalizableModel(key: 'ocorrencia_resposta', text: 'Write the response to the resident here'),  
          LocalizableModel(key: 'ocorrencia_status', text: 'Select the status:'), 
          LocalizableModel(key: 'ocorrencia_abertura_nav', text: 'Opening Incidents'), 
          LocalizableModel(key: 'ocorrencia_erro_tipo', text: 'Select the type of incident!'),     
          LocalizableModel(key: 'ocorrencia_nav_edit', text: 'Select the type of incident!'),   
          LocalizableModel(key: 'ocorrencia_tipo', text: 'Type of occurrence'),   
      
          //PRESTADORES
          LocalizableModel(key: 'prestador_eletricista', text: '⚡ Electrician'),  
          LocalizableModel(key: 'prestador_hidraulica', text: '🚰 Plumber / Plumber'),  
          LocalizableModel(key: 'prestador_pintor', text: '🎨 Painter'),  
          LocalizableModel(key: 'prestador_pedreiro', text: '🏚 Mason'),  
          LocalizableModel(key: 'prestador_limpeza', text: '🧹 Cleaning'),  
          LocalizableModel(key: 'prestador_dedetizacao', text: '🐜 Pest control'),  
          LocalizableModel(key: 'prestador_nav_edit', text: 'Edit Service Provider'),
          LocalizableModel(key: 'prestador_nav_new', text: 'Register Service Provider'),
          LocalizableModel(key: 'prestador_infos', text: 'PROVIDER INFORMATION'),
          LocalizableModel(key: 'prestador_funcoes', text: 'FUNCTIONS'),
          LocalizableModel(key: 'prestador_selecione_categoria', text:  'Select category(ies):'),
          LocalizableModel(key: 'prestador_categoria_desc', text: 'Or enter other category(ies): (separated by commas)'),
      
          //VISITANTES
          LocalizableModel(key: 'visitantes_list', text: 'Visitor List'),  
          LocalizableModel(key: 'visitantes_nav_new', text: 'Register new visitor'),
          LocalizableModel(key: 'visitantes_nav_edit', text: 'Edit Visitor'),
          LocalizableModel(key: 'visitantes_infos', text: 'VISIT INFORMATION'),
          LocalizableModel(key: 'visitantes_data_hora_inicio', text: 'Start date and time of release'),
          LocalizableModel(key: 'visitantes_data_hora_termino', text: 'End date and time of release'),
          LocalizableModel(key: 'visitante', text: 'Visitor'),
          LocalizableModel(key: 'prestador', text: 'Provider'),
          LocalizableModel(key: 'visitante_prestador_servico', text: 'Service Provider'),
          LocalizableModel(key: 'visitante_erro_bloco', text: 'First select the block!'),

          //OUTROS
          LocalizableModel(key: 'pessoas', text: 'People'),
          LocalizableModel(key: 'capacidade_indeterminada', text: 'Undetermined capacity'),
          LocalizableModel(key: 'pagos', text: 'Paid'),
          LocalizableModel(key: 'escolha_opcao_desejada', text: 'Choose the desired option'),
          LocalizableModel(key: 'ciente', text: 'Aware'),
          LocalizableModel(key: 'solucionado', text: 'Solved'),
          LocalizableModel(key: 'urgente', text: 'Urgent'),
          LocalizableModel(key: 'manutencao', text: 'Maintenance'),
          LocalizableModel(key: 'outros', text: 'Others'),
          LocalizableModel(key: 'primeiro_documento', text: 'First Document'),
          LocalizableModel(key: 'link_erro', text: 'Unable to open the link'),
          LocalizableModel(key: 'invalid_data', text: 'Invalid date entered!'),
          LocalizableModel(key: 'invalid_hora', text: 'Invalid time entered!'),
          LocalizableModel(key: 'senhas_nao_conferem', text: 'The passwords entered do not match.'),
          LocalizableModel(key: 'senha_minimo_caracteres', text: 'The password must contain at least 6 characters.'),
          LocalizableModel(key: 'libere_funcoes', text: 'Release the Desired Functions'),
          LocalizableModel(key: 'editar_manutencao', text: 'Edit Maintenance'),
          LocalizableModel(key: 'nova_manutencao', text: 'New Maintenance'),
          LocalizableModel(key: 'gerar_alerta', text: 'Generate alert for residents'),

          LocalizableModel(key: 'moeda', text: 'Currency'),
          LocalizableModel(key: 'moeda_real', text: 'R\$ (Brazilian real)'),
          LocalizableModel(key: 'moeda_dolar_americano', text: 'US\$ (US Dollar)'),
          LocalizableModel(key: 'moeda_euro', text: '€ (Euro)'),
          LocalizableModel(key: 'moeda_libra', text: '£ (Pound)'),
          LocalizableModel(key: 'moeda_peso_mexicano', text: 'Mex\$ (Mexican peso)'),
          LocalizableModel(key: 'moeda_generico', text: '\$'),

          LocalizableModel(key: 'assinatura_semestral', text: 'Six Months'),
          LocalizableModel(key: 'assinatura_anual', text: 'Yearly'),

          LocalizableModel(key: 'meus_condominios', text: 'My Condominiums'),
      
        ];
      
      }
