import 'package:click/utils/localizable/localizable.dart';

class Localizable_Es {

  final List<LocalizableModel> strings = [
    // Idioma
          LocalizableModel(key: 'language_idioma', text: 'Idioma'),
          LocalizableModel(key: 'language_pt_br', text: 'portugués brasileño'),
          LocalizableModel(key: 'language_pt_pt', text: 'portugués portugal'),
          LocalizableModel(key: 'language_en', text: 'Inglés'),
          LocalizableModel(key: 'language_es', text: 'Español'),
          LocalizableModel(key: 'language_al', text: 'Alemán'),
      
          // Data
          LocalizableModel(key: 'data_informar', text: 'Ingrese la fecha deseada.'),
          LocalizableModel(key: 'data_selecionar_horario', text: 'Seleccione el horario deseado.'),
          LocalizableModel(key: 'data_das', text: 'Dar'),    
          LocalizableModel(key: 'data_as', text: 'Hacia'),    
          LocalizableModel(key: 'data_e_hora', text: 'Fecha y hora'),
          LocalizableModel(key: 'dia_e_hora', text: 'Día y hora'),
          LocalizableModel(key: 'dia', text: 'Día'),
          LocalizableModel(key: 'días', text: 'días'),
          LocalizableModel(key: 'data', text: 'Fecha'),
          LocalizableModel(key: 'datas', text: 'Fechas'),
          LocalizableModel(key: 'hora', text: 'Tiempo'),
          LocalizableModel(key: 'data_inicio', text: 'Fecha de inicio'),
          LocalizableModel(key: 'hora_inicio', text: 'Hora de inicio'),
          LocalizableModel(key: 'data_termino', text: 'Fecha de finalización'),
          LocalizableModel(key: 'hora_termino', text: 'Hora de finalización'),
          LocalizableModel(key: 'data_hora_criacao', text: 'FECHA Y HORA DE CREACIÓN'),
          LocalizableModel(key: 'data_hora_inicio', text: 'Fecha y hora de inicio'),
          LocalizableModel(key: 'segunda', text: 'Segundo'),
          LocalizableModel(key: 'terca', text: 'Tercero'),
          LocalizableModel(key: 'quarta', text: 'Cuatro'),
          LocalizableModel(key: 'quinta', text: 'Quinto'),
          LocalizableModel(key: 'sexta', text: 'Viernes'),
          LocalizableModel(key: 'sabado', text: 'Sábado'),
          LocalizableModel(key: 'domingo', text: 'Domingo'),
      
          // Modal Select Month
          LocalizableModel(key: 'modal_select_month_btn_ok', text: 'DE ACUERDO'),
          LocalizableModel(key: 'modal_select_month_btn_cancel', text: 'Cancelar'),
      
          //TextField
          LocalizableModel(key: 'textfield_long_placeholder', text: 'Escribe aquí...'),
          LocalizableModel(key: 'textfield_short_placeholder', text: 'Escribe tu mensaje...'),
      
          //Label
          LocalizableModel(key: 'label_to', text: 'A:'),
          LocalizableModel(key: 'label_of', text: 'de'),
          LocalizableModel(key: 'label_until', text: 'hasta'),
          LocalizableModel(key: 'ola', text: 'Hola'),
          LocalizableModel(key: 'sindico', text: 'Receptor'),
          LocalizableModel(key: 'morador', text: 'Residente'),
          LocalizableModel(key: 'funcionario', text: 'Empleado'),
          LocalizableModel(key: 'email', text: 'Correo electrónico'),
          LocalizableModel(key: 'senha', text: 'Contraseña'),
          LocalizableModel(key: 'vesaoApp', text: 'Versión:'),
          LocalizableModel(key: 'nome', text: 'Nombre'),
          LocalizableModel(key: 'user_nome_completo', text: 'nombre completo'),
          LocalizableModel(key: 'user_documento', text: 'Documento de identificación'),
          LocalizableModel(key: 'data_nascimento', text: 'Fecha de nacimiento'),
          LocalizableModel(key: 'email', text: 'Correo electrónico'),
          LocalizableModel(key: 'telefone', text: 'Teléfono'),
          LocalizableModel(key: 'senha', text: 'Contraseña'),
          LocalizableModel(key: 'editar_infos', text: 'Editar información'),
          LocalizableModel(key: 'label_exclusao', text: '¡Exclusión!'),
      
          LocalizableModel(key: 'lb_areas_sociais', text: 'Áreas Sociales'),
          LocalizableModel(key: 'lb_area_social', text: 'Área Social'),
          LocalizableModel(key: 'lb_financeiro', text: 'Financiero'),
          LocalizableModel(key: 'lb_assembleia_votacoes', text: 'Asambleas y votaciones'),
          LocalizableModel(key: 'lb_assembleias', text: 'Asambleas'),
          LocalizableModel(key: 'lb_assembleia', text: 'Asamblea'),
          LocalizableModel(key: 'lb_votacoes', text: 'Centro'),
          LocalizableModel(key: 'lb_enquetes', text: 'Centro'),
          LocalizableModel(key: 'lb_comunicados', text: 'Anuncios'),
          LocalizableModel(key: 'lb_comunicado', text: 'Anuncio'),
          LocalizableModel(key: 'lb_ocorrencias', text: 'Ocurrencias'),
          LocalizableModel(key: 'lb_ocorrencia', text: 'Aparición'),
          LocalizableModel(key: 'lb_funcionarios', text: 'Empleados'),
          LocalizableModel(key: 'lb_funcionarios_condominio', text: 'Personal del condominio'),
          LocalizableModel(key: 'lb_manut_programadas', text: 'Mantenimiento programado'),
          LocalizableModel(key: 'lb_manut_programada', text: 'Mantenimiento programado'),
          LocalizableModel(key: 'lb_prestadores_servico', text: 'Proveedores de servicios'),
          LocalizableModel(key: 'lb_agendar_mudanca', text: 'Cambio de horario'),
          LocalizableModel(key: 'lb_cadastrar_visitante', text: 'Registrar visitante'),
          LocalizableModel(key: 'lb_apartamentos', text: 'Apartamentos'),
          LocalizableModel(key: 'lb_apartamento', text: 'Departamento'),
          LocalizableModel(key: 'lb_docs', text: 'Documentos'),
          LocalizableModel(key: 'lb_apto', text: 'Departamento'),
          LocalizableModel(key: 'lb_ref', text: 'Árbitro.'),
          LocalizableModel(key: 'lb_saldo', text: 'Balance'),
          LocalizableModel(key: 'lb_status', text: 'Estado'),
          LocalizableModel(key: 'lb_categorias', text: 'Categorías'),
          LocalizableModel(key: 'lb_categoria', text: 'Categoría'),
          LocalizableModel(key: 'lb_anexos', text: 'Adjuntos'),
          LocalizableModel(key: 'lb_insira_fotos', text: 'Inserta tus fotos aquí'),
          LocalizableModel(key: 'lb_tipo', text: 'Tipo'),
          LocalizableModel(key: 'lb_resposta', text: 'Respuesta'),
          LocalizableModel(key: 'lb_todos', text: 'Todo'),
          LocalizableModel(key: 'lb_pendentes', text: 'Colgantes'),
          LocalizableModel(key: 'lb_buscar', text: 'Buscar'),
          LocalizableModel(key: 'lb_aviso', text: 'Aviso'),
          LocalizableModel(key: 'lb_ultima_atualizacao', text: 'Última actualización'),
          LocalizableModel(key: 'lb_ciente', text: 'Consciente'),
          LocalizableModel(key: 'lb_pendente', text: 'Pendiente'),
          LocalizableModel(key: 'lb_aprovado', text: 'Aprobado'),
          LocalizableModel(key: 'lb_recusado', text: 'Rechazado'),
          LocalizableModel(key: 'lb_solucionado', text: 'Resuelto'),
          LocalizableModel(key: 'lb_nao_informado', text: 'No informado'),
          LocalizableModel(key: 'lb_aceitar', text: 'aceptar'),
          LocalizableModel(key: 'lb_recusar', text: 'Rechazar'),
          LocalizableModel(key: 'lb_finalizar', text: 'Finalizar'),
      
          LocalizableModel(key: 'lb_titulo', text: 'Título'),
          LocalizableModel(key: 'lb_descricao', text: 'Descripción'),
          LocalizableModel(key: 'lb_descricao_opcional', text: 'DESCRIPCIÓN (OPCIONAL)'),
          LocalizableModel(key: 'lb_observacoes_opcional', text: 'NOTAS (OPCIONAL)'),
          LocalizableModel(key: 'lb_observacoes', text: 'Observaciones'),    
          LocalizableModel(key: 'lb_inicio', text: 'Comenzar'),
          LocalizableModel(key: 'lb_termino', text: 'Terminación'),
          LocalizableModel(key: 'lb_autorizado_por', text: 'Autorizado por'),
      
          LocalizableModel(key: 'lb_infos_apto', text: 'INFORMACIÓN DEL APARTAMENTO'),
          LocalizableModel(key: 'lb_bloco', text: 'Bloquear'),
      
          LocalizableModel(key: 'lb_li_concordo', text: 'He leído y acepto las reglas.'),
          LocalizableModel(key: 'lb_complementos', text: 'Complementos'),
      
          LocalizableModel(key: 'lb_logout', text: 'para salir'),
      
          //Button
          LocalizableModel(key: 'btn_save', text: 'AHORRAR'),
          LocalizableModel(key: 'btn_delete', text: 'Borrar'),
          LocalizableModel(key: 'btn_enviar', text: 'PARA ENVIAR'),
          LocalizableModel(key: 'btn_proximo', text: 'PRÓXIMO'),
          LocalizableModel(key: 'btn_anterior', text: 'ANTERIOR'),
      
          //UPLOAD
          LocalizableModel(key: 'upload_max_number', text: 'Número máximo de documentos alcanzado'),
      
          // ALERT
          LocalizableModel(key: 'alert', text: '¡Alerta!'),
          LocalizableModel(key: 'alert_alert', text: 'Aviso'),
          LocalizableModel(key: 'alert_success', text: '¡Éxito!'),
          LocalizableModel(key: 'alert_error', text: '¡Error!'),
          LocalizableModel(key: 'alert_ops', text: '¡Ups!'),
          LocalizableModel(key: 'alert_invalid_value', text: '¡Valor no válido ingresado!'),
          LocalizableModel(key: 'alert_sim', text: 'Sí'),
          LocalizableModel(key: 'alert_nao', text: 'No'),
          LocalizableModel(key: 'alert_em_breve', text: '¡Dentro de poco!'),
          LocalizableModel(key: 'alert_em_breve_description', text: 'Estamos trabajando para que este servicio esté disponible lo antes posible.'),    
          LocalizableModel(key: 'alert_delete_description', text: '¿Está seguro de que desea eliminar este elemento de forma permanente?'),
          LocalizableModel(key: 'alert_cancel_description', text: '¿Estás seguro de que deseas cancelar este artículo?'),
          LocalizableModel(key: 'alert_photo_choice', text: '¿Quieres tomar una foto ahora o seleccionar una foto de la galería?'),
          LocalizableModel(key: 'alert_doc_choice', text: '¿Quieres adjuntar algún documento o imagen?'),
          LocalizableModel(key: 'alert_photo_camera', text: 'Cámara'),
          LocalizableModel(key: 'alert_photo_galeria', text: 'Galería'),
          LocalizableModel(key: 'alert_photo_image', text: 'Imagen'),
          LocalizableModel(key: 'alert_document', text: 'Documento'),
          LocalizableModel(key: 'alert_generic_error', text: 'Hubo un error, ¡inténtalo de nuevo!'),
          LocalizableModel(key: 'alert_list_empty_generic', text: '¡No se encontraron registros!'),
          LocalizableModel(key: 'alert_upload_image', text: 'Inserta la imagen.'),
          LocalizableModel(key: 'alert_dados_alterados', text: '¡Los datos cambiaron exitosamente!'),
          LocalizableModel(key: 'alert_nenhum_bloco', text: '¡No se encontraron bloques!\nPrimero registre las unidades en el menú "Apartamentos".'),
          LocalizableModel(key: 'alert_nenhum_apto', text: '¡No se encontraron apartamentos!\no Primero registre las unidades en el menú "Apartamentos" en la pantalla de inicio.'),
      
          // ACESSO
          LocalizableModel(key: 'sou_sindico', text: 'SOY SINDICANO'),
          LocalizableModel(key: 'sou_morador', text: 'SOY RESIDENTE'),
          LocalizableModel(key: 'sou_funcionario', text: 'SOY EMPLEADO'),
          LocalizableModel(key: 'view_hello_text', text: '¿Registramos su primer condominio?'),
          LocalizableModel(key: 'vamos_cadastrar', text: 'vamos a registrarnos'),
          LocalizableModel(key: 'possuo_cadastro', text: 'ya tengo un registro'),
          
          // LOGIN
          LocalizableModel(key: 'login_btn_entrar', text: 'PARA ENTRAR'),
          LocalizableModel(key: 'login_btn_esqueci_senha', text: '¿Olvidaste tu contraseña?'),
          LocalizableModel(key: 'login_error', text: 'Nombre de usuario o contraseña incorrectos. Intentar otra vez'),
      
          // ESQUECI A SENHA
          LocalizableModel(key: 'esqueci_senha_nav', text: 'Has olvidado tu contraseña'),
          LocalizableModel(key: 'esqueci_senha_title', text: '¿Olvidaste tu contraseña?'),
          LocalizableModel(key: 'esqueci_senha_description', text: 'No te preocupes, completa tu correo electrónico a continuación y te enviaremos un enlace de recuperación.'),
          LocalizableModel(key: 'esqueci_senha_send_description', text: 'El enlace de recuperación ha sido enviado a su correo electrónico.'),    
      
          // CADASTRO SÍNDICO
          LocalizableModel(key: 'signup_nav_sindico', text: 'Registro del receptor'),
          LocalizableModel(key: 'sindico_nav_edit', text: 'Editar datos'),
          LocalizableModel(key: 'signup_success', text: '¡Registro completado exitosamente!'),
          LocalizableModel(key: 'signup_erro_dt_nascimento', text: '¡Fecha de nacimiento no válida!'),
          LocalizableModel(key: 'signup_infos_contato', text: 'INFORMACIÓN DEL CONTACTO'),
      
          // CADASTRO CONDOMINIO
          LocalizableModel(key: 'signup_cond_nav', text: 'Registro de Condominio'),
          LocalizableModel(key: 'condominio_nav_edit', text: 'Editar Condominio'),
          LocalizableModel(key: 'condominio_nav_edit_address', text: 'Editar Condominio'),
          LocalizableModel(key: 'signup_cond_error_nome', text: 'Ingrese el nombre del condominio.'),
          LocalizableModel(key: 'signup_cond_error_doc', text: 'Proporcionar el documento de identificación del condominio.'),
          LocalizableModel(key: 'signup_cond_error_subsindico', text: 'Ingrese el nombre del diputado.'),
          LocalizableModel(key: 'signup_cond_error_dt_inicio_mandato', text: 'Introduzca la fecha de inicio del mandato'),
          LocalizableModel(key: 'signup_cond_error_dt_fim_mandato', text: 'Introduzca la fecha de finalización del mandato.'),
          LocalizableModel(key: 'signup_cond_error_dt_anterior', text: 'Fecha de finalización anterior a la fecha de inicio.'), 
          LocalizableModel(key: 'signup_cond_error_cep', text: 'Ingrese el código postal.'),  
          LocalizableModel(key: 'signup_cond_error_pais', text: 'Ingrese al país.'),  
          LocalizableModel(key: 'signup_cond_error_estado', text: 'Informar al Estado.'),  
          LocalizableModel(key: 'signup_cond_error_cidade', text: 'Informar al Ayuntamiento.'),  
          LocalizableModel(key: 'signup_cond_error_bairro', text: 'Informar al Vecindario.'),  
          LocalizableModel(key: 'signup_cond_error_rua', text: 'Informar a Rúa.'),  
          LocalizableModel(key: 'signup_cond_error_numero', text: 'Ingrese el número.'),  
      
          LocalizableModel(key: 'signup_cond_nome', text: 'Nombre del condominio'),
          LocalizableModel(key: 'signup_cond_subsindico_nome', text: 'Nombre de la subsidiaria'),
          LocalizableModel(key: 'signup_cond_ini_mandato', text: 'Fecha de inicio del plazo'),
          LocalizableModel(key: 'signup_cond_fim_mandato', text: 'Fecha de finalización del plazo'),
          LocalizableModel(key: 'signup_cond_cep', text: 'código postal'),
          LocalizableModel(key: 'signup_cond_pais', text: 'País'),  
          LocalizableModel(key: 'signup_cond_uf', text: 'UF'),  
          LocalizableModel(key: 'signup_cond_cidade', text: 'Ciudad'),  
          LocalizableModel(key: 'signup_cond_bairro', text: 'Vecindario'),  
          LocalizableModel(key: 'signup_cond_rua', text: 'Camino'),  
          LocalizableModel(key: 'signup_cond_numero', text: 'Número'),  
          LocalizableModel(key: 'signup_cond_complemento', text: 'Complementar'),  
      
          LocalizableModel(key: 'signup_cond_valor_total', text: 'A partir de:'),  
          LocalizableModel(key: 'signup_cond_valor_mensal', text: 'R\$ 35,99 / mês'), 
          LocalizableModel(key: 'signup_cond_dias_gratuitos', text: '¡Disfruta de tus 45 días Gratis!'), 
          LocalizableModel(key: 'signup_cond_cancele_label', text: '¡Cancela cuando quieras!'), 
      
          LocalizableModel(key: 'signup_cond_sucesso', text: 'Condominio Registrado EXITOSAMENTE'), 
      
          LocalizableModel(key: 'cond_confirm_delete', text: '¿Está seguro de que desea eliminar este condominio de forma permanente?'), 
          LocalizableModel(key: 'signup_confirm_delete', text: '¿Estás seguro de que deseas eliminar tu cuenta permanentemente?'), 
      
          LocalizableModel(key: 'condominio_edit_dados', text: 'Editar datos del condominio'),
          LocalizableModel(key: 'condominio_edit_endereco', text: 'Actualizar dirección'),
          
        
          //MANUTENCAO PROGRAMADA
          LocalizableModel(key: 'manut_edit_nav', text: 'Editar cita de la agenda'), 
          LocalizableModel(key: 'manut_signup_nav', text: 'Nuevo compromiso en la agenda'), 
          LocalizableModel(key: 'manut_about', text: 'SOBRE EL COMPROMISO'), 
          LocalizableModel(key: 'manut_nav', text: 'Solicitudes de mantenimiento'), 
          LocalizableModel(key: 'manut_edit', text: 'Editar solicitud'), 
          LocalizableModel(key: 'manut_new', text: 'Nueva Solicitud'), 
          
      
      
          //AREA SOCIAL
          LocalizableModel(key: 'area_social_precisa_agendamento', text: 'Se requiere cita previa'), 
          LocalizableModel(key: 'area_social_precisa_autorizacao', text: 'Requiere autorización'), 
          LocalizableModel(key: 'area_social_precisa_pagamento', text: 'Requerir pago'), 
          LocalizableModel(key: 'area_social_agendamentos', text: 'Equipo'), 
          LocalizableModel(key: 'area_social_meus_agendamentos', text: 'Mis Horarios'), 
          LocalizableModel(key: 'area_social_nenhum_agendamento', text: 'no tienes citas'), 
          LocalizableModel(key: 'area_social_nav_new', text: 'Nueva Área Social'), 
          LocalizableModel(key: 'area_social_dados_iniciais', text: 'DATOS INICIALES'), 
          LocalizableModel(key: 'area_social_capacidade_maxima', text: 'Capacidad máxima'), 
          LocalizableModel(key: 'area_social_capacidade_vazio', text: 'Dejar vacío si no tiene capacidad máxima'), 
          LocalizableModel(key: 'area_social_obrigatoriedades', text: 'OBLIGACIONES'), 
          LocalizableModel(key: 'area_social_novo_horario', text: 'Nuevo horario'), 
          LocalizableModel(key: 'area_social_erro_normas', text: 'Acepta las reglas antes de continuar.'), 
          LocalizableModel(key: 'area_social_nav_edit_reserva', text: 'Editar reserva'), 
          LocalizableModel(key: 'area_social_nav_reservar', text: 'Libro'), 
          LocalizableModel(key: 'area_social_data_reserva', text: 'Fecha de reserva:'), 
          LocalizableModel(key: 'area_social_hora_reserva', text: 'Hora de reserva:'), 
          LocalizableModel(key: 'area_social_reservado', text: 'Reservado:'), 
      
          //ASSEMBLEIA
          LocalizableModel(key: 'assembleia_infos', text: 'INFORMACIÓN DE MONTAJE'), 
          LocalizableModel(key: 'assembleia_local', text: 'Ubicación'), 
          LocalizableModel(key: 'assembleia_nav_edit', text: 'Editar ensamblaje'), 
          LocalizableModel(key: 'assembleia_nav_new', text: 'Nueva Asamblea'), 
          LocalizableModel(key: 'assembleia_data_local', text: 'SOBRE LA FECHA Y EL LUGAR'), 
          LocalizableModel(key: 'assembleia_link_online', text: 'Enlace (si la asamblea es online)'), 
          LocalizableModel(key: 'assembleia_arquivos', text: 'Insira os arquivos aqui\n(Apenas formato .PDF)'), 
      
          LocalizableModel(key: 'assembleia_alert_ata', text: 'Ingrese el ATA para completar este ensamblaje'), 
          LocalizableModel(key: 'assembleia_encerrada', text: 'A assembléia foi encerrada!\nA ATA se encontra disponível para consulta no menu "Docs" do seu condomínio.'), 
          LocalizableModel(key: 'assembleia_finalize_upload', text: 'Finalice el montaje.\nSuba las actas'), 
          LocalizableModel(key: 'assembleia_upload_ata', text: 'Inserte aquí el Acta de la Asamblea'), 
          
      
          //VOTACAO
          LocalizableModel(key: 'votacao_signup_informe_opcoes', text: 'Ingrese sus opciones de votación.'), 
          LocalizableModel(key: 'votacao_signup_nav', text: 'Crear encuesta'), 
          LocalizableModel(key: 'votacao_signup_infos', text: 'INFORMACIÓN DE VOTACIÓN'), 
          LocalizableModel(key: 'votacao_signup_dt_encerramento', text: 'fecha de cierre'), 
          LocalizableModel(key: 'votacao_opcoes', text: 'OPCIONES'), 
          LocalizableModel(key: 'votacao_opcao', text: 'Opción'), 
          LocalizableModel(key: 'votacao_confirm_delete', text: '¿Está seguro de que desea finalizar la votación antes de la fecha de finalización prevista?'), 
          LocalizableModel(key: 'votacao_enquete', text: 'Encuesta'), 
          LocalizableModel(key: 'votacao_infos', text: 'INFORMACIÓN DE LA ENCUESTA'), 
          LocalizableModel(key: 'votacao_agendado', text: 'Programado'), 
          LocalizableModel(key: 'votacao_andamento', text: 'En curso'), 
          LocalizableModel(key: 'votacao_finalizado', text: 'Finalizado'), 
          LocalizableModel(key: 'votacao_finalizar', text: '¿Finalizar la votación?'), 
          LocalizableModel(key: 'votacao_fora_periodo', text: 'Votar fuera del plazo permitido.'), 
      
          //COMUNICADO
          LocalizableModel(key: 'comunicado_nav_edit', text: 'Editar anuncio'), 
          LocalizableModel(key: 'comunicado_nav_new', text: 'Nuevo anuncio'), 
          LocalizableModel(key: 'comunicados_infos', text: 'INFORMACIÓN DE PUBLICACIÓN'), 
      
          //CONFIGURACAO
          LocalizableModel(key: 'config_delete_account_sucesso', text: 'A exclusão da sua conta foi solicitada!\nA equipe responsável lhe comunicará do andamento!'), 
          LocalizableModel(key: 'config_nav', text: 'Ajustes'), 
          LocalizableModel(key: 'config_termos_uso', text: 'Condiciones de uso'), 
          LocalizableModel(key: 'config_politica_privacidade', text: 'política de privacidad'), 
          LocalizableModel(key: 'config_fale_conosco', text: 'Contáctenos'), 
          LocalizableModel(key: 'config_fale_conosco_descricao', text: 'Ponte en contacto vía correo electrónico con tus dudas y/o requerimientos.\n\nY no olvides identificarte.\n\ncontato@click-app.co\n'), 
          LocalizableModel(key: 'config_alt_senha', text: 'Cambiar la contraseña'), 
          LocalizableModel(key: 'config_delete_cond', text: 'Excluir condominio'), 
          LocalizableModel(key: 'config_delete_account', text: 'eliminar mi cuenta'), 
          LocalizableModel(key: 'config_nova_senha', text: 'Nueva contraseña'), 
          LocalizableModel(key: 'config_confirm_nova_senha', text: 'Confirmar nueva contraseña'), 
          LocalizableModel(key: 'config_alt_senha_sucesso', text: '¡La contraseña se cambió correctamente!'), 
      
          //ASSINATURA
          LocalizableModel(key: 'assinatura', text: 'Firma'), 
          LocalizableModel(key: 'assinatura_morador', text: 'Firma del residente'), 
          LocalizableModel(key: 'assinatura_condominio', text: 'Suscripción de condominio'), 
          LocalizableModel(key: 'assinatura_erro', text: 'Hubo un error con tu compra, inténtalo nuevamente.'), 
          LocalizableModel(key: 'assinatura_renovada', text: '¡Suscripción renovada con éxito!'), 
          LocalizableModel(key: 'assinatura_produto_nao_localizado', text: '¡Producto no localizado!'), 
          LocalizableModel(key: 'assinatura_erro_loja', text: 'La aplicación no pudo comunicarse con la tienda. ¡Inténtelo de nuevo más tarde!'), 
          LocalizableModel(key: 'assinatura_tipo_renovacao', text: 'Tipo de renovación:'),
          LocalizableModel(key: 'assinatura_mensal', text: 'Mensual'),
          LocalizableModel(key: 'assinatura_validade', text: 'Validez:'),
          LocalizableModel(key: 'assinatura_dias_restantes', text: 'Días restantes:'),
          LocalizableModel(key: 'assinatura_venceu', text: '¡Tu suscripción ha caducado!'),
          LocalizableModel(key: 'assinatura_renove_agora', text: '¡Renueva ahora por otros 30 días y mantente al día de todo lo que sucede en tu condominio!'),    
          LocalizableModel(key: 'assinatura_cond_renove_agora', text: '¡Renueva ahora por otros 30 días y garantiza más tranquilidad al administrar tu condominio!'),    
          LocalizableModel(key: 'assinatura_cond_contato_sindico', text: 'Contacta con el administrador de la propiedad e infórmale sobre la renovación del plan App Click.'), 
          LocalizableModel(key: 'assinatura_renove_agora_obs', text: 'Si aún te quedan días, la renovación comenzará a contar a partir de la fecha de vencimiento del plan actual.'),    
          LocalizableModel(key: 'assinatura_btn_mensal_morador', text: 'Renovar ahora'),    
          LocalizableModel(key: 'assinatura_btn_mensal_cond', text: 'Renovar ahora'),    
          LocalizableModel(key: 'assinatura_renovar_depois', text: 'Renovar más tarde'),  
          LocalizableModel(key: 'assinatura_renovar_7_dias', text: '¡Podrás renovar tu plan faltando 7 días para la fecha de vencimiento!' ),  
           
          
      
          //DOCS
          LocalizableModel(key: 'docs_nav_atas', text: 'Minutos'), 
          LocalizableModel(key: 'docs_nav', text: 'Documentos'), 
          LocalizableModel(key: 'docs_nav_new', text: 'Nuevo documento'), 
          LocalizableModel(key: 'docs_title', text: 'Título del documento'), 
          LocalizableModel(key: 'docs_upload', text: 'Inserta tu documento aquí'), 
      
          //FINANCEIRO
          LocalizableModel(key: 'financeiro_inadimplente', text: 'Moroso'), 
          LocalizableModel(key: 'financeiro_inadimplentes', text: 'Morosos'), 
          LocalizableModel(key: 'financeiro_meses_aberto', text: 'MESES ABIERTOS'), 
          LocalizableModel(key: 'financeiro_nav_relatorio', text: 'Resumen'), 
          LocalizableModel(key: 'financeiro_nav_resultado', text: 'RESULTADO'),
          LocalizableModel(key: 'financeiro_total_receitas', text: 'Ingresos totales:'), 
          LocalizableModel(key: 'financeiro_total_despesas', text: 'Gastos Totales:'), 
          LocalizableModel(key: 'financeiro_resultado_periodo', text: 'Resultado del periodo:'), 
          LocalizableModel(key: 'financeiro_nav_arrecadacoes', text: 'Colecciones'),
          LocalizableModel(key: 'financeiro_sem_lancamentos', text: 'No hay lanzamientos en el periodo.'),
          LocalizableModel(key: 'financeiro_nenhum_inadimplente', text: 'No se encontraron morosos'),
          LocalizableModel(key: 'financeiro_despesa', text: 'Gastos'), 
          LocalizableModel(key: 'financeiro_despesas', text: 'Gastos'), 
          LocalizableModel(key: 'financeiro_arrecadacoes', text: 'Colecciones'),  
          LocalizableModel(key: 'financeiro_receita_outras', text: 'Receta - Otros'),  
          LocalizableModel(key: 'financeiro_receita', text: 'Ganancia'), 
          LocalizableModel(key: 'financeiro_recebedor', text: 'RECEPTOR'), 
          LocalizableModel(key: 'financeiro_fornecedor', text: 'Proveedor'), 
          LocalizableModel(key: 'financeiro_categoria', text: 'Categoría'), 
          LocalizableModel(key: 'financeiro_dt_pag', text: 'Fecha de pago'), 
          LocalizableModel(key: 'financeiro_valores', text: 'VALORES'), 
          LocalizableModel(key: 'financeiro_valor', text: 'Valor'), 
          LocalizableModel(key: 'financeiro_forma_pagamento', text: 'Método de pago'), 
          LocalizableModel(key: 'financeiro_parcelas', text: 'Número de cuotas'), 
          LocalizableModel(key: 'financeiro_conta_debito', text: 'cuenta de débito'),
          LocalizableModel(key: 'financeiro_desc_comprovante', text: 'DESCRIPCIÓN Y PRUEBA (OPCIONAL)'), 
          LocalizableModel(key: 'financeiro_anexo_comprovante', text: 'Haga clic aquí y adjunte una foto del recibo o NF'), 
          LocalizableModel(key: 'financeiro_arrecadacao', text: 'Recopilación'), 
          LocalizableModel(key: 'financeiro_lancamento', text: 'Lanzamiento'), 
          LocalizableModel(key: 'financeiro_mes_referencia', text: 'Mes de referencia'), 
          LocalizableModel(key: 'financeiro_data_vencimento', text: 'Fecha de expiración'), 
          LocalizableModel(key: 'financeiro_pagador', text: 'Pagador'), 
          LocalizableModel(key: 'financeiro_tipo', text: 'Tipo'), 
          LocalizableModel(key: 'financeiro_forn_cliente', text: 'Proveedor / Cliente'), 
          LocalizableModel(key: 'financeiro_data_recebimento', text: 'fecha de recibo'),
          LocalizableModel(key: 'financeiro_conta_bancaria', text: 'Cuenta bancaria'),
          LocalizableModel(key: 'financeiro_nav_edit', text: 'Editar versión'),
          LocalizableModel(key: 'financeiro_nav_new', text: 'Nuevo lanzamiento'),
          LocalizableModel(key: 'financeiro_saldo_dia', text: 'Saldo del día'),
      
          LocalizableModel(key: 'financeiro_categ_consumo', text: 'Consumo'),
          LocalizableModel(key: 'financeiro_categ_manutencao', text: 'Mantenimiento'),
          LocalizableModel(key: 'financeiro_categ_pessoal', text: 'Tipo'),
          LocalizableModel(key: 'financeiro_categ_impostos', text: 'Impuestos'),
          LocalizableModel(key: 'financeiro_categ_adms', text: 'Administrativo'),
          LocalizableModel(key: 'financeiro_categ_outras', text: 'Otros'),
      
          LocalizableModel(key: 'financeiro_conta_corrente', text: 'Cuenta corriente'),
          LocalizableModel(key: 'financeiro_conta_poupanca', text: 'Ahorros'),
          LocalizableModel(key: 'financeiro_conta_outra', text: 'Otro'),
      
          LocalizableModel(key: 'financeiro_dinheiro', text: 'Dinero'),
          LocalizableModel(key: 'financeiro_pix', text: 'Foto'),
          LocalizableModel(key: 'financeiro_boleto', text: 'Boleto'),
          LocalizableModel(key: 'financeiro_cartao_credito', text: 'Tarjeta de crédito'),
          LocalizableModel(key: 'financeiro_cartao_debito', text: 'Tarjeta de débito'),
          LocalizableModel(key: 'financeiro_outra', text: 'Otro'),
      
      
          //FUNCIONÁRIO
          LocalizableModel(key: 'funcionario_nav_edit', text: 'Editar empleado'), 
          LocalizableModel(key: 'funcionario_nav_new', text: 'Registrar empleado'), 
          LocalizableModel(key: 'funcionario_infos_pessoais', text: 'INFORMACIÓN PERSONAL'), 
          LocalizableModel(key: 'funcionario_infos_funcao', text: 'INFORMACIÓN RELACIONADA CON LA FUNCIÓN'), 
          LocalizableModel(key: 'funcionario_funcao', text: 'Función'), 
          LocalizableModel(key: 'funcionario_horario_trabalho', text: 'Horas de trabajo'), 
          LocalizableModel(key: 'funcionario_permissoes', text: 'PERMISOS DENTRO DE LA APLICACIÓN'),     
          LocalizableModel(key: 'funcionario_permissoes_sobre', text: '¡Al habilitar un permiso, le estarás dando a este empleado la autonomía de administrador del menú elegido!'),
          LocalizableModel(key: 'funcionario_infos_extra', text: 'INFORMACIÓN ADICIONAL (OPCIONAL)'),
          LocalizableModel(key: 'funcionario_infos_extra_1', text: 'Información adicional 1'),
          LocalizableModel(key: 'funcionario_infos_extra_2', text: 'Información adicional 2'),
          LocalizableModel(key: 'funcionario_infos_extra_3', text: 'Información adicional 3'),
          LocalizableModel(key: 'funcionario_infos_extra_4', text: 'Información adicional 4'),
          LocalizableModel(key: 'funcionario_infos_acesso', text: 'ACCEDER A LA INFORMACIÓN'),
          LocalizableModel(key: 'funcionario_senha', text: 'Haga clic en Contraseña de acceso'),
      
          //MORADORES
          LocalizableModel(key: 'moradores_empty', text: 'No hay residentes registrados por el momento.'), 
      
          //APARTAMENTO
          LocalizableModel(key: 'apto_desc', text: 'Para registrar un nuevo apartamento, ingrese los datos a continuación:'), 
          LocalizableModel(key: 'apto_fracao', text: 'Fracción ideal'), 
          LocalizableModel(key: 'apto_proprietarios', text: 'Propietarios:'), 
          LocalizableModel(key: 'apto_inquilinos', text: 'Inquilinos:'), 
          LocalizableModel(key: 'apto_usuario_criado_msg', text: 'Usuário criado!\nInforme que a senha padrão será o número do documento e que ao entrar na conta a senha poderá ser alterada.'), 
          
          //MUDANCA
          LocalizableModel(key: 'mudanca_nav', text: 'Cambiar horarios'),  
          LocalizableModel(key: 'mudanca_nav_edit', text: 'Editar cambio'),
          LocalizableModel(key: 'mudanca_nav_new', text: 'Solicitar cambio'),
          LocalizableModel(key: 'mudanca_pendente_aprovacao', text: 'Este item não está mais pendente aprovação.\nVocê não pode mais editá-lo.'), 
          LocalizableModel(key: 'mudanca_selecione_apto', text: 'ASeleccione el apartamento deseado'),   
          LocalizableModel(key: 'mudanca_infos_mudanca', text: 'INFORMACIÓN SOBRE EL CAMBIO'),   
          LocalizableModel(key: 'mudanca_motivo_recusa', text: 'Motivo del rechazo'),   
      
          //OCORRÊNCIA
          LocalizableModel(key: 'ocorrencia_sobre', text: 'ACERCA DEL OCURRENCIA'),  
          LocalizableModel(key: 'ocorrencia_respondido', text: 'Respondido en'),  
          LocalizableModel(key: 'ocorrencia_resposta', text: 'Escribe la respuesta al residente aquí.'),  
          LocalizableModel(key: 'ocorrencia_status', text: 'Seleccionar estado:'), 
          LocalizableModel(key: 'ocorrencia_abertura_nav', text: 'Apertura de sucesos'), 
          LocalizableModel(key: 'ocorrencia_erro_tipo', text: '¡Seleccione el tipo de ocurrencia!'),     
          LocalizableModel(key: 'ocorrencia_nav_edit', text: '¡Seleccione el tipo de ocurrencia!'),   
          LocalizableModel(key: 'ocorrencia_tipo', text: 'Tipo de ocurrencia'),   
      
          //PRESTADORES
          LocalizableModel(key: 'prestador_eletricista', text: '⚡ electricista'),  
          LocalizableModel(key: 'prestador_hidraulica', text: '🚰 Hidráulica / Plomería'),  
          LocalizableModel(key: 'prestador_pintor', text: '🎨 Pintor'),  
          LocalizableModel(key: 'prestador_pedreiro', text: '🏚 Albañil'),  
          LocalizableModel(key: 'prestador_limpeza', text: '🧹 Limpieza'),  
          LocalizableModel(key: 'prestador_dedetizacao', text: '🐜 Control de plagas'),  
          LocalizableModel(key: 'prestador_nav_edit', text: 'Editar proveedor de servicios'),
          LocalizableModel(key: 'prestador_nav_new', text: 'Registrar proveedor de servicios'),
          LocalizableModel(key: 'prestador_infos', text: 'INFORMACIÓN DEL PROVEEDOR'),
          LocalizableModel(key: 'prestador_funcoes', text: 'FUNCIONES'),
          LocalizableModel(key: 'prestador_selecione_categoria', text:  'Seleccione categoría(s):'),
          LocalizableModel(key: 'prestador_categoria_desc', text: 'O ingrese otra(s) categoría(s): (separadas por coma)'),
      
          //VISITANTES
          LocalizableModel(key: 'visitantes_list', text: 'Lista de visitantes'),  
          LocalizableModel(key: 'visitantes_nav_new', text: 'Registrar nuevo visitante'),
          LocalizableModel(key: 'visitantes_nav_edit', text: 'Editar visitante'),
          LocalizableModel(key: 'visitantes_infos', text: 'INFORMACIÓN SOBRE LA VISITA'),
          LocalizableModel(key: 'visitantes_data_hora_inicio', text: 'Fecha y hora de inicio del lanzamiento'),
          LocalizableModel(key: 'visitantes_data_hora_termino', text: 'Fecha y hora de finalización del lanzamiento'),
          LocalizableModel(key: 'visitante', text: 'Visitante'),
          LocalizableModel(key: 'prestador', text: 'Proveedor'),
          LocalizableModel(key: 'visitante_prestador_servico', text: 'Proveedor de servicios'),
          LocalizableModel(key: 'visitante_erro_bloco', text: '¡Primero selecciona el bloque!'),

          //OUTROS
          LocalizableModel(key: 'pessoas', text: 'Gente'),
          LocalizableModel(key: 'capacidade_indeterminada', text: 'Capacidad indeterminada'),
          LocalizableModel(key: 'pagos', text: 'Pagado'),
          LocalizableModel(key: 'escolha_opcao_desejada', text: 'Elija la opción deseada'),
          LocalizableModel(key: 'ciente', text: 'Consciente'),
          LocalizableModel(key: 'solucionado', text: 'Resuelto'),
          LocalizableModel(key: 'urgente', text: 'Urgente'),
          LocalizableModel(key: 'manutencao', text: 'Mantenimiento'),
          LocalizableModel(key: 'outros', text: 'Otros'),
          LocalizableModel(key: 'primeiro_documento', text: 'Primer documento'),
          LocalizableModel(key: 'link_erro', text: 'No se puede abrir el enlace'),
          LocalizableModel(key: 'invalid_data', text: '¡Se ingresó una fecha no válida!'),
          LocalizableModel(key: 'invalid_hora', text: '¡Se ingresó hora no válida!'),
          LocalizableModel(key: 'senhas_nao_conferem', text: 'Las contraseñas ingresadas no coinciden.'),
          LocalizableModel(key: 'senha_minimo_caracteres', text: 'La contraseña debe contener al menos 6 caracteres.'),
          LocalizableModel(key: 'libere_funcoes', text: 'Libere las funciones deseadas'),
          LocalizableModel(key: 'editar_manutencao', text: 'Editar mantenimiento'),
          LocalizableModel(key: 'nova_manutencao', text: 'Nuevo mantenimiento'),
          LocalizableModel(key: 'gerar_alerta', text: 'Generan alerta para residentes'),

          LocalizableModel(key: 'moeda', text: 'Acuñar'),
          LocalizableModel(key: 'moeda_real', text: 'R\$ (Real Brasileño)'),
          LocalizableModel(key: 'moeda_dolar_americano', text: 'US\$ (Dólar Estadounidense)'),
          LocalizableModel(key: 'moeda_euro', text: '€ (Euro)'),
          LocalizableModel(key: 'moeda_libra', text: '£ (Libra)'),
          LocalizableModel(key: 'moeda_peso_mexicano', text: 'Mex\$ (Pesos Mexicanos)'),
          LocalizableModel(key: 'moeda_generico', text: '\$'),

          LocalizableModel(key: 'assinatura_semestral', text: 'Semestral'),
          LocalizableModel(key: 'assinatura_anual', text: 'Anual'),

          LocalizableModel(key: 'meus_condominios', text: 'Mis Condominios'),
      
        ];
      
      }
