import 'package:click/utils/localizable/localizable.dart';

class Localizable_PtPt {

  final List<LocalizableModel> strings = [
    // Idioma
    LocalizableModel(key: 'language_idioma', text: 'Linguagem'),
    LocalizableModel(key: 'language_pt_br', text: 'Brasil português'),
    LocalizableModel(key: 'language_pt_pt', text: 'Português Portugal'),
    LocalizableModel(key: 'language_en', text: 'Inglês'),
    LocalizableModel(key: 'language_es', text: 'Espanhol'),
    LocalizableModel(key: 'language_al', text: 'Alemão'),

    // Data
    LocalizableModel(key: 'data_informar', text: 'Informe na data pretendida.'),
    LocalizableModel(key: 'data_selecionar_horario', text: 'Selecione o horário pretendido.'),
    LocalizableModel(key: 'data_das', text: 'Das'),    
    LocalizableModel(key: 'data_as', text: 'Ás'),    
    LocalizableModel(key: 'data_e_hora', text: 'Data e hora'),
    LocalizableModel(key: 'dia_e_hora', text: 'Dia e hora'),
    LocalizableModel(key: 'dia', text: 'Dia'),
    LocalizableModel(key: 'dias', text: 'dias'),
    LocalizableModel(key: 'data', text: 'Dados'),
    LocalizableModel(key: 'datas', text: 'Dados'),
    LocalizableModel(key: 'hora', text: 'Hora'),
    LocalizableModel(key: 'data_inicio', text: 'Data de início'),
    LocalizableModel(key: 'hora_inicio', text: 'Hora de início'),
    LocalizableModel(key: 'data_termino', text: 'Data de mandato'),
    LocalizableModel(key: 'hora_termino', text: 'Hora de término'),
    LocalizableModel(key: 'data_hora_criacao', text: 'DADOS E HORA DA CRIAÇÃO'),
    LocalizableModel(key: 'data_hora_inicio', text: 'Data e hora de início'),
    LocalizableModel(key: 'segunda', text: 'Segundo'),
    LocalizableModel(key: 'terca', text: 'Terça-feira'),
    LocalizableModel(key: 'quarta', text: 'Quarto'),
    LocalizableModel(key: 'quinta', text: 'Quinto'),
    LocalizableModel(key: 'sexta', text: 'Sexto'),
    LocalizableModel(key: 'sabado', text: 'Sábado'),
    LocalizableModel(key: 'domingo', text: 'Domingo'),

    // Modal Select Month
    LocalizableModel(key: 'modal_select_month_btn_ok', text: 'OK'),
    LocalizableModel(key: 'modal_select_month_btn_cancel', text: 'Cancelar'),

    //TextField
    LocalizableModel(key: 'textfield_long_placeholder', text: 'Escreva aqui...'),
    LocalizableModel(key: 'textfield_short_placeholder', text: 'Guarde a sua mensagem...'),

    //Label
    LocalizableModel(key: 'label_to', text: 'Para:'),
    LocalizableModel(key: 'label_of', text: 'de'),
    LocalizableModel(key: 'label_until', text: 'comeu'),
    LocalizableModel(key: 'ola', text: 'Olá'),
    LocalizableModel(key: 'sindico', text: 'Receptor'),
    LocalizableModel(key: 'morador', text: 'Habitante'),
    LocalizableModel(key: 'funcionario', text: 'Oficial'),
    LocalizableModel(key: 'email', text: 'E-mail'),
    LocalizableModel(key: 'senha', text: 'Senha'),
    LocalizableModel(key: 'vesaoApp', text: 'Versão:'),
    LocalizableModel(key: 'nome', text: 'Nome'),
    LocalizableModel(key: 'user_nome_completo', text: 'Nome Completo'),
    LocalizableModel(key: 'user_documento', text: 'Documento de Identificação'),
    LocalizableModel(key: 'data_nascimento', text: 'Data de nascimento'),
    LocalizableModel(key: 'email', text: 'E-mail'),
    LocalizableModel(key: 'telefone', text: 'Telefone'),
    LocalizableModel(key: 'senha', text: 'Senha'),
    LocalizableModel(key: 'editar_infos', text: 'Editar informações'),
    LocalizableModel(key: 'label_exclusao', text: 'Exclusão!'),

    LocalizableModel(key: 'lb_areas_sociais', text: 'Áreas Sociais'),
    LocalizableModel(key: 'lb_area_social', text: 'Área Social'),
    LocalizableModel(key: 'lb_financeiro', text: 'Financeiro'),
    LocalizableModel(key: 'lb_assembleia_votacoes', text: 'Assembleias e Votações'),
    LocalizableModel(key: 'lb_assembleias', text: 'Montagens'),
    LocalizableModel(key: 'lb_assembleia', text: 'Conjunto'),
    LocalizableModel(key: 'lb_votacoes', text: 'Votação'),
    LocalizableModel(key: 'lb_enquetes', text: 'Enquetes'),
    LocalizableModel(key: 'lb_comunicados', text: 'Anúncios'),
    LocalizableModel(key: 'lb_comunicado', text: 'Liberar'),
    LocalizableModel(key: 'lb_ocorrencias', text: 'Ocorrências'),
    LocalizableModel(key: 'lb_ocorrencia', text: 'Ocorrência'),
    LocalizableModel(key: 'lb_funcionarios', text: 'Funcionários'),
    LocalizableModel(key: 'lb_funcionarios_condominio', text: 'Funcionários do condomínio'),
    LocalizableModel(key: 'lb_manut_programadas', text: 'Manutenção Programada'),
    LocalizableModel(key: 'lb_manut_programada', text: 'Manutenção Programada'),
    LocalizableModel(key: 'lb_prestadores_servico', text: 'Prestadores de serviços'),
    LocalizableModel(key: 'lb_agendar_mudanca', text: 'Agendar mudança'),
    LocalizableModel(key: 'lb_cadastrar_visitante', text: 'Visitante Cadastral'),
    LocalizableModel(key: 'lb_apartamentos', text: 'Apartamentos'),
    LocalizableModel(key: 'lb_apartamento', text: 'Apartamento'),
    LocalizableModel(key: 'lb_docs', text: 'Documentos'),
    LocalizableModel(key: 'lb_apto', text: 'Adequado'),
    LocalizableModel(key: 'lb_ref', text: 'Ref.'),
    LocalizableModel(key: 'lb_saldo', text: 'Equilíbrio'),
    LocalizableModel(key: 'lb_status', text: 'Status'),
    LocalizableModel(key: 'lb_categorias', text: 'Categorias'),
    LocalizableModel(key: 'lb_categoria', text: 'Categoria'),
    LocalizableModel(key: 'lb_anexos', text: 'Anexos'),
    LocalizableModel(key: 'lb_insira_fotos', text: 'Coloque aqui as suas fotos'),
    LocalizableModel(key: 'lb_tipo', text: 'Cara'),
    LocalizableModel(key: 'lb_resposta', text: 'Responder'),
    LocalizableModel(key: 'lb_todos', text: 'Todos'),
    LocalizableModel(key: 'lb_pendentes', text: 'Pendentes'),
    LocalizableModel(key: 'lb_buscar', text: 'Procurar'),
    LocalizableModel(key: 'lb_aviso', text: 'Aviso'),
    LocalizableModel(key: 'lb_ultima_atualizacao', text: 'Última atualização'),
    LocalizableModel(key: 'lb_ciente', text: 'Cliente'),
    LocalizableModel(key: 'lb_pendente', text: 'Pendente'),
    LocalizableModel(key: 'lb_aprovado', text: 'Aprovado'),
    LocalizableModel(key: 'lb_recusado', text: 'Recusado'),
    LocalizableModel(key: 'lb_solucionado', text: 'Resolvido'),
    LocalizableModel(key: 'lb_nao_informado', text: 'Não informado'),
    LocalizableModel(key: 'lb_aceitar', text: 'Óleo'),
    LocalizableModel(key: 'lb_recusar', text: 'recusar'),
    LocalizableModel(key: 'lb_finalizar', text: 'Terminar'),

    LocalizableModel(key: 'lb_titulo', text: 'Qualificação'),
    LocalizableModel(key: 'lb_descricao', text: 'Descrição'),
    LocalizableModel(key: 'lb_descricao_opcional', text: 'DESCRIÇÃO (OPCIONAL)'),
    LocalizableModel(key: 'lb_observacoes_opcional', text: 'OBSERVAÇÕES (OPCIONAL)'),
    LocalizableModel(key: 'lb_observacoes', text: 'Observações'),    
    LocalizableModel(key: 'lb_inicio', text: 'Começar'),
    LocalizableModel(key: 'lb_termino', text: 'Prazo'),
    LocalizableModel(key: 'lb_autorizado_por', text: 'Autorizado por'),

    LocalizableModel(key: 'lb_infos_apto', text: 'INFORMAÇÕES DO APARTAMENTO'),
    LocalizableModel(key: 'lb_bloco', text: 'Bloco'),

    LocalizableModel(key: 'lb_li_concordo', text: 'Concordo com as regras'),
    LocalizableModel(key: 'lb_complementos', text: 'Acessórios'),

    LocalizableModel(key: 'lb_logout', text: 'Sair'),

    //Button
    LocalizableModel(key: 'btn_save', text: 'SALVAR'),
    LocalizableModel(key: 'btn_delete', text: 'Excluir'),
    LocalizableModel(key: 'btn_enviar', text: 'ENVIAR'),
    LocalizableModel(key: 'btn_proximo', text: 'PRÓXIMO'),
    LocalizableModel(key: 'btn_anterior', text: 'ANTIGO'),

    //UPLOAD
    LocalizableModel(key: 'upload_max_number', text: 'Número máximo de documentos elegíveis'),

    // ALERT
    LocalizableModel(key: 'alert', text: 'Alerta!'),
    LocalizableModel(key: 'alert_alert', text: 'Aviso'),
    LocalizableModel(key: 'alert_success', text: 'Sucesso!'),
    LocalizableModel(key: 'alert_error', text: 'Errado!'),
    LocalizableModel(key: 'alert_ops', text: 'Ops!'),
    LocalizableModel(key: 'alert_invalid_value', text: 'Valor introduzido inválido!'),
    LocalizableModel(key: 'alert_sim', text: 'Sim'),
    LocalizableModel(key: 'alert_nao', text: 'Não'),
    LocalizableModel(key: 'alert_em_breve', text: 'Em Breve!'),
    LocalizableModel(key: 'alert_em_breve_description', text: 'Estamos a trabalhar para disponibilizar este serviço o mais rápido possível.'),    
    LocalizableModel(key: 'alert_delete_description', text: 'Tem a certeza de que pretende eliminar este item permanentemente?'),
    LocalizableModel(key: 'alert_cancel_description', text: 'Tem a certeza do que pretende fazer ou cancelar este artigo?'),
    LocalizableModel(key: 'alert_photo_choice', text: 'Quer tirar uma fotografia agora ou selecionar uma fotografia da galeria?'),
    LocalizableModel(key: 'alert_doc_choice', text: 'Pretende anexar um documento ou uma imagem?'),
    LocalizableModel(key: 'alert_photo_camera', text: 'Câmera'),
    LocalizableModel(key: 'alert_photo_galeria', text: 'Galeria'),
    LocalizableModel(key: 'alert_photo_image', text: 'Imagem'),
    LocalizableModel(key: 'alert_document', text: 'Documento'),
    LocalizableModel(key: 'alert_generic_error', text: 'Ocorreu um erro, tente novamente!'),
    LocalizableModel(key: 'alert_list_empty_generic', text: 'Nenhum registo encontrado!'),
    LocalizableModel(key: 'alert_upload_image', text: 'Insira uma imagem.'),
    LocalizableModel(key: 'alert_dados_alterados', text: 'Dados alterados com sucesso!'),
    LocalizableModel(key: 'alert_nenhum_bloco', text: 'Nenhum bloco localizado!\nPrimeiro registe as unidades no menu "Apartamentos".'),
    LocalizableModel(key: 'alert_nenhum_apto', text: 'Nenhum apartamento localizado!\no Primeiro registe as unidades no menu "Apartamentos" no ecrã inicial.'),

    // ACESSO
    LocalizableModel(key: 'sou_sindico', text: 'SOU TRUSTEE'),
    LocalizableModel(key: 'sou_morador', text: 'SOU DORADOR'),
    LocalizableModel(key: 'sou_funcionario', text: 'SOU FUNCIONÁRIO'),
    LocalizableModel(key: 'view_hello_text', text: 'Vamos registar o seu primeiro condomínio?'),
    LocalizableModel(key: 'vamos_cadastrar', text: 'vamos registar'),
    LocalizableModel(key: 'possuo_cadastro', text: 'já possuo registo'),
    
    // LOGIN
    LocalizableModel(key: 'login_btn_entrar', text: 'DIGITAR'),
    LocalizableModel(key: 'login_btn_esqueci_senha', text: 'Esboçar uma palavra-passe?'),
    LocalizableModel(key: 'login_error', text: 'Login ou Palavra-passe incorreta. Tente novamente'),

    // ESQUECI A SENHA
    LocalizableModel(key: 'esqueci_senha_nav', text: 'Esqueci-me da senha'),
    LocalizableModel(key: 'esqueci_senha_title', text: 'Esboçar uma palavra-passe?'),
    LocalizableModel(key: 'esqueci_senha_description', text: 'Não se preocupe, preencha o seu e-mail abaixo e enviaremos um link de recuperação.'),
    LocalizableModel(key: 'esqueci_senha_send_description', text: 'O link de recuperação foi enviado para o seu email.'),    

    // CADASTRO SÍNDICO
    LocalizableModel(key: 'signup_nav_sindico', text: 'Registo de Administradores'),
    LocalizableModel(key: 'sindico_nav_edit', text: 'Editar dados'),
    LocalizableModel(key: 'signup_success', text: 'Registo realizado com sucesso!'),
    LocalizableModel(key: 'signup_erro_dt_nascimento', text: 'Data de nascimento inválida!'),
    LocalizableModel(key: 'signup_infos_contato', text: 'INFORMAÇÃO DE CONTATO'),

    // CADASTRO CONDOMINIO
    LocalizableModel(key: 'signup_cond_nav', text: 'Registo Condomínio'),
    LocalizableModel(key: 'condominio_nav_edit', text: 'Editar Condomínio'),
    LocalizableModel(key: 'condominio_nav_edit_address', text: 'Editar Condomínio'),
    LocalizableModel(key: 'signup_cond_error_nome', text: 'Informe ou nome do condomínio.'),
    LocalizableModel(key: 'signup_cond_error_doc', text: 'Relatório ou documento de identificação do condomínio.'),
    LocalizableModel(key: 'signup_cond_error_subsindico', text: 'Relatório ou nome do subadministrador.'),
    LocalizableModel(key: 'signup_cond_error_dt_inicio_mandato', text: 'Relatório sobre a data de início do mandato'),
    LocalizableModel(key: 'signup_cond_error_dt_fim_mandato', text: 'Relatório no final do mandato.'),
    LocalizableModel(key: 'signup_cond_error_dt_anterior', text: 'Data de fim anterior à data de início.'), 
    LocalizableModel(key: 'signup_cond_error_cep', text: 'Relatório ou código postal.'),  
    LocalizableModel(key: 'signup_cond_error_pais', text: 'Relatório ou País.'),  
    LocalizableModel(key: 'signup_cond_error_estado', text: 'Relatório ou Estado.'),  
    LocalizableModel(key: 'signup_cond_error_cidade', text: 'Reporte à cidade.'),  
    LocalizableModel(key: 'signup_cond_error_bairro', text: 'Reportagem ou Bairro.'),  
    LocalizableModel(key: 'signup_cond_error_rua', text: 'Relatório ou Rua.'),  
    LocalizableModel(key: 'signup_cond_error_numero', text: 'Relatório ou Número.'),  

    LocalizableModel(key: 'signup_cond_nome', text: 'Nome do condomínio'),
    LocalizableModel(key: 'signup_cond_subsindico_nome', text: 'Nome do subadministrador'),
    LocalizableModel(key: 'signup_cond_ini_mandato', text: 'Data de início do mandato'),
    LocalizableModel(key: 'signup_cond_fim_mandato', text: 'Data do fim do mandato'),
    LocalizableModel(key: 'signup_cond_cep', text: 'CEP'),
    LocalizableModel(key: 'signup_cond_pais', text: 'País'),  
    LocalizableModel(key: 'signup_cond_uf', text: 'UFA'),  
    LocalizableModel(key: 'signup_cond_cidade', text: 'Cidade'),  
    LocalizableModel(key: 'signup_cond_bairro', text: 'Bairro'),  
    LocalizableModel(key: 'signup_cond_rua', text: 'rua'),  
    LocalizableModel(key: 'signup_cond_numero', text: 'Número'),  
    LocalizableModel(key: 'signup_cond_complemento', text: 'Complemento'),  

    LocalizableModel(key: 'signup_cond_valor_total', text: 'Valor Total:'),  
    LocalizableModel(key: 'signup_cond_valor_mensal', text: 'R\$ 35,99 / mês'), 
    LocalizableModel(key: 'signup_cond_dias_gratuitos', text: 'Aproveite os seus 45 dias grátis!'), 
    LocalizableModel(key: 'signup_cond_cancele_label', text: 'Cancele quando quiser!'), 

    LocalizableModel(key: 'signup_cond_sucesso', text: 'Condomínio Registado com SUCESSO'), 

    LocalizableModel(key: 'cond_confirm_delete', text: 'Tem a certeza que deseja excluir este condomínio permanentemente?'), 
    LocalizableModel(key: 'signup_confirm_delete', text: 'Tem a certeza de que pretende eliminar a sua conta permanentemente?'), 

    LocalizableModel(key: 'condominio_edit_dados', text: 'Editar os dados do condomínio'),
    LocalizableModel(key: 'condominio_edit_endereco', text: 'Atualizar alisamento'),
    
  
    //MANUTENCAO PROGRAMADA
    LocalizableModel(key: 'manut_edit_nav', text: 'Editar Compromisso da Agenda'), 
    LocalizableModel(key: 'manut_signup_nav', text: 'Novo compromisso na agenda'), 
    LocalizableModel(key: 'manut_about', text: 'SOBRE OU COMPROMISSO'), 
    LocalizableModel(key: 'manut_nav', text: 'Solicitações de manutenção'), 
    LocalizableModel(key: 'manut_edit', text: 'Editar solicitação'), 
    LocalizableModel(key: 'manut_new', text: 'Novo aplicativo'), 
    


    //AREA SOCIAL
    LocalizableModel(key: 'area_social_precisa_agendamento', text: 'Agenda necessária'), 
    LocalizableModel(key: 'area_social_precisa_autorizacao', text: 'Autorização necessária'), 
    LocalizableModel(key: 'area_social_precisa_pagamento', text: 'Pagamento necessário'), 
    LocalizableModel(key: 'area_social_agendamentos', text: 'Agendas'), 
    LocalizableModel(key: 'area_social_meus_agendamentos', text: 'As minhas agendas'), 
    LocalizableModel(key: 'area_social_nenhum_agendamento', text: 'Não tem agendas'), 
    LocalizableModel(key: 'area_social_nav_new', text: 'Nova Área Social'), 
    LocalizableModel(key: 'area_social_dados_iniciais', text: 'DADOS INICIAIS'), 
    LocalizableModel(key: 'area_social_capacidade_maxima', text: 'Capacidade máxima'), 
    LocalizableModel(key: 'area_social_capacidade_vazio', text: 'A caixa vazia não tem capacidade máxima'), 
    LocalizableModel(key: 'area_social_obrigatoriedades', text: 'OBRIGATÓRIOS'), 
    LocalizableModel(key: 'area_social_novo_horario', text: 'Nova programação'), 
    LocalizableModel(key: 'area_social_erro_normas', text: 'Lubrifique de acordo com os regulamentos antes de continuar.'), 
    LocalizableModel(key: 'area_social_nav_edit_reserva', text: 'Editar reserva'), 
    LocalizableModel(key: 'area_social_nav_reservar', text: 'Reserva'), 
    LocalizableModel(key: 'area_social_data_reserva', text: 'Data da reserva:'), 
    LocalizableModel(key: 'area_social_hora_reserva', text: 'Horário da reserva:'), 
    LocalizableModel(key: 'area_social_reservado', text: 'Reservado:'), 

    //ASSEMBLEIA
    LocalizableModel(key: 'assembleia_infos', text: 'INFORMAÇÕES DA ASSEMBLEIA'), 
    LocalizableModel(key: 'assembleia_local', text: 'Local'), 
    LocalizableModel(key: 'assembleia_nav_edit', text: 'Editar montagem'), 
    LocalizableModel(key: 'assembleia_nav_new', text: 'Nova Assembleia'), 
    LocalizableModel(key: 'assembleia_data_local', text: 'SOBRE A DADOS E O LOCAL'), 
    LocalizableModel(key: 'assembleia_link_online', text: 'Link (caso para montagem seja online)'), 
    LocalizableModel(key: 'assembleia_arquivos', text: 'Insira os arquivos aqui\n(Apenas formato .PDF)'), 

    LocalizableModel(key: 'assembleia_alert_ata', text: 'Insira ATA para finalizar esta Assembleia'), 
    LocalizableModel(key: 'assembleia_encerrada', text: 'A assembléia foi encerrada!\nA ATA se encontra disponível para consulta no menu "Docs" do seu condomínio.'), 
    LocalizableModel(key: 'assembleia_finalize_upload', text: 'Termine a assembéia. \nFaça o upload da Ata'), 
    LocalizableModel(key: 'assembleia_upload_ata', text: 'Clique aqui para a Ata da Assembleia'), 
    

    //VOTACAO
    LocalizableModel(key: 'votacao_signup_informe_opcoes', text: 'Introduza as opções de voto.'), 
    LocalizableModel(key: 'votacao_signup_nav', text: 'Aumentar a votação'), 
    LocalizableModel(key: 'votacao_signup_infos', text: 'INFORMAÇÕES DE VOTO'), 
    LocalizableModel(key: 'votacao_signup_dt_encerramento', text: 'Data de bloqueio'), 
    LocalizableModel(key: 'votacao_opcoes', text: 'OPÇÕES'), 
    LocalizableModel(key: 'votacao_opcao', text: 'Opção'), 
    LocalizableModel(key: 'votacao_confirm_delete', text: 'Tem a certeza de que pretende terminar a votação antes da data de fim prevista?'), 
    LocalizableModel(key: 'votacao_enquete', text: 'Pacote'), 
    LocalizableModel(key: 'votacao_infos', text: 'INFORMAÇÕES DA ENQUETE'), 
    LocalizableModel(key: 'votacao_agendado', text: 'Agendado'), 
    LocalizableModel(key: 'votacao_andamento', text: 'Em curso'), 
    LocalizableModel(key: 'votacao_finalizado', text: 'Finalizado'), 
    LocalizableModel(key: 'votacao_finalizar', text: 'Terminar a votação?'), 
    LocalizableModel(key: 'votacao_fora_periodo', text: 'Votação fora do período permitido.'), 

    //COMUNICADO
    LocalizableModel(key: 'comunicado_nav_edit', text: 'Editar declaração'), 
    LocalizableModel(key: 'comunicado_nav_new', text: 'Novo comunicado'), 
    LocalizableModel(key: 'comunicados_infos', text: 'COMUNICAR INFORMAÇÕES'), 

    //CONFIGURACAO
    LocalizableModel(key: 'config_delete_account_sucesso', text: 'A exclusão da sua conta foi solicitada!\nA equipe responsável lhe comunicará do andamento!'), 
    LocalizableModel(key: 'config_nav', text: 'Configurações'), 
    LocalizableModel(key: 'config_termos_uso', text: 'Termos de Utilização'), 
    LocalizableModel(key: 'config_politica_privacidade', text: 'política de Privacidade'), 
    LocalizableModel(key: 'config_fale_conosco', text: 'Fale eu sei'), 
    LocalizableModel(key: 'config_fale_conosco_descricao', text: 'Entre em contato através do nosso e-mail apontando suas dúvidas e/ou requerimentos.\n\nE não se esqueça de se identificar.\n\ncontato@click-app.co\n'), 
    LocalizableModel(key: 'config_alt_senha', text: 'Alterar palavra-passe'), 
    LocalizableModel(key: 'config_delete_cond', text: 'Excluir condomínio'), 
    LocalizableModel(key: 'config_delete_account', text: 'Apagar a minha conta'), 
    LocalizableModel(key: 'config_nova_senha', text: 'Nova senha'), 
    LocalizableModel(key: 'config_confirm_nova_senha', text: 'Confirme para nova palavra-passe'), 
    LocalizableModel(key: 'config_alt_senha_sucesso', text: 'Palavra-passe alterada com sucesso!'), 

    //ASSINATURA
    LocalizableModel(key: 'assinatura', text: 'Assinatura'), 
    LocalizableModel(key: 'assinatura_morador', text: 'Morador de Assinatura'), 
    LocalizableModel(key: 'assinatura_condominio', text: 'Condomínio Assinatura'), 
    LocalizableModel(key: 'assinatura_erro', text: 'Se cometeu um erro na sua compra, tente novamente.'), 
    LocalizableModel(key: 'assinatura_renovada', text: 'Subscrição renovada com sucesso!'), 
    LocalizableModel(key: 'assinatura_produto_nao_localizado', text: 'Produto não localizado!'), 
    LocalizableModel(key: 'assinatura_erro_loja', text: 'A app não conseguiu comunicar com a loja, tente mais tarde!'), 
    LocalizableModel(key: 'assinatura_tipo_renovacao', text: 'Tipo de renovação:'),
    LocalizableModel(key: 'assinatura_mensal', text: 'Mensal'),
    LocalizableModel(key: 'assinatura_validade', text: 'Validar:'),
    LocalizableModel(key: 'assinatura_dias_restantes', text: 'Dias restantes:'),
    LocalizableModel(key: 'assinatura_venceu', text: 'A sua tarefa está vencida!'),
    LocalizableModel(key: 'assinatura_renove_agora', text: 'Renove já por mais de 30 dias e continue a par de tudo ou do que acontece no seu condomínio!'),    
    LocalizableModel(key: 'assinatura_cond_renove_agora', text: 'Renove já por mais 30 dias e garanta mais tranquilidade na gestão do seu condomínio!'),    
    LocalizableModel(key: 'assinatura_cond_contato_sindico', text: 'Contacte o administrador e informe a renovação do plano App Click.'), 
    LocalizableModel(key: 'assinatura_renove_agora_obs', text: 'Caso ainda faltem três dias, a renovação começará a contar a partir da data de vencimento do plano em vigor.'),    
    LocalizableModel(key: 'assinatura_btn_mensal_morador', text: 'Renovar agora'),    
    LocalizableModel(key: 'assinatura_btn_mensal_cond', text: 'Renovar agora'),    
    LocalizableModel(key: 'assinatura_renovar_depois', text: 'Renovar mais tarde'),  
    LocalizableModel(key: 'assinatura_renovar_7_dias', text: 'Poderá renovar o seu plano faltando 7 dias para a data de vencimento!' ),  
      
    

    //DOCS
    LocalizableModel(key: 'docs_nav_atas', text: 'Atas'), 
    LocalizableModel(key: 'docs_nav', text: 'Documentos'), 
    LocalizableModel(key: 'docs_nav_new', text: 'Novo Documento'), 
    LocalizableModel(key: 'docs_title', text: 'Título do documento'), 
    LocalizableModel(key: 'docs_upload', text: 'Insira aqui o seu documento'), 

    //FINANCEIRO
    LocalizableModel(key: 'financeiro_inadimplente', text: 'Inadimplente'), 
    LocalizableModel(key: 'financeiro_inadimplentes', text: 'Inadimplentes'), 
    LocalizableModel(key: 'financeiro_meses_aberto', text: 'MESES EM ABERTO'), 
    LocalizableModel(key: 'financeiro_nav_relatorio', text: 'Resumo'), 
    LocalizableModel(key: 'financeiro_nav_resultado', text: 'RESULTADO'),
    LocalizableModel(key: 'financeiro_total_receitas', text: 'Receitas totais:'), 
    LocalizableModel(key: 'financeiro_total_despesas', text: 'Despesas totais:'), 
    LocalizableModel(key: 'financeiro_resultado_periodo', text: 'Resultado do período:'), 
    LocalizableModel(key: 'financeiro_nav_arrecadacoes', text: 'Arrecadações'),
    LocalizableModel(key: 'financeiro_sem_lancamentos', text: 'Não há lançamentos no período'),
    LocalizableModel(key: 'financeiro_nenhum_inadimplente', text: 'Nenhum incumpridor encontrado'),
    LocalizableModel(key: 'financeiro_despesa', text: 'Decolar'), 
    LocalizableModel(key: 'financeiro_despesas', text: 'Despesas'), 
    LocalizableModel(key: 'financeiro_arrecadacoes', text: 'Arrecadações'),  
    LocalizableModel(key: 'financeiro_receita_outras', text: 'Receita - Outras'),  
    LocalizableModel(key: 'financeiro_receita', text: 'Receita'), 
    LocalizableModel(key: 'financeiro_recebedor', text: 'RECEPTOR'), 
    LocalizableModel(key: 'financeiro_fornecedor', text: 'Provedor'), 
    LocalizableModel(key: 'financeiro_categoria', text: 'Categoria'), 
    LocalizableModel(key: 'financeiro_dt_pag', text: 'Dados de pagamento'), 
    LocalizableModel(key: 'financeiro_valores', text: 'VALORES'), 
    LocalizableModel(key: 'financeiro_valor', text: 'Valor'), 
    LocalizableModel(key: 'financeiro_forma_pagamento', text: 'Forma de pagamento'), 
    LocalizableModel(key: 'financeiro_parcelas', text: 'Nº de prestações'), 
    LocalizableModel(key: 'financeiro_conta_debito', text: 'Conta de débito'),
    LocalizableModel(key: 'financeiro_desc_comprovante', text: 'DESCRIÇÃO E FORNECIDA (OPCIONAL)'), 
    LocalizableModel(key: 'financeiro_anexo_comprovante', text: 'Clique aqui e anexe uma foto do recibo da sua NF'), 
    LocalizableModel(key: 'financeiro_arrecadacao', text: 'Arrecadação'), 
    LocalizableModel(key: 'financeiro_lancamento', text: 'Lançar'), 
    LocalizableModel(key: 'financeiro_mes_referencia', text: 'Informações de referência'), 
    LocalizableModel(key: 'financeiro_data_vencimento', text: 'data de validade'), 
    LocalizableModel(key: 'financeiro_pagador', text: 'Pagador'), 
    LocalizableModel(key: 'financeiro_tipo', text: 'Cara'), 
    LocalizableModel(key: 'financeiro_forn_cliente', text: 'Fornecedor/Cliente'), 
    LocalizableModel(key: 'financeiro_data_recebimento', text: 'Data de recepção'),
    LocalizableModel(key: 'financeiro_conta_bancaria', text: 'Conta bancária'),
    LocalizableModel(key: 'financeiro_nav_edit', text: 'Editar versão'),
    LocalizableModel(key: 'financeiro_nav_new', text: 'Novo lançamento'),
    LocalizableModel(key: 'financeiro_saldo_dia', text: 'Saldo no dia'),

    LocalizableModel(key: 'financeiro_categ_consumo', text: 'Consumo'),
    LocalizableModel(key: 'financeiro_categ_manutencao', text: 'Manutenção'),
    LocalizableModel(key: 'financeiro_categ_pessoal', text: 'Funcionários'),
    LocalizableModel(key: 'financeiro_categ_impostos', text: 'Impostos'),
    LocalizableModel(key: 'financeiro_categ_adms', text: 'Administrativo'),
    LocalizableModel(key: 'financeiro_categ_outras', text: 'Outras'),

    LocalizableModel(key: 'financeiro_conta_corrente', text: 'Conta corrente'),
    LocalizableModel(key: 'financeiro_conta_poupanca', text: 'Poupança'),
    LocalizableModel(key: 'financeiro_conta_outra', text: 'Outro'),

    LocalizableModel(key: 'financeiro_dinheiro', text: 'Dinheiro'),
    LocalizableModel(key: 'financeiro_pix', text: 'Pix'),
    LocalizableModel(key: 'financeiro_boleto', text: 'Bilhete'),
    LocalizableModel(key: 'financeiro_cartao_credito', text: 'Carta de crédito'),
    LocalizableModel(key: 'financeiro_cartao_debito', text: 'Cartão de Débito'),
    LocalizableModel(key: 'financeiro_outra', text: 'Outro'),


    //FUNCIONÁRIO
    LocalizableModel(key: 'funcionario_nav_edit', text: 'Editar Oficial'), 
    LocalizableModel(key: 'funcionario_nav_new', text: 'Registar Oficial'), 
    LocalizableModel(key: 'funcionario_infos_pessoais', text: 'INFORMAÇÕES PESSOAIS'), 
    LocalizableModel(key: 'funcionario_infos_funcao', text: 'INFORMAÇÃO RELATIVA À FUNÇÃO'), 
    LocalizableModel(key: 'funcionario_funcao', text: 'Função'), 
    LocalizableModel(key: 'funcionario_horario_trabalho', text: 'Horário de trabalho'), 
    LocalizableModel(key: 'funcionario_permissoes', text: 'PERMISSÕES NA APLICAÇÃO'),     
    LocalizableModel(key: 'funcionario_permissoes_sobre', text: 'Ao habilitar o alvará, estará a dar autonomia de curador a esse funcionário no menu escolhido!'),
    LocalizableModel(key: 'funcionario_infos_extra', text: 'INFORMAÇÃO EXTRA (OPCIONAL)'),
    LocalizableModel(key: 'funcionario_infos_extra_1', text: 'Informações extra 1'),
    LocalizableModel(key: 'funcionario_infos_extra_2', text: 'Informações extra 2'),
    LocalizableModel(key: 'funcionario_infos_extra_3', text: 'Informações extra 3'),
    LocalizableModel(key: 'funcionario_infos_extra_4', text: 'Informações extra 4'),
    LocalizableModel(key: 'funcionario_infos_acesso', text: 'INFORMAÇÕES DE ACESSO'),
    LocalizableModel(key: 'funcionario_senha', text: 'Clique em Aceder Senha'),

    //MORADORES
    LocalizableModel(key: 'moradores_empty', text: 'Não existem habitantes cadastrais em nenhum momento'), 

    //APARTAMENTO
    LocalizableModel(key: 'apto_desc', text: 'Para efetuar o registo de um novo apartamento, clique nos dados abaixo:'), 
    LocalizableModel(key: 'apto_fracao', text: 'Fração ideal'), 
    LocalizableModel(key: 'apto_proprietarios', text: 'Proprietários:'), 
    LocalizableModel(key: 'apto_inquilinos', text: 'Inquilinos:'), 
    LocalizableModel(key: 'apto_usuario_criado_msg', text: 'Usuário criado!\nInforme que a senha padrão será o número do documento e que ao entrar na conta a senha poderá ser alterada.'), 
    
    //MUDANCA
    LocalizableModel(key: 'mudanca_nav', text: 'Movendo agendas'),  
    LocalizableModel(key: 'mudanca_nav_edit', text: 'Editar Mudança'),
    LocalizableModel(key: 'mudanca_nav_new', text: 'Solicitar alteração'),
    LocalizableModel(key: 'mudanca_pendente_aprovacao', text: 'Este item não está mais pendente aprovação.\nVocê não pode mais editá-lo.'), 
    LocalizableModel(key: 'mudanca_selecione_apto', text: 'ASelecione o apartamento pretendido'),   
    LocalizableModel(key: 'mudanca_infos_mudanca', text: 'INFORMAÇÃO SOBRE MUDANÇA'),   
    LocalizableModel(key: 'mudanca_motivo_recusa', text: 'Motivo da recusa'),   

    //OCORRÊNCIA
    LocalizableModel(key: 'ocorrencia_sobre', text: 'SOBRE A OCORRÊNCIA'),  
    LocalizableModel(key: 'ocorrencia_respondido', text: 'Respondi'),  
    LocalizableModel(key: 'ocorrencia_resposta', text: 'Escreva aqui para responder pelo morador'),  
    LocalizableModel(key: 'ocorrencia_status', text: 'Selecione ou estado:'), 
    LocalizableModel(key: 'ocorrencia_abertura_nav', text: 'Abertura de Ocorrências'), 
    LocalizableModel(key: 'ocorrencia_erro_tipo', text: 'Selecione o tipo de ocorrência!'),     
    LocalizableModel(key: 'ocorrencia_nav_edit', text: 'Selecione o tipo de ocorrência!'),   
    LocalizableModel(key: 'ocorrencia_tipo', text: 'Tipo de ocorrência'),   

    //PRESTADORES
    LocalizableModel(key: 'prestador_eletricista', text: '⚡ Eletricista'),  
    LocalizableModel(key: 'prestador_hidraulica', text: '🚰 Hidráulica / Canalizador'),  
    LocalizableModel(key: 'prestador_pintor', text: '🎨 Pintor'),  
    LocalizableModel(key: 'prestador_pedreiro', text: '🏚Pedreiro'),  
    LocalizableModel(key: 'prestador_limpeza', text: '🧹 Limpeza'),  
    LocalizableModel(key: 'prestador_dedetizacao', text: '🐜Deteção'),  
    LocalizableModel(key: 'prestador_nav_edit', text: 'Editar fornecedor de serviços'),
    LocalizableModel(key: 'prestador_nav_new', text: 'Prestador de serviços cadastrais'),
    LocalizableModel(key: 'prestador_infos', text: 'INFORMAÇÕES DO FORNECEDOR'),
    LocalizableModel(key: 'prestador_funcoes', text: 'FUNÇÕES'),
    LocalizableModel(key: 'prestador_selecione_categoria', text:  'Selecione as categorias:'),
    LocalizableModel(key: 'prestador_categoria_desc', text: 'O seu relatório outra(s) categoria(s): (separado por vírgula)'),

    //VISITANTES
    LocalizableModel(key: 'visitantes_list', text: 'Lista de visitantes'),  
    LocalizableModel(key: 'visitantes_nav_new', text: 'Registar novo visitante'),
    LocalizableModel(key: 'visitantes_nav_edit', text: 'Editar visitante'),
    LocalizableModel(key: 'visitantes_infos', text: 'INFORMAÇÕES SOBRE VISITAS'),
    LocalizableModel(key: 'visitantes_data_hora_inicio', text: 'Data e hora de início da libertação'),
    LocalizableModel(key: 'visitantes_data_hora_termino', text: 'Data e hora de fim da libertação'),
    LocalizableModel(key: 'visitante', text: 'Visitante'),
    LocalizableModel(key: 'prestador', text: 'Emprestador'),
    LocalizableModel(key: 'visitante_prestador_servico', text: 'Prestador de serviços'),
    LocalizableModel(key: 'visitante_erro_bloco', text: 'Primeiro selecione o bloco!'),

    //OUTROS
    LocalizableModel(key: 'pessoas', text: 'Pessoas'),
    LocalizableModel(key: 'capacidade_indeterminada', text: 'Capacidade indeterminada'),
    LocalizableModel(key: 'pagos', text: 'Pagos'),
    LocalizableModel(key: 'escolha_opcao_desejada', text: 'Escolha a opção pretendida'),
    LocalizableModel(key: 'ciente', text: 'Ciente'),
    LocalizableModel(key: 'solucionado', text: 'Solucionado'),
    LocalizableModel(key: 'urgente', text: 'Urgente'),
    LocalizableModel(key: 'manutencao', text: 'Manutenção'),
    LocalizableModel(key: 'outros', text: 'Outros'),
    LocalizableModel(key: 'primeiro_documento', text: 'Primeiro Documento'),
    LocalizableModel(key: 'link_erro', text: 'Não foi possível abrir o link'),
    LocalizableModel(key: 'invalid_data', text: 'Data informada inválida!'),
    LocalizableModel(key: 'invalid_hora', text: 'Hora informada inválida!'),
    LocalizableModel(key: 'senhas_nao_conferem', text: 'As senhas introduzidas não conferem.'),
    LocalizableModel(key: 'senha_minimo_caracteres', text: 'A palavra-passe deve conter no mínimo 6 caracteres.'),
    LocalizableModel(key: 'libere_funcoes', text: 'Libere as Funções Desejadas'),
    LocalizableModel(key: 'editar_manutencao', text: 'Editar Manutenção'),
    LocalizableModel(key: 'nova_manutencao', text: 'Nova Manutenção'),
    LocalizableModel(key: 'gerar_alerta', text: 'Gerar alerta para os moradores'),

    LocalizableModel(key: 'moeda', text: 'Moeda'),
    LocalizableModel(key: 'moeda_real', text: 'R\$ (Real Brasileiro)'),
    LocalizableModel(key: 'moeda_dolar_americano', text: 'US\$ (Dolár Americano)'),
    LocalizableModel(key: 'moeda_euro', text: '€ (Euro)'),
    LocalizableModel(key: 'moeda_libra', text: '£ (Libra)'),
    LocalizableModel(key: 'moeda_peso_mexicano', text: 'Mex\$ (Peso Mexicano)'),
    LocalizableModel(key: 'moeda_generico', text: '\$'),

    LocalizableModel(key: 'assinatura_semestral', text: 'Semestral'),
    LocalizableModel(key: 'assinatura_anual', text: 'Anual'),

    LocalizableModel(key: 'meus_condominios', text: 'Meus Condomínios'),
  ];

}
