import 'package:click/utils/localizable/localizable.dart';

class Localizable_Al {

  final List<LocalizableModel> strings = [
    // Idioma
    LocalizableModel(key: 'language_idioma', text: 'Sprache'),
    LocalizableModel(key: 'language_pt_br', text: 'Brasilianisches Portugiesisch'),
    LocalizableModel(key: 'language_pt_pt', text: 'Portugiesisches Portugal'),
    LocalizableModel(key: 'language_en', text: 'Englisch'),
    LocalizableModel(key: 'language_es', text: 'Spanisch'),
    LocalizableModel(key: 'language_al', text: 'Deutsch'),

    // Data
    LocalizableModel(key: 'data_informar', text: 'Geben Sie das gewünschte Datum ein.'),
    LocalizableModel(key: 'data_selecionar_horario', text: 'Wählen Sie die gewünschte Zeit aus.'),
    LocalizableModel(key: 'data_das', text: 'Geben'),    
    LocalizableModel(key: 'data_as', text: 'Zum'),    
    LocalizableModel(key: 'data_e_hora', text: 'Datum und Uhrzeit'),
    LocalizableModel(key: 'dia_e_hora', text: 'Tag und Uhrzeit'),
    LocalizableModel(key: 'dia', text: 'Tag'),
    LocalizableModel(key: 'Tage', text: 'Tage'),
    LocalizableModel(key: 'data', text: 'Datum'),
    LocalizableModel(key: 'datas', text: 'Termine'),
    LocalizableModel(key: 'hora', text: 'Zeit'),
    LocalizableModel(key: 'data_inicio', text: 'Startdatum'),
    LocalizableModel(key: 'hora_inicio', text: 'Startzeit'),
    LocalizableModel(key: 'data_termino', text: 'Enddatum'),
    LocalizableModel(key: 'hora_termino', text: 'Endzeit'),
    LocalizableModel(key: 'data_hora_criacao', text: 'DATUM UND UHRZEIT DER ERSTELLUNG'),
    LocalizableModel(key: 'data_hora_inicio', text: 'Startdatum und -uhrzeit'),
    LocalizableModel(key: 'segunda', text: 'Zweite'),
    LocalizableModel(key: 'terca', text: 'Dritte'),
    LocalizableModel(key: 'quarta', text: 'Vierte'),
    LocalizableModel(key: 'quinta', text: 'Fünfte'),
    LocalizableModel(key: 'sexta', text: 'Freitag'),
    LocalizableModel(key: 'sabado', text: 'Samstag'),
    LocalizableModel(key: 'domingo', text: 'Sonntag'),

    // Modal Select Month
    LocalizableModel(key: 'modal_select_month_btn_ok', text: 'OK'),
    LocalizableModel(key: 'modal_select_month_btn_cancel', text: 'stornieren'),

    //TextField
    LocalizableModel(key: 'textfield_long_placeholder', text: 'Schreiben Sie hier...'),
    LocalizableModel(key: 'textfield_short_placeholder', text: 'Schreiben Sie Ihre Nachricht...'),

    //Label
    LocalizableModel(key: 'label_to', text: 'Zu:'),
    LocalizableModel(key: 'label_of', text: 'von'),
    LocalizableModel(key: 'label_until', text: 'bis'),
    LocalizableModel(key: 'ola', text: 'Hallo'),
    LocalizableModel(key: 'sindico', text: 'Empfänger'),
    LocalizableModel(key: 'morador', text: 'Einwohner'),
    LocalizableModel(key: 'funcionario', text: 'Mitarbeiter'),
    LocalizableModel(key: 'email', text: 'E-Mail'),
    LocalizableModel(key: 'senha', text: 'Passwort'),
    LocalizableModel(key: 'vesaoApp', text: 'Version:'),
    LocalizableModel(key: 'nome', text: 'Name'),
    LocalizableModel(key: 'user_nome_completo', text: 'Vollständiger Name'),
    LocalizableModel(key: 'user_documento', text: 'Ausweisdokument'),
    LocalizableModel(key: 'data_nascimento', text: 'Geburtsdatum'),
    LocalizableModel(key: 'email', text: 'E-Mail'),
    LocalizableModel(key: 'telefone', text: 'Telefon'),
    LocalizableModel(key: 'senha', text: 'Passwort'),
    LocalizableModel(key: 'editar_infos', text: 'Informationen bearbeiten'),
    LocalizableModel(key: 'label_exclusao', text: 'Ausschluss!'),

    LocalizableModel(key: 'lb_areas_sociais', text: 'Soziale Bereiche'),
    LocalizableModel(key: 'lb_area_social', text: 'Sozialer Bereich'),
    LocalizableModel(key: 'lb_financeiro', text: 'Finanziell'),
    LocalizableModel(key: 'lb_assembleia_votacoes', text: 'Versammlungen und Abstimmungen'),
    LocalizableModel(key: 'lb_assembleias', text: 'Versammlungen'),
    LocalizableModel(key: 'lb_assembleia', text: 'Montage'),
    LocalizableModel(key: 'lb_votacoes', text: 'Umfragen'),
    LocalizableModel(key: 'lb_enquetes', text: 'Umfragen'),
    LocalizableModel(key: 'lb_comunicados', text: 'Ankündigungen'),
    LocalizableModel(key: 'lb_comunicado', text: 'Bekanntmachung'),
    LocalizableModel(key: 'lb_ocorrencias', text: 'Vorkommen'),
    LocalizableModel(key: 'lb_ocorrencia', text: 'Auftreten'),
    LocalizableModel(key: 'lb_funcionarios', text: 'Mitarbeiter'),
    LocalizableModel(key: 'lb_funcionarios_condominio', text: 'Personal für Eigentumswohnungen'),
    LocalizableModel(key: 'lb_manut_programadas', text: 'Geplante Wartung'),
    LocalizableModel(key: 'lb_manut_programada', text: 'Geplante Wartung'),
    LocalizableModel(key: 'lb_prestadores_servico', text: 'Dienstleister'),
    LocalizableModel(key: 'lb_agendar_mudanca', text: 'Zeitplanänderung'),
    LocalizableModel(key: 'lb_cadastrar_visitante', text: 'Besucher registrieren'),
    LocalizableModel(key: 'lb_apartamentos', text: 'Wohnungen'),
    LocalizableModel(key: 'lb_apartamento', text: 'Wohnung'),
    LocalizableModel(key: 'lb_docs', text: 'Dokumente'),
    LocalizableModel(key: 'lb_apto', text: 'Wohnung'),
    LocalizableModel(key: 'lb_ref', text: 'Ref.'),
    LocalizableModel(key: 'lb_saldo', text: 'Gleichgewicht'),
    LocalizableModel(key: 'lb_status', text: 'Status'),
    LocalizableModel(key: 'lb_categorias', text: 'Kategorien'),
    LocalizableModel(key: 'lb_categoria', text: 'Kategorie'),
    LocalizableModel(key: 'lb_anexos', text: 'Anhänge'),
    LocalizableModel(key: 'lb_insira_fotos', text: 'Fügen Sie hier Ihre Fotos ein'),
    LocalizableModel(key: 'lb_tipo', text: 'Typ'),
    LocalizableModel(key: 'lb_resposta', text: 'Antwort'),
    LocalizableModel(key: 'lb_todos', text: 'Alle'),
    LocalizableModel(key: 'lb_pendentes', text: 'Anhänger'),
    LocalizableModel(key: 'lb_buscar', text: 'Suchen'),
    LocalizableModel(key: 'lb_aviso', text: 'Beachten'),
    LocalizableModel(key: 'lb_ultima_atualizacao', text: 'Letztes Update'),
    LocalizableModel(key: 'lb_ciente', text: 'Bewusst'),
    LocalizableModel(key: 'lb_pendente', text: 'Ausstehend'),
    LocalizableModel(key: 'lb_aprovado', text: 'Genehmigt'),
    LocalizableModel(key: 'lb_recusado', text: 'Abgelehnt'),
    LocalizableModel(key: 'lb_solucionado', text: 'Gelöst'),
    LocalizableModel(key: 'lb_nao_informado', text: 'Nicht informiert'),
    LocalizableModel(key: 'lb_aceitar', text: 'Akzeptieren'),
    LocalizableModel(key: 'lb_recusar', text: 'Verweigern'),
    LocalizableModel(key: 'lb_finalizar', text: 'Beenden'),

    LocalizableModel(key: 'lb_titulo', text: 'Titel'),
    LocalizableModel(key: 'lb_descricao', text: 'Beschreibung'),
    LocalizableModel(key: 'lb_descricao_opcional', text: 'BESCHREIBUNG (OPTIONAL)'),
    LocalizableModel(key: 'lb_observacoes_opcional', text: 'HINWEISE (OPTIONAL)'),
    LocalizableModel(key: 'lb_observacoes', text: 'Beobachtungen'),    
    LocalizableModel(key: 'lb_inicio', text: 'Start'),
    LocalizableModel(key: 'lb_termino', text: 'Beendigung'),
    LocalizableModel(key: 'lb_autorizado_por', text: 'Autorisiert von'),

    LocalizableModel(key: 'lb_infos_apto', text: 'INFORMATIONEN ZUR WOHNUNG'),
    LocalizableModel(key: 'lb_bloco', text: 'Block'),

    LocalizableModel(key: 'lb_li_concordo', text: 'Ich habe die Regeln gelesen und bin damit einverstanden'),
    LocalizableModel(key: 'lb_complementos', text: 'Add-ons'),

    LocalizableModel(key: 'lb_logout', text: 'Ausgehen'),

    //Button
    LocalizableModel(key: 'btn_save', text: 'SPEICHERN'),
    LocalizableModel(key: 'btn_delete', text: 'Löschen'),
    LocalizableModel(key: 'btn_enviar', text: 'ZUM SENDEN'),
    LocalizableModel(key: 'btn_proximo', text: 'NÄCHSTE'),
    LocalizableModel(key: 'btn_anterior', text: 'VORHERIGE'),

    //UPLOAD
    LocalizableModel(key: 'upload_max_number', text: 'Maximale Anzahl an Dokumenten erreicht'),

    // ALERT
    LocalizableModel(key: 'alert', text: 'Alarm!'),
    LocalizableModel(key: 'alert_alert', text: 'Beachten'),
    LocalizableModel(key: 'alert_success', text: 'Erfolg!'),
    LocalizableModel(key: 'alert_error', text: 'Fehler!'),
    LocalizableModel(key: 'alert_ops', text: 'Hoppla!'),
    LocalizableModel(key: 'alert_invalid_value', text: 'Ungültiger Wert eingegeben!'),
    LocalizableModel(key: 'alert_sim', text: 'Ja'),
    LocalizableModel(key: 'alert_nao', text: 'NEIN'),
    LocalizableModel(key: 'alert_em_breve', text: 'Kurz!'),
    LocalizableModel(key: 'alert_em_breve_description', text: 'Wir arbeiten daran, diesen Service so schnell wie möglich verfügbar zu machen.'),    
    LocalizableModel(key: 'alert_delete_description', text: 'Sind Sie sicher, dass Sie dieses Element dauerhaft löschen möchten?'),
    LocalizableModel(key: 'alert_cancel_description', text: 'Sind Sie sicher, dass Sie diesen Artikel stornieren möchten?'),
    LocalizableModel(key: 'alert_photo_choice', text: 'Möchten Sie jetzt ein Foto machen oder ein Foto aus der Galerie auswählen?'),
    LocalizableModel(key: 'alert_doc_choice', text: 'Möchten Sie ein Dokument oder Bild anhängen?'),
    LocalizableModel(key: 'alert_photo_camera', text: 'Kamera'),
    LocalizableModel(key: 'alert_photo_galeria', text: 'Galerie'),
    LocalizableModel(key: 'alert_photo_image', text: 'Bild'),
    LocalizableModel(key: 'alert_document', text: 'Dokumentieren'),
    LocalizableModel(key: 'alert_generic_error', text: 'Es ist ein Fehler aufgetreten, bitte versuchen Sie es erneut!'),
    LocalizableModel(key: 'alert_list_empty_generic', text: 'Keine Datensätze gefunden!'),
    LocalizableModel(key: 'alert_upload_image', text: 'Fügen Sie das Bild ein.'),
    LocalizableModel(key: 'alert_dados_alterados', text: 'Daten erfolgreich geändert!'),
    LocalizableModel(key: 'alert_nenhum_bloco', text: 'Keine Blöcke gefunden!\nRegistrieren Sie die Einheiten zunächst im Menü „Wohnungen“.'),
    LocalizableModel(key: 'alert_nenhum_apto', text: 'Keine Wohnungen gefunden!\nein Registrieren Sie die Einheiten zunächst im Menü „Wohnungen“ auf dem Startbildschirm.'),

    // ACESSO
    LocalizableModel(key: 'sou_sindico', text: 'Ich bin Syndizier'),
    LocalizableModel(key: 'sou_morador', text: 'Ich bin ein Bewohner'),
    LocalizableModel(key: 'sou_funcionario', text: 'Ich bin Angestellter'),
    LocalizableModel(key: 'view_hello_text', text: 'Sollen wir Ihre erste Eigentumswohnung anmelden?'),
    LocalizableModel(key: 'vamos_cadastrar', text: 'lasst uns registrieren'),
    LocalizableModel(key: 'possuo_cadastro', text: 'Ich habe bereits eine Registrierung'),
    
    // LOGIN
    LocalizableModel(key: 'login_btn_entrar', text: 'EINGEBEN'),
    LocalizableModel(key: 'login_btn_esqueci_senha', text: 'Passwort vergessen?'),
    LocalizableModel(key: 'login_error', text: 'Falscher Login oder Passwort. Versuchen Sie es erneut'),

    // ESQUECI A SENHA
    LocalizableModel(key: 'esqueci_senha_nav', text: 'Passwort vergessen'),
    LocalizableModel(key: 'esqueci_senha_title', text: 'Passwort vergessen?'),
    LocalizableModel(key: 'esqueci_senha_description', text: 'Machen Sie sich keine Sorgen, geben Sie unten Ihre E-Mail-Adresse ein und wir senden Ihnen einen Wiederherstellungslink.'),
    LocalizableModel(key: 'esqueci_senha_send_description', text: 'Der Wiederherstellungslink wurde an Ihre E-Mail-Adresse gesendet.'),    

    // CADASTRO SÍNDICO
    LocalizableModel(key: 'signup_nav_sindico', text: 'Empfängerregistrierung'),
    LocalizableModel(key: 'sindico_nav_edit', text: 'Daten bearbeiten'),
    LocalizableModel(key: 'signup_success', text: 'Registrierung erfolgreich abgeschlossen!'),
    LocalizableModel(key: 'signup_erro_dt_nascimento', text: 'Ungültiges Geburtsdatum!'),
    LocalizableModel(key: 'signup_infos_contato', text: 'KONTAKTINFORMATIONEN'),

    // CADASTRO CONDOMINIO
    LocalizableModel(key: 'signup_cond_nav', text: 'Registrierung von Eigentumswohnungen'),
    LocalizableModel(key: 'condominio_nav_edit', text: 'Eigentumswohnung bearbeiten'),
    LocalizableModel(key: 'condominio_nav_edit_address', text: 'Eigentumswohnung bearbeiten'),
    LocalizableModel(key: 'signup_cond_error_nome', text: 'Geben Sie den Namen der Eigentumswohnung ein.'),
    LocalizableModel(key: 'signup_cond_error_doc', text: 'Legen Sie den Ausweis der Eigentumswohnung vor.'),
    LocalizableModel(key: 'signup_cond_error_subsindico', text: 'Geben Sie den Namen des Stellvertreters ein.'),
    LocalizableModel(key: 'signup_cond_error_dt_inicio_mandato', text: 'Geben Sie das Startdatum des Mandats ein'),
    LocalizableModel(key: 'signup_cond_error_dt_fim_mandato', text: 'Geben Sie das Enddatum des Mandats ein.'),
    LocalizableModel(key: 'signup_cond_error_dt_anterior', text: 'Enddatum vor dem Startdatum.'), 
    LocalizableModel(key: 'signup_cond_error_cep', text: 'Geben Sie die Postleitzahl ein.'),  
    LocalizableModel(key: 'signup_cond_error_pais', text: 'Geben Sie das Land ein.'),  
    LocalizableModel(key: 'signup_cond_error_estado', text: 'Informieren Sie den Staat.'),  
    LocalizableModel(key: 'signup_cond_error_cidade', text: 'Informieren Sie die Stadt.'),  
    LocalizableModel(key: 'signup_cond_error_bairro', text: 'Informieren Sie die Nachbarschaft.'),  
    LocalizableModel(key: 'signup_cond_error_rua', text: 'Rua informieren.'),  
    LocalizableModel(key: 'signup_cond_error_numero', text: 'Geben Sie die Nummer ein.'),  

    LocalizableModel(key: 'signup_cond_nome', text: 'Name der Eigentumswohnung'),
    LocalizableModel(key: 'signup_cond_subsindico_nome', text: 'Name der Tochtergesellschaft'),
    LocalizableModel(key: 'signup_cond_ini_mandato', text: 'Datum des Semesterbeginns'),
    LocalizableModel(key: 'signup_cond_fim_mandato', text: 'Enddatum der Laufzeit'),
    LocalizableModel(key: 'signup_cond_cep', text: 'PLZ'),
    LocalizableModel(key: 'signup_cond_pais', text: 'Land'),  
    LocalizableModel(key: 'signup_cond_uf', text: 'UF'),  
    LocalizableModel(key: 'signup_cond_cidade', text: 'Stadt'),  
    LocalizableModel(key: 'signup_cond_bairro', text: 'Nachbarschaft'),  
    LocalizableModel(key: 'signup_cond_rua', text: 'Straße'),  
    LocalizableModel(key: 'signup_cond_numero', text: 'Nummer'),  
    LocalizableModel(key: 'signup_cond_complemento', text: 'Ergänzen'),  

    LocalizableModel(key: 'signup_cond_valor_total', text: 'Gesamtwert:'),  
    LocalizableModel(key: 'signup_cond_valor_mensal', text: 'R\$ 35,99 / mês'), 
    LocalizableModel(key: 'signup_cond_dias_gratuitos', text: 'Genießen Sie Ihre 45 Tage kostenlos!'), 
    LocalizableModel(key: 'signup_cond_cancele_label', text: 'Kündigen Sie jederzeit!'), 

    LocalizableModel(key: 'signup_cond_sucesso', text: 'Eigentumswohnungsregistrierung ERFOLGREICH'), 

    LocalizableModel(key: 'cond_confirm_delete', text: 'Sind Sie sicher, dass Sie diese Eigentumswohnung dauerhaft löschen möchten?'), 
    LocalizableModel(key: 'signup_confirm_delete', text: 'Sind Sie sicher, dass Sie Ihr Konto dauerhaft löschen möchten?'), 

    LocalizableModel(key: 'condominio_edit_dados', text: 'Eigentumswohnungsdaten bearbeiten'),
    LocalizableModel(key: 'condominio_edit_endereco', text: 'Adresse aktualisieren'),
    
  
    //MANUTENCAO PROGRAMADA
    LocalizableModel(key: 'manut_edit_nav', text: 'Agenda-Termin bearbeiten'), 
    LocalizableModel(key: 'manut_signup_nav', text: 'Neues Engagement auf der Tagesordnung'), 
    LocalizableModel(key: 'manut_about', text: 'ÜBER DAS ENGAGEMENT'), 
    LocalizableModel(key: 'manut_nav', text: 'Wartungsanfragen'), 
    LocalizableModel(key: 'manut_edit', text: 'Anfrage bearbeiten'), 
    LocalizableModel(key: 'manut_new', text: 'Neue Anfrage'), 
    


    //AREA SOCIAL
    LocalizableModel(key: 'area_social_precisa_agendamento', text: 'Terminvereinbarung erforderlich'), 
    LocalizableModel(key: 'area_social_precisa_autorizacao', text: 'Erfordert eine Genehmigung'), 
    LocalizableModel(key: 'area_social_precisa_pagamento', text: 'Zahlung erforderlich'), 
    LocalizableModel(key: 'area_social_agendamentos', text: 'Termine'), 
    LocalizableModel(key: 'area_social_meus_agendamentos', text: 'Meine Zeitpläne'), 
    LocalizableModel(key: 'area_social_nenhum_agendamento', text: 'Sie haben keine Termine'), 
    LocalizableModel(key: 'area_social_nav_new', text: 'Neuer sozialer Bereich'), 
    LocalizableModel(key: 'area_social_dados_iniciais', text: 'ERSTE DATEN'), 
    LocalizableModel(key: 'area_social_capacidade_maxima', text: 'Maximale Kapazität'), 
    LocalizableModel(key: 'area_social_capacidade_vazio', text: 'Lassen Sie es leer, wenn nicht die maximale Kapazität vorhanden ist'), 
    LocalizableModel(key: 'area_social_obrigatoriedades', text: 'VERPFLICHTUNGEN'), 
    LocalizableModel(key: 'area_social_novo_horario', text: 'Neuer Zeitplan'), 
    LocalizableModel(key: 'area_social_erro_normas', text: 'Akzeptieren Sie die Regeln, bevor Sie fortfahren.'), 
    LocalizableModel(key: 'area_social_nav_edit_reserva', text: 'Reservierung bearbeiten'), 
    LocalizableModel(key: 'area_social_nav_reservar', text: 'Buch'), 
    LocalizableModel(key: 'area_social_data_reserva', text: 'Reservierungsdatum:'), 
    LocalizableModel(key: 'area_social_hora_reserva', text: 'Buchungszeit:'), 
    LocalizableModel(key: 'area_social_reservado', text: 'Reserviert:'), 

    //ASSEMBLEIA
    LocalizableModel(key: 'assembleia_infos', text: 'MONTAGEINFORMATIONEN'), 
    LocalizableModel(key: 'assembleia_local', text: 'Standort'), 
    LocalizableModel(key: 'assembleia_nav_edit', text: 'Baugruppe bearbeiten'), 
    LocalizableModel(key: 'assembleia_nav_new', text: 'Neue Versammlung'), 
    LocalizableModel(key: 'assembleia_data_local', text: 'ÜBER DATUM UND ORT'), 
    LocalizableModel(key: 'assembleia_link_online', text: 'Link (wenn die Versammlung online ist)'), 
    LocalizableModel(key: 'assembleia_arquivos', text: 'Insira os arquivos aqui\n(Apenas formato .PDF)'), 

    LocalizableModel(key: 'assembleia_alert_ata', text: 'Geben Sie den ATA ein, um diese Montage abzuschließen'), 
    LocalizableModel(key: 'assembleia_encerrada', text: 'A assembléia foi encerrada!\nA ATA se encontra disponível para consulta no menu "Docs" do seu condomínio.'), 
    LocalizableModel(key: 'assembleia_finalize_upload', text: 'Beenden Sie die Montage.\nLaden Sie das Protokoll hoch'), 
    LocalizableModel(key: 'assembleia_upload_ata', text: 'Fügen Sie hier das Protokoll der Versammlung ein'), 
    

    //VOTACAO
    LocalizableModel(key: 'votacao_signup_informe_opcoes', text: 'Geben Sie Ihre Abstimmungsoptionen ein.'), 
    LocalizableModel(key: 'votacao_signup_nav', text: 'Umfrage erstellen'), 
    LocalizableModel(key: 'votacao_signup_infos', text: 'ABSTIMMUNGSINFORMATIONEN'), 
    LocalizableModel(key: 'votacao_signup_dt_encerramento', text: 'Einsendeschluss'), 
    LocalizableModel(key: 'votacao_opcoes', text: 'OPTIONEN'), 
    LocalizableModel(key: 'votacao_opcao', text: 'Option'), 
    LocalizableModel(key: 'votacao_confirm_delete', text: 'Sind Sie sicher, dass Sie die Abstimmung vor dem geplanten Enddatum abschließen möchten?'), 
    LocalizableModel(key: 'votacao_enquete', text: 'Umfrage'), 
    LocalizableModel(key: 'votacao_infos', text: 'UMFRAGEINFORMATIONEN'), 
    LocalizableModel(key: 'votacao_agendado', text: 'Geplant'), 
    LocalizableModel(key: 'votacao_andamento', text: 'Im Gange'), 
    LocalizableModel(key: 'votacao_finalizado', text: 'Fertig'), 
    LocalizableModel(key: 'votacao_finalizar', text: 'Abstimmung abschließen?'), 
    LocalizableModel(key: 'votacao_fora_periodo', text: 'Abstimmung außerhalb des zulässigen Zeitraums.'), 

    //COMUNICADO
    LocalizableModel(key: 'comunicado_nav_edit', text: 'Ankündigung bearbeiten'), 
    LocalizableModel(key: 'comunicado_nav_new', text: 'Neue Ankündigung'), 
    LocalizableModel(key: 'comunicados_infos', text: 'INFORMATIONEN ZUR VERÖFFENTLICHUNG'), 

    //CONFIGURACAO
    LocalizableModel(key: 'config_delete_account', text: 'A exclusão da sua conta foi solicitada!\nA equipe responsável lhe comunicará do andamento!'), 
    LocalizableModel(key: 'config_nav', text: 'Einstellungen'), 
    LocalizableModel(key: 'config_termos_uso', text: 'Nutzungsbedingungen'), 
    LocalizableModel(key: 'config_politica_privacidade', text: 'Datenschutzrichtlinie'), 
    LocalizableModel(key: 'config_fale_conosco', text: 'Kontaktieren Sie uns'), 
    LocalizableModel(key: 'config_fale_conosco_descricao', text: 'Kontaktieren Sie uns per E-Mail mit Ihren Fragen und/oder Anforderungen.\n\nUnd vergessen Sie nicht, sich auszuweisen.\n\ncontato@click-app.co\n'), 
    LocalizableModel(key: 'config_alt_senha', text: 'Kennwort ändern'), 
    LocalizableModel(key: 'config_delete_cond', text: 'Eigentumswohnung ausschließen'), 
    LocalizableModel(key: 'config_delete_account', text: 'Mein Konto löschen'), 
    LocalizableModel(key: 'config_nova_senha', text: 'Neues Passwort'), 
    LocalizableModel(key: 'config_confirm_nova_senha', text: 'Neues Passwort bestätigen'), 
    LocalizableModel(key: 'config_alt_senha_sucesso', text: 'Passwort erfolgreich geändert!'), 

    //ASSINATURA
    LocalizableModel(key: 'assinatura', text: 'Unterschrift'), 
    LocalizableModel(key: 'assinatura_morador', text: 'Unterschrift des Bewohners'), 
    LocalizableModel(key: 'assinatura_condominio', text: 'Eigentumswohnungsabonnement'), 
    LocalizableModel(key: 'assinatura_erro', text: 'Bei Ihrem Kauf ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.'), 
    LocalizableModel(key: 'assinatura_renovada', text: 'Abonnement erfolgreich verlängert!'), 
    LocalizableModel(key: 'assinatura_produto_nao_localizado', text: 'Produkt nicht gefunden!'), 
    LocalizableModel(key: 'assinatura_erro_loja', text: 'Die App konnte nicht mit dem Store kommunizieren. Bitte versuchen Sie es später noch einmal!'), 
    LocalizableModel(key: 'assinatura_tipo_renovacao', text: 'Verlängerungstyp:'),
    LocalizableModel(key: 'assinatura_mensal', text: 'Monatlich'),
    LocalizableModel(key: 'assinatura_validade', text: 'Gültigkeit:'),
    LocalizableModel(key: 'assinatura_dias_restantes', text: 'Verbleibende Tage:'),
    LocalizableModel(key: 'assinatura_venceu', text: 'Ihr Abonnement ist abgelaufen!'),
    LocalizableModel(key: 'assinatura_renove_agora', text: 'Verlängern Sie jetzt um weitere 30 Tage und bleiben Sie über alles, was in Ihrer Eigentumswohnung passiert, auf dem Laufenden!'),    
    LocalizableModel(key: 'assinatura_cond_renove_agora', text: 'Verlängern Sie jetzt um weitere 30 Tage und garantieren Sie sich mehr Sicherheit bei der Verwaltung Ihrer Eigentumswohnung!'),    
    LocalizableModel(key: 'assinatura_cond_contato_sindico', text: 'Kontaktieren Sie den Hausverwalter und informieren Sie ihn über die Erneuerung des App Click-Plans.'), 
    LocalizableModel(key: 'assinatura_renove_agora_obs', text: 'Wenn Sie noch Tage übrig haben, beginnt die Verlängerung ab dem Ablaufdatum des aktuellen Plans.'),    
    LocalizableModel(key: 'assinatura_btn_mensal_morador', text: 'Jetzt verlängern'),    
    LocalizableModel(key: 'assinatura_btn_mensal_cond', text: 'Jetzt verlängern'),    
    LocalizableModel(key: 'assinatura_renovar_depois', text: 'Später erneuern'),  
    LocalizableModel(key: 'assinatura_renovar_7_dias', text: 'Sie können Ihren Plan noch 7 Tage vor dem Ablaufdatum verlängern!' ),  
      
    

    //DOCS
    LocalizableModel(key: 'docs_nav_atas', text: 'Minuten'), 
    LocalizableModel(key: 'docs_nav', text: 'Unterlagen'), 
    LocalizableModel(key: 'docs_nav_new', text: 'Neues Dokument'), 
    LocalizableModel(key: 'docs_title', text: 'Dokumenttitel'), 
    LocalizableModel(key: 'docs_upload', text: 'Fügen Sie hier Ihr Dokument ein'), 

    //FINANCEIRO
    LocalizableModel(key: 'financeiro_inadimplente', text: 'Säumiger'), 
    LocalizableModel(key: 'financeiro_inadimplentes', text: 'Säumige'), 
    LocalizableModel(key: 'financeiro_meses_aberto', text: 'MONATE GEÖFFNET'), 
    LocalizableModel(key: 'financeiro_nav_relatorio', text: 'Zusammenfassung'), 
    LocalizableModel(key: 'financeiro_nav_resultado', text: 'ERGEBNIS'),
    LocalizableModel(key: 'financeiro_total_receitas', text: 'Gesamtumsatz:'), 
    LocalizableModel(key: 'financeiro_total_despesas', text: 'Gesamtkosten:'), 
    LocalizableModel(key: 'financeiro_resultado_periodo', text: 'Ergebnis der Periode:'), 
    LocalizableModel(key: 'financeiro_nav_arrecadacoes', text: 'Sammlungen'),
    LocalizableModel(key: 'financeiro_sem_lancamentos', text: 'In diesem Zeitraum gibt es keine Veröffentlichungen'),
    LocalizableModel(key: 'financeiro_nenhum_inadimplente', text: 'Keine Säumigen gefunden'),
    LocalizableModel(key: 'financeiro_despesa', text: 'Kosten'), 
    LocalizableModel(key: 'financeiro_despesas', text: 'Kosten'), 
    LocalizableModel(key: 'financeiro_arrecadacoes', text: 'Sammlungen'),  
    LocalizableModel(key: 'financeiro_receita_outras', text: 'Rezept – Andere'),  
    LocalizableModel(key: 'financeiro_receita', text: 'Einnahmen'), 
    LocalizableModel(key: 'financeiro_recebedor', text: 'EMPFÄNGER'), 
    LocalizableModel(key: 'financeiro_fornecedor', text: 'Anbieter'), 
    LocalizableModel(key: 'financeiro_categoria', text: 'Kategorie'), 
    LocalizableModel(key: 'financeiro_dt_pag', text: 'Zahlungsdatum'), 
    LocalizableModel(key: 'financeiro_valores', text: 'WERTE'), 
    LocalizableModel(key: 'financeiro_valor', text: 'Wert'), 
    LocalizableModel(key: 'financeiro_forma_pagamento', text: 'Zahlungsart'), 
    LocalizableModel(key: 'financeiro_parcelas', text: 'Anzahl der Raten'), 
    LocalizableModel(key: 'financeiro_conta_debito', text: 'Sollkonto'),
    LocalizableModel(key: 'financeiro_desc_comprovante', text: 'BESCHREIBUNG UND NACHWEIS (OPTIONAL)'), 
    LocalizableModel(key: 'financeiro_anexo_comprovante', text: 'Klicken Sie hier und fügen Sie ein Foto der Quittung oder NF bei'), 
    LocalizableModel(key: 'financeiro_arrecadacao', text: 'Sammlung'), 
    LocalizableModel(key: 'financeiro_lancamento', text: 'Start'), 
    LocalizableModel(key: 'financeiro_mes_referencia', text: 'Referenzmonat'), 
    LocalizableModel(key: 'financeiro_data_vencimento', text: 'Verfallsdatum'), 
    LocalizableModel(key: 'financeiro_pagador', text: 'Zahler'), 
    LocalizableModel(key: 'financeiro_tipo', text: 'Typ'), 
    LocalizableModel(key: 'financeiro_forn_cliente', text: 'Lieferant / Kunde'), 
    LocalizableModel(key: 'financeiro_data_recebimento', text: 'Empfangsdatum'),
    LocalizableModel(key: 'financeiro_conta_bancaria', text: 'Bankkonto'),
    LocalizableModel(key: 'financeiro_nav_edit', text: 'Version bearbeiten'),
    LocalizableModel(key: 'financeiro_nav_new', text: 'Neue Veröffentlichung'),
    LocalizableModel(key: 'financeiro_saldo_dia', text: 'Bilanz des Tages'),

    LocalizableModel(key: 'financeiro_categ_consumo', text: 'Verbrauch'),
    LocalizableModel(key: 'financeiro_categ_manutencao', text: 'Wartung'),
    LocalizableModel(key: 'financeiro_categ_pessoal', text: 'Jungs'),
    LocalizableModel(key: 'financeiro_categ_impostos', text: 'Steuern'),
    LocalizableModel(key: 'financeiro_categ_adms', text: 'Administrativ'),
    LocalizableModel(key: 'financeiro_categ_outras', text: 'Andere'),

    LocalizableModel(key: 'financeiro_conta_corrente', text: 'Girokonto'),
    LocalizableModel(key: 'financeiro_conta_poupanca', text: 'Ersparnisse'),
    LocalizableModel(key: 'financeiro_conta_outra', text: 'Andere'),

    LocalizableModel(key: 'financeiro_dinheiro', text: 'Geld'),
    LocalizableModel(key: 'financeiro_pix', text: 'Pix'),
    LocalizableModel(key: 'financeiro_boleto', text: 'Ticket'),
    LocalizableModel(key: 'financeiro_cartao_credito', text: 'Kreditkarte'),
    LocalizableModel(key: 'financeiro_cartao_debito', text: 'Debitkarte'),
    LocalizableModel(key: 'financeiro_outra', text: 'Andere'),


    //FUNCIONÁRIO
    LocalizableModel(key: 'funcionario_nav_edit', text: 'Mitarbeiter bearbeiten'), 
    LocalizableModel(key: 'funcionario_nav_new', text: 'Mitarbeiter registrieren'), 
    LocalizableModel(key: 'funcionario_infos_pessoais', text: 'PERSÖNLICHE INFORMATIONEN'), 
    LocalizableModel(key: 'funcionario_infos_funcao', text: 'FUNKTIONSBEZOGENE INFORMATIONEN'), 
    LocalizableModel(key: 'funcionario_funcao', text: 'Funktion'), 
    LocalizableModel(key: 'funcionario_horario_trabalho', text: 'Arbeitszeit'), 
    LocalizableModel(key: 'funcionario_permissoes', text: 'BERECHTIGUNGEN INNERHALB DER ANWENDUNG'),     
    LocalizableModel(key: 'funcionario_permissoes_sobre', text: 'Indem Sie eine Berechtigung aktivieren, geben Sie diesem Mitarbeiter die Autonomie des Managers für das ausgewählte Menü!'),
    LocalizableModel(key: 'funcionario_infos_extra', text: 'ZUSÄTZLICHE INFORMATIONEN (OPTIONAL)'),
    LocalizableModel(key: 'funcionario_infos_extra_1', text: 'Zusätzliche Informationen 1'),
    LocalizableModel(key: 'funcionario_infos_extra_2', text: 'Zusätzliche Informationen 2'),
    LocalizableModel(key: 'funcionario_infos_extra_3', text: 'Zusätzliche Informationen 3'),
    LocalizableModel(key: 'funcionario_infos_extra_4', text: 'Zusätzliche Informationen 4'),
    LocalizableModel(key: 'funcionario_infos_acesso', text: 'ZUGRIFFSINFORMATIONEN'),
    LocalizableModel(key: 'funcionario_senha', text: 'Klicken Sie auf Zugangspasswort'),

    //MORADORES
    LocalizableModel(key: 'moradores_empty', text: 'Derzeit sind keine Bewohner registriert'), 

    //APARTAMENTO
    LocalizableModel(key: 'apto_desc', text: 'Um eine neue Wohnung anzumelden, geben Sie die folgenden Daten ein:'), 
    LocalizableModel(key: 'apto_fracao', text: 'Idealer Bruch'), 
    LocalizableModel(key: 'apto_proprietarios', text: 'Eigentümer:'), 
    LocalizableModel(key: 'apto_inquilinos', text: 'Mieter:'), 
    LocalizableModel(key: 'apto_usuario_criado_msg', text: 'Usuário criado!\nInforme que a senha padrão será o número do documento e que ao entrar na conta a senha poderá ser alterada.'), 
    
    //MUDANCA
    LocalizableModel(key: 'mudanca_nav', text: 'Zeitpläne ändern'),  
    LocalizableModel(key: 'mudanca_nav_edit', text: 'Änderung bearbeiten'),
    LocalizableModel(key: 'mudanca_nav_new', text: 'Änderung anfordern'),
    LocalizableModel(key: 'mudanca_pendente_aprovacao', text: 'Este item não está mais pendente aprovação.\nVocê não pode mais editá-lo.'), 
    LocalizableModel(key: 'mudanca_selecione_apto', text: 'AWählen Sie die gewünschte Wohnung aus'),   
    LocalizableModel(key: 'mudanca_infos_mudanca', text: 'INFORMATIONEN ZUR ÄNDERUNG'),   
    LocalizableModel(key: 'mudanca_motivo_recusa', text: 'Grund für die Ablehnung'),   

    //OCORRÊNCIA
    LocalizableModel(key: 'ocorrencia_sobre', text: 'ÜBER DAS VORGEHEN'),  
    LocalizableModel(key: 'ocorrencia_respondido', text: 'Beantwortet'),  
    LocalizableModel(key: 'ocorrencia_resposta', text: 'Schreiben Sie hier die Antwort an den Bewohner'),  
    LocalizableModel(key: 'ocorrencia_status', text: 'Status auswählen:'), 
    LocalizableModel(key: 'ocorrencia_abertura_nav', text: 'Öffnung von Vorkommnissen'), 
    LocalizableModel(key: 'ocorrencia_erro_tipo', text: 'Wählen Sie die Art des Ereignisses aus!'),     
    LocalizableModel(key: 'ocorrencia_nav_edit', text: 'Wählen Sie die Art des Ereignisses aus!'),   
    LocalizableModel(key: 'ocorrencia_tipo', text: 'Art des Ereignisses'),   

    //PRESTADORES
    LocalizableModel(key: 'prestador_eletricista', text: '⚡ Elektriker'),  
    LocalizableModel(key: 'prestador_hidraulica', text: '🚰 Hydraulik / Sanitär'),  
    LocalizableModel(key: 'prestador_pintor', text: '🎨 Maler'),  
    LocalizableModel(key: 'prestador_pedreiro', text: '🏚 Maurer'),  
    LocalizableModel(key: 'prestador_limpeza', text: '🧹 Reinigung'),  
    LocalizableModel(key: 'prestador_dedetizacao', text: '🐜 Schädlingsbekämpfung'),  
    LocalizableModel(key: 'prestador_nav_edit', text: 'Bearbeiten Sie den Dienstanbieter'),
    LocalizableModel(key: 'prestador_nav_new', text: 'Registrieren Sie den Dienstanbieter'),
    LocalizableModel(key: 'prestador_infos', text: 'ANBIETERINFORMATIONEN'),
    LocalizableModel(key: 'prestador_funcoes', text: 'FUNKTIONEN'),
    LocalizableModel(key: 'prestador_selecione_categoria', text:  'Kategorie(n) auswählen:'),
    LocalizableModel(key: 'prestador_categoria_desc', text: 'Oder geben Sie eine oder mehrere andere Kategorie(n) ein: (durch Komma getrennt)'),

    //VISITANTES
    LocalizableModel(key: 'visitantes_list', text: 'Besucherliste'),  
    LocalizableModel(key: 'visitantes_nav_new', text: 'Neuen Besucher registrieren'),
    LocalizableModel(key: 'visitantes_nav_edit', text: 'Besucher bearbeiten'),
    LocalizableModel(key: 'visitantes_infos', text: 'INFORMATIONEN ZUM BESUCH'),
    LocalizableModel(key: 'visitantes_data_hora_inicio', text: 'Datum und Uhrzeit des Veröffentlichungsstarts'),
    LocalizableModel(key: 'visitantes_data_hora_termino', text: 'Enddatum und -uhrzeit der Veröffentlichung'),
    LocalizableModel(key: 'visitante', text: 'Gast'),
    LocalizableModel(key: 'prestador', text: 'Anbieter'),
    LocalizableModel(key: 'visitante_prestador_servico', text: 'Dienstleister'),
    LocalizableModel(key: 'visitante_erro_bloco', text: 'Wählen Sie zuerst den Block aus!'),

    //OUTROS
    LocalizableModel(key: 'pessoas', text: 'Menschen'),
    LocalizableModel(key: 'capacidade_indeterminada', text: 'Unbestimmte Kapazität'),
    LocalizableModel(key: 'pagos', text: 'Bezahlt'),
    LocalizableModel(key: 'escolha_opcao_desejada', text: 'Wählen Sie die gewünschte Option'),
    LocalizableModel(key: 'ciente', text: 'Bewusst'),
    LocalizableModel(key: 'solucionado', text: 'Gelöst'),
    LocalizableModel(key: 'urgente', text: 'Dringend'),
    LocalizableModel(key: 'manutencao', text: 'Wartung'),
    LocalizableModel(key: 'outros', text: 'Andere'),
    LocalizableModel(key: 'primeiro_documento', text: 'Erstes Dokument'),
    LocalizableModel(key: 'link_erro', text: 'Link kann nicht geöffnet werden'),
    LocalizableModel(key: 'invalid_data', text: 'Ungültiges Datum eingegeben!'),
    LocalizableModel(key: 'invalid_hora', text: 'Ungültige Zeit eingegeben!'),
    LocalizableModel(key: 'senhas_nao_conferem', text: 'Die eingegebenen Passwörter stimmen nicht überein.'),
    LocalizableModel(key: 'senha_minimo_caracteres', text: 'Das Passwort muss mindestens 6 Zeichen enthalten.'),
    LocalizableModel(key: 'libere_funcoes', text: 'Geben Sie die gewünschten Funktionen frei'),
    LocalizableModel(key: 'editar_manutencao', text: 'Wartung bearbeiten'),
    LocalizableModel(key: 'nova_manutencao', text: 'Neue Wartung'),
    LocalizableModel(key: 'gerar_alerta', text: 'Generieren Sie eine Warnung für die Bewohner'),
    
    LocalizableModel(key: 'moeda', text: 'Münze'),
    LocalizableModel(key: 'moeda_real', text: 'R\$ (Brasilianischer Real)'),
    LocalizableModel(key: 'moeda_dolar_americano', text: 'US\$ (US-Dollar)'),
    LocalizableModel(key: 'moeda_euro', text: '€ (Euro)'),
    LocalizableModel(key: 'moeda_libra', text: '£ (Pfund)'),
    LocalizableModel(key: 'moeda_peso_mexicano', text: 'Mex\$ (Mexikanischer Peso)'),
    LocalizableModel(key: 'moeda_generico', text: '\$'),

    LocalizableModel(key: 'assinatura_semestral', text: 'Halbjährlich'),
    LocalizableModel(key: 'assinatura_anual', text: 'Jährlich'),

    LocalizableModel(key: 'meus_condominios', text: 'Meine Eigentumswohnungen'),
  ];

}
